// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-28

//! Build script for baton-rs.
//!
//! Compiles `shim/ffi_shim.c` into a static library that the Rust
//! crate links against. The shim is the only translation unit that
//! `#include`s the iRODS client headers — every iRODS API call
//! baton-rs makes flows through it. Per-iRODS-version differences
//! (4.2 vs 4.3 vs 5.x) live behind `#ifdef`s in the shim.
//!
//! The Rust-side FFI bindings live in `src/ffi.rs` (hand-written to
//! mirror `shim/ffi_shim.h`). bindgen is intentionally not used:
//! Ubuntu 16.04 (the iRODS 4.2.7 build image's base) ships
//! libclang 3.8, which modern bindgen / clang-sys cannot run on
//! (they require libclang ≥ 5.0 for APIs such as
//! `clang_getTranslationUnitTargetInfo`). Hand-rolled bindings keep
//! the build dependency footprint to a C compiler — that, every
//! supported environment has.
//!
//! See issue #9 for the full Session 4.5 rationale.

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=shim/ffi_shim.c");
    println!("cargo:rerun-if-changed=shim/ffi_shim.h");
    println!("cargo:rerun-if-changed=src/ffi.rs");

    // Compile the C shim into libbaton_rs_shim.a and emit the
    // static-link directive. iRODS headers are needed here (and
    // only here) so the shim can call through to them.
    cc::Build::new()
        .file("shim/ffi_shim.c")
        .include("shim")
        .include("/usr/include/irods")
        .warnings(true)
        .compile("baton_rs_shim");

    // Link dynamically against the iRODS client libraries provided
    // by the iRODS .deb packages.
    //
    // iRODS splits its client runtime across at least two shared
    // objects:
    //   - libirods_client — connection/protocol APIs (rcConnect, …)
    //   - libirods_common — utilities, including getRodsEnv
    // If more symbols surface as undefined later, switch to
    // pkg-config.
    println!("cargo:rustc-link-lib=irods_client");
    println!("cargo:rustc-link-lib=irods_common");
}
