// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-24

//! Build script for baton-rs.
//!
//! Generates raw FFI bindings from `wrapper.h` (which transitively includes
//! the iRODS client headers) into `$OUT_DIR/bindings.rs`, and emits link
//! directives for the iRODS client library. `src/ffi.rs` includes the
//! generated file.

use std::env;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=wrapper.h");

    // Link dynamically against the iRODS client library provided by the
    // iRODS .deb packages (decision recorded in Project constants).
    println!("cargo:rustc-link-lib=irods_client");

    let bindings = bindgen::Builder::default()
        .header("wrapper.h")
        .clang_arg("-I/usr/include/irods")
        // Functions used by the connection and error-mapping layers.
        .allowlist_function("rcConnect")
        .allowlist_function("rcDisconnect")
        .allowlist_function("clientLogin")
        .allowlist_function("getRodsEnv")
        .allowlist_function("rErrMsg")
        // Types referenced by those functions.
        .allowlist_type("rcComm_t")
        .allowlist_type("rodsEnv")
        .allowlist_type("rErrMsg_t")
        // Error code constants used when translating iRODS codes into
        // BatonError. The allowlist is broad on purpose — constants are cheap.
        .allowlist_var("CAT_.*")
        .allowlist_var("SYS_.*")
        .allowlist_var("AUTH_.*")
        .allowlist_var("USER_.*")
        .parse_callbacks(Box::new(bindgen::CargoCallbacks::new()))
        .generate()
        .expect("bindgen: failed to generate iRODS bindings");

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("bindgen: failed to write bindings.rs");
}
