// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-28
//
// bindgen entry point. Two header trees are pulled in here during the
// Session 4.5 shim migration (issue #9):
//
//   1. `<rodsClient.h>` — the iRODS client API. Subsystems that haven't
//      been moved behind the shim yet still call iRODS symbols directly
//      (queries, metamod, error-name lookup). The final commit of
//      Session 4.5 removes this include once every caller has migrated,
//      narrowing the libclang-visible surface to just the shim.
//
//   2. `shim/ffi_shim.h` — the version-agnostic C shim. Once iRODS
//      headers are dropped, this is the only thing bindgen sees.
//
// The set of symbols that actually make it into `bindings.rs` is
// controlled by the allowlists in build.rs, not by what this header
// transitively pulls in.

#include <rodsClient.h>
#include "shim/ffi_shim.h"
