// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! Integration test for iRODS authentication via `clientLogin`.
//!
//! Requires `iinit` to have been run once in this environment so that
//! `$HOME/.irods/.irodsA` exists. Both CI's `docker/build.sh` and the
//! devcontainer's `setup.sh` run `iinit` before `cargo test`, so this
//! precondition is already met in the normal flows.

use baton_rs::RodsConnection;

#[test]
fn connect_and_login() {
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login().expect("login");
    // Drop runs rcDisconnect regardless of whether we logged in, so
    // there's no explicit logout step to exercise.
}
