// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! Integration smoke tests for `operations::baton_do::dispatch_one`.
//!
//! Per-operation routing is a discrete unit worth a couple of
//! end-to-end checks against a live iRODS connection. Comprehensive
//! cross-operation coverage lands later in 7b's binary-level
//! integration tests, where the input flows through the clap
//! parser + NDJSON loop + dispatcher in one go.

use std::process::Command;

use baton_rs::operations::baton_do::dispatch_one;
use baton_rs::types::{
    Arguments, BatonDoEnvelope, Collection, DataObject, Operation, OperationResult,
};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors swallowed.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

#[test]
fn dispatch_routes_list_to_list_one_annotated() {
    // Smoke test the live-connection routing for a simple op.
    // We iput a known file, build a `list` envelope with --size,
    // dispatch, and verify the result contains the populated
    // size field. Proves the dispatcher (a) routes by operation,
    // (b) translates Arguments → ListOptions, (c) wraps the
    // returned target in OperationResult::Single.
    let local = "/tmp/baton_rs_dispatch_list_src";
    std::fs::write(local, b"dispatch list").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_dispatch_list_obj";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let mut args = Arguments::default();
    args.size = true;
    let envelope = BatonDoEnvelope {
        operation: Operation::List,
        target: Target::DataObject(DataObject {
            collection: remote_coll.to_string(),
            data_object: data_object.to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        }),
        arguments: args,
    };

    let output = dispatch_one(&mut conn, envelope);

    assert!(
        output.error.is_none(),
        "no error expected for an existing data object: {:?}",
        output.error
    );
    let result = output.result.expect("result populated on success");
    match result {
        OperationResult::Single(Target::DataObject(d)) => {
            assert!(
                d.size.is_some(),
                "list with arguments.size should populate size; got {:?}",
                d.size
            );
        }
        other => panic!("expected Single(DataObject), got {:?}", other),
    }
}

#[test]
fn dispatch_metaquery_returns_deferred_error() {
    // Pins the explicit "not yet implemented" placeholder for
    // metaquery. Will fail loudly when commit 3 of 7b lands the
    // real metaquery routing — at that point this test gets
    // replaced by a proper metaquery happy-path.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let envelope = BatonDoEnvelope {
        operation: Operation::Metaquery,
        target: Target::Collection(Collection {
            collection: "/testZone/home/irods".to_string(),
            avus: None,
            access: None,
            timestamps: None,
            contents: None,
            error: None,
        }),
        arguments: Arguments::default(),
    };

    let output = dispatch_one(&mut conn, envelope);
    assert!(output.result.is_none());
    let err = output.error.expect("metaquery placeholder error");
    assert!(
        err.message.contains("metaquery via baton-do not yet implemented"),
        "error message should be the placeholder; got {:?}",
        err
    );
}

#[test]
fn dispatch_move_requires_arguments_path() {
    // arguments.path is required for move; missing it surfaces
    // a clear envelope-level error before any iRODS call.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let envelope = BatonDoEnvelope {
        operation: Operation::Move,
        target: Target::DataObject(DataObject {
            collection: "/testZone/home/irods".to_string(),
            data_object: "irrelevant".to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        }),
        arguments: Arguments::default(),
    };

    let output = dispatch_one(&mut conn, envelope);
    assert!(output.result.is_none());
    let err = output.error.expect("missing-path error");
    assert!(
        err.message.contains("arguments.path"),
        "error message should mention arguments.path: {:?}",
        err
    );
}
