// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-06

//! Integration smoke tests for `operations::baton_do::dispatch_one`.
//!
//! Per-operation routing is a discrete unit worth a couple of
//! end-to-end checks against a live iRODS connection. Comprehensive
//! cross-operation coverage lands later in 7b's binary-level
//! integration tests, where the input flows through the clap
//! parser + NDJSON loop + dispatcher in one go.

use std::process::Command;

use baton_rs::operations::baton_do::dispatch_one;
use baton_rs::types::{
    Arguments, AvuQuery, BatonDoEnvelope, DataObject, MetaqueryInput, Operation,
    OperationResult, Operator,
};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors swallowed.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

/// `imeta add -d <path> <attr> <value>`: attach an AVU to a data
/// object. Used by the metaquery routing test to stage a queryable
/// AVU.
fn imeta_add_data_object(path: &str, attr: &str, value: &str) {
    let status = Command::new("imeta")
        .args(["add", "-d", path, attr, value])
        .status()
        .expect("failed to spawn imeta");
    assert!(status.success(), "imeta add -d {} failed", path);
}

fn data_object_target(collection: &str, data_object: &str) -> Target {
    Target::DataObject(DataObject {
        collection: collection.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    })
}

#[test]
fn dispatch_routes_list_to_list_one_annotated() {
    // Smoke test the live-connection routing for a simple op.
    // iput a known file, build a `list` envelope with --size,
    // dispatch, and verify the result contains the populated
    // size field. Proves the dispatcher (a) routes by operation,
    // (b) translates Arguments → ListOptions, (c) wraps the
    // returned target in OperationResult::Single.
    let local = "/tmp/baton_rs_dispatch_list_src";
    std::fs::write(local, b"dispatch list").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_dispatch_list_obj";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let mut args = Arguments::default();
    args.size = true;
    let envelope = BatonDoEnvelope::new_standard(
        Operation::List,
        data_object_target(remote_coll, data_object),
        args,
    );

    let output = dispatch_one(&mut conn, envelope);

    assert!(
        output.error.is_none(),
        "no error expected for an existing data object: {:?}",
        output.error
    );
    let result = output.result.expect("result populated on success");
    match result {
        OperationResult::Single(Target::DataObject(d)) => {
            assert!(
                d.size.is_some(),
                "list with arguments.size should populate size; got {:?}",
                d.size
            );
        }
        other => panic!("expected Single(DataObject), got {:?}", other),
    }
}

#[test]
fn dispatch_routes_metaquery_with_operator_through_to_multiple_results() {
    // Live-connection test for the metaquery dispatch path —
    // proves the per-operation target shape (MetaqueryInput with
    // operator-bearing AvuQuery) flows through the custom
    // BatonDoEnvelope deserialiser, into the dispatcher, into
    // operations::metaquery::metaquery, and the matching results
    // come back wrapped in OperationResult::Multiple.
    //
    // Stage one data object with a known AVU, then query for it
    // by AVU value with operator=Equals. The AVU value is
    // deliberately unique to avoid colliding with anything else
    // in the test catalog.
    let local = "/tmp/baton_rs_dispatch_metaquery_src";
    std::fs::write(local, b"dispatch metaquery").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_dispatch_metaquery_obj";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote.clone());

    let attr = "baton_rs_dispatch_metaquery_attr";
    let value = format!("dispatch_metaquery_value_{}", std::process::id());
    imeta_add_data_object(&remote, attr, &value);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let mut input = MetaqueryInput::default();
    input.avus = vec![AvuQuery {
        attribute: attr.to_string(),
        value: value.clone(),
        units: None,
        operator: Operator::Equals,
    }];
    let mut args = Arguments::default();
    args.object = true; // narrow to data objects
    let envelope = BatonDoEnvelope::new_metaquery(input, args);

    let output = dispatch_one(&mut conn, envelope);

    assert!(
        output.error.is_none(),
        "no error expected for a valid metaquery: {:?}",
        output.error
    );
    let result = output.result.expect("metaquery should populate result");
    match result {
        OperationResult::Multiple(targets) => {
            assert!(
                targets.iter().any(|t| matches!(
                    t,
                    Target::DataObject(d)
                        if d.collection == remote_coll && d.data_object == data_object
                )),
                "staged object should appear in metaquery results, got {:?}",
                targets
            );
        }
        other => panic!("metaquery should return Multiple, got {:?}", other),
    }
}

#[test]
fn dispatch_metaquery_decorates_results_with_size_when_requested() {
    // arguments.size on a metaquery dispatches per-result
    // decoration via metaquery::decorate_result, which stats each
    // matching path. Pins the wiring of decoration_options through
    // the dispatcher into the metaquery branch.
    let local = "/tmp/baton_rs_dispatch_metaquery_size_src";
    std::fs::write(local, b"dispatch metaquery size").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_dispatch_metaquery_size_obj";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote.clone());

    let attr = "baton_rs_dispatch_metaquery_size_attr";
    let value = format!("size_decoration_{}", std::process::id());
    imeta_add_data_object(&remote, attr, &value);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let mut input = MetaqueryInput::default();
    input.avus = vec![AvuQuery {
        attribute: attr.to_string(),
        value,
        units: None,
        operator: Operator::Equals,
    }];
    let mut args = Arguments::default();
    args.object = true;
    args.size = true;
    let envelope = BatonDoEnvelope::new_metaquery(input, args);

    let output = dispatch_one(&mut conn, envelope);
    let result = output.result.expect("metaquery result");
    match result {
        OperationResult::Multiple(targets) => {
            let staged = targets.iter().find(|t| matches!(
                t,
                Target::DataObject(d)
                    if d.collection == remote_coll && d.data_object == data_object
            ));
            match staged {
                Some(Target::DataObject(d)) => assert!(
                    d.size.is_some(),
                    "decoration should populate size; got {:?}",
                    d.size,
                ),
                _ => panic!("staged object should appear in results"),
            }
        }
        other => panic!("expected Multiple, got {:?}", other),
    }
}

#[test]
fn dispatch_move_requires_arguments_path() {
    // arguments.path is required for move; missing it surfaces
    // a clear envelope-level error before any iRODS call.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let envelope = BatonDoEnvelope::new_standard(
        Operation::Move,
        data_object_target("/testZone/home/irods", "irrelevant"),
        Arguments::default(),
    );

    let output = dispatch_one(&mut conn, envelope);
    assert!(output.result.is_none());
    let err = output.error.expect("missing-path error");
    assert!(
        err.message.contains("arguments.path"),
        "error message should mention arguments.path: {:?}",
        err
    );
}
