// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! Integration tests for `operations::checksum`.
//!
//! Each test stages and tears down its own data via `iput`, calls
//! `checksum_one`, and verifies the returned digest against an
//! independent MD5 of the source bytes. Cross-checking the
//! server's digest against a client-side computation is the same
//! pattern `tests/put.rs` uses for `--checksum`.

use std::path::PathBuf;
use std::process::Command;

use baton_rs::operations::checksum::{checksum_one, checksum_one_annotated};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed because a test that
/// failed before staging may have nothing to clean up.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

/// Drop guard for a local file written during test setup.
struct LocalCleanup(PathBuf);
impl Drop for LocalCleanup {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", "-K", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput -K {} {} failed", local, remote);
}

/// MD5 digest of `bytes` as 32 lowercase hex chars. Independent
/// oracle for the digest baton-do checksum returns from the
/// server.
fn md5_hex(bytes: &[u8]) -> String {
    format!("{:x}", md5::compute(bytes))
}

fn data_object_target(collection: &str, data_object: &str) -> Target {
    Target::DataObject(DataObject {
        collection: collection.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    })
}

#[test]
fn checksum_returns_server_digest_matching_independent_md5() {
    // Happy path: iput a known file with -K so the catalog has an
    // MD5 recorded up front. checksum_one reads it back via
    // rcDataObjChksum (which returns the stored digest when
    // present). The returned string must contain the MD5 of the
    // local source bytes — proves the catalog matches the upload
    // and that we're routing through the right code path.
    let upload_local = PathBuf::from("/tmp/baton_rs_checksum_basic_src");
    let content: Vec<u8> = (0u8..=255u8).cycle().take(200 * 1024).collect();
    std::fs::write(&upload_local, &content).expect("write source");
    let _local_cleanup = LocalCleanup(upload_local.clone());

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_checksum_basic_obj";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(upload_local.to_str().unwrap(), &remote);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = data_object_target(remote_coll, data_object);
    let output = checksum_one(&mut conn, input).expect("checksum_one");
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };

    let server_chksum = d
        .checksum
        .as_deref()
        .expect("checksum field populated by checksum_one")
        .to_lowercase();
    let local_md5 = md5_hex(&content);
    assert!(
        server_chksum.contains(&local_md5),
        "server digest from checksum_one should contain local MD5: \
         server={server_chksum:?} local={local_md5:?}"
    );
}

#[test]
fn checksum_on_collection_is_error() {
    // rcDataObjChksum is data-object-specific. Passing a Collection
    // surfaces as a typed BatonError before any iRODS call —
    // matches the symmetric guard in operations::get and
    // operations::put.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    });

    let result = checksum_one(&mut conn, input);
    assert!(
        result.is_err(),
        "expected error when calling checksum_one on a collection, got {:?}",
        result
    );
    let err = result.unwrap_err();
    assert!(
        err.message.contains("collection"),
        "error message should mention 'collection': {:?}",
        err
    );
}

#[test]
fn checksum_annotated_error_for_missing_path() {
    // Non-existent data object: rcDataObjChksum returns a
    // not-found code. checksum_one_annotated catches it and
    // emits the input with the error field annotated, leaving the
    // checksum field unset.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = data_object_target(
        "/testZone/home/irods",
        "definitely_not_here_baton_rs_checksum",
    );
    let output = checksum_one_annotated(&mut conn, input);
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        d.error.is_some(),
        "expected error annotation for missing path, got {:?}",
        d
    );
    assert!(
        d.checksum.is_none(),
        "checksum field should NOT be populated on the error path"
    );
}
