// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-01
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01

//! Integration tests for `operations::chmod`.
//!
//! Each test stages and tears down its own data via `iput` /
//! `imkdir`, applies `chmod_one`, and verifies via
//! `operations::list::list_one(--acl)` rather than parsing
//! `ils -A` — going through baton-rs's own well-tested ACL
//! reader keeps the assertions out-of-process-free.

use std::process::Command;

use baton_rs::operations::chmod::{chmod_one, chmod_one_annotated, ChmodOptions};
use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::types::{Acl, AclLevel, Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed because a test that
/// failed before staging may have nothing to clean up.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

fn imkdir(remote: &str) {
    let status = Command::new("imkdir")
        .args(["-p", remote])
        .status()
        .expect("failed to spawn imkdir");
    assert!(status.success(), "imkdir {} failed", remote);
}

/// Pre-stage an ACL via `ichmod` so the revoke tests have something
/// to take away. Errors panic — this is test setup, not assertion.
fn ichmod(level: &str, user: &str, path: &str) {
    let status = Command::new("ichmod")
        .args([level, user, path])
        .status()
        .expect("failed to spawn ichmod");
    assert!(
        status.success(),
        "ichmod {} {} {} failed",
        level,
        user,
        path
    );
}

/// True iff iRODS has a user (or group) with the given name. Same
/// `iquest`-based pattern as `tests/metaquery.rs::user_exists`.
fn user_or_group_exists(name: &str) -> bool {
    Command::new("iquest")
        .args([
            "%s",
            &format!("SELECT USER_NAME WHERE USER_NAME = '{}'", name),
        ])
        .output()
        .map(|out| {
            String::from_utf8_lossy(&out.stdout)
                .lines()
                .any(|line| line.trim() == name)
        })
        .unwrap_or(false)
}

/// Fetch the access list of `target` via `list_one(--acl)`. The
/// well-tested ACL reader is the right oracle for "what's actually
/// recorded in the catalog right now"; parsing `ils -A` would be
/// fragile across iRODS versions.
fn fetch_access(conn: &mut RodsConnection, target: Target) -> Vec<Acl> {
    let opts = ListOptions {
        acl: true,
        ..Default::default()
    };
    let out = list_one(conn, target, &opts).expect("list_one --acl");
    match out {
        Target::DataObject(d) => d.access.unwrap_or_default(),
        Target::Collection(c) => c.access.unwrap_or_default(),
    }
}

fn data_object_target(collection: &str, data_object: &str, access: Option<Vec<Acl>>) -> Target {
    Target::DataObject(DataObject {
        collection: collection.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access,
        replicates: None,
        timestamps: None,
        error: None,
    })
}

fn collection_target(collection: &str, access: Option<Vec<Acl>>) -> Target {
    Target::Collection(Collection {
        collection: collection.to_string(),
        avus: None,
        access,
        timestamps: None,
        contents: None,
        error: None,
    })
}

// `public` is the iRODS built-in group that always exists on any
// zone. Granting / revoking against `public` lets the chmod tests
// exercise real catalog state without having to create a test user
// (which would require admin privileges and per-test setup).
const PUBLIC_GROUP: &str = "public";

#[test]
fn chmod_grants_read_to_public_group() {
    // Happy path: grant `read` to the public group on a fresh
    // collection. The input omits `zone`, so this also pins that
    // baton-rs sends an empty zone string and iRODS resolves to
    // the local zone (matching upstream's
    // parseUserName-driven default).
    let coll = "/testZone/home/irods/baton_rs_chmod_grant";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = collection_target(
        coll,
        Some(vec![Acl {
            owner: PUBLIC_GROUP.to_string(),
            level: AclLevel::Read,
            zone: None,
        }]),
    );

    chmod_one(&mut conn, input, &ChmodOptions::default()).expect("chmod_one grant");

    let access = fetch_access(&mut conn, collection_target(coll, None));
    assert!(
        access.iter().any(|a| a.owner == PUBLIC_GROUP && a.level == AclLevel::Read),
        "public should have read access after grant; got {:?}",
        access
    );
}

#[test]
fn chmod_revokes_with_null_level() {
    // Pre-stage a `read` ACL via ichmod, then null-revoke it via
    // chmod_one. The post-revoke fetch must not show public in the
    // access list (other entries — owner etc. — stay).
    let coll = "/testZone/home/irods/baton_rs_chmod_revoke";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    ichmod("read", PUBLIC_GROUP, coll);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // Sanity: pre-condition — public IS in the access list right now.
    let pre = fetch_access(&mut conn, collection_target(coll, None));
    assert!(
        pre.iter().any(|a| a.owner == PUBLIC_GROUP),
        "test pre-condition violated: public not present after ichmod read; got {:?}",
        pre
    );

    let input = collection_target(
        coll,
        Some(vec![Acl {
            owner: PUBLIC_GROUP.to_string(),
            level: AclLevel::Null,
            zone: None,
        }]),
    );
    chmod_one(&mut conn, input, &ChmodOptions::default()).expect("chmod_one revoke");

    let post = fetch_access(&mut conn, collection_target(coll, None));
    assert!(
        !post.iter().any(|a| a.owner == PUBLIC_GROUP),
        "public should have been revoked; got {:?}",
        post
    );
}

#[test]
fn chmod_applies_multiple_acls_in_one_record() {
    // Two ACL entries in the same record: same target, different
    // grant levels for two distinct identities. Pin that
    // chmod_one's loop applies both rather than stopping at the
    // first.
    //
    // Both grants target `public` with different levels, simulating
    // a two-step grant sequence (read then own — ends up as own).
    // We can't assume a second test user exists, and `public` is
    // the only built-in group we can rely on; using two distinct
    // levels exercises the loop without needing additional
    // identities.
    let coll = "/testZone/home/irods/baton_rs_chmod_multi";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = collection_target(
        coll,
        Some(vec![
            Acl {
                owner: PUBLIC_GROUP.to_string(),
                level: AclLevel::Read,
                zone: None,
            },
            Acl {
                owner: PUBLIC_GROUP.to_string(),
                level: AclLevel::Own,
                zone: None,
            },
        ]),
    );
    chmod_one(&mut conn, input, &ChmodOptions::default()).expect("chmod_one multi");

    let access = fetch_access(&mut conn, collection_target(coll, None));
    let public_entry = access
        .iter()
        .find(|a| a.owner == PUBLIC_GROUP)
        .expect("public should be in the access list");
    assert_eq!(
        public_entry.level,
        AclLevel::Own,
        "second grant should win; got {:?}",
        public_entry
    );
}

#[test]
fn chmod_annotated_error_for_missing_user() {
    // Bogus user name → server returns CAT_INVALID_USER (or
    // similar). chmod_one_annotated catches the error and
    // annotates the input record; the NDJSON stream continues.
    let coll = "/testZone/home/irods/baton_rs_chmod_bad_user";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    let bogus_user = format!("baton_rs_no_such_user_{}", std::process::id());
    assert!(
        !user_or_group_exists(&bogus_user),
        "test prerequisite: iRODS already has a user named {bogus_user:?}; \
         the negative case wouldn't be meaningful",
    );

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = collection_target(
        coll,
        Some(vec![Acl {
            owner: bogus_user.clone(),
            level: AclLevel::Read,
            zone: None,
        }]),
    );
    let output = chmod_one_annotated(&mut conn, input, &ChmodOptions::default());
    let err = match output {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        err.is_some(),
        "expected error annotation for missing user, got Ok"
    );
}

#[test]
fn chmod_annotated_error_for_missing_path() {
    // Path that doesn't exist on the server. iRODS returns a
    // collection-not-found / data-object-not-found code; the
    // annotated wrapper catches it.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = collection_target(
        "/testZone/home/irods/definitely_not_here_baton_rs_chmod",
        Some(vec![Acl {
            owner: PUBLIC_GROUP.to_string(),
            level: AclLevel::Read,
            zone: None,
        }]),
    );
    let output = chmod_one_annotated(&mut conn, input, &ChmodOptions::default());
    let err = match output {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(err.is_some(), "expected error annotation for missing path");
}

#[test]
fn chmod_recursive_applies_to_collection_children() {
    // Stage a parent collection containing one data object and one
    // sub-collection. chmod with --recurse on the parent — iRODS
    // walks server-side, so all three (parent, child object,
    // sub-coll) end up with public in their access list.
    let parent = "/testZone/home/irods/baton_rs_chmod_recurse";
    let sub_coll = format!("{}/sub", parent);
    let data_object = "child.txt";
    let data_path = format!("{}/{}", parent, data_object);

    imkdir(parent);
    imkdir(&sub_coll);
    let local = "/tmp/baton_rs_chmod_recurse_child";
    std::fs::write(local, b"recurse child").expect("write child");
    iput(local, &data_path);
    let _cleanup = IrodsCleanup(parent.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = collection_target(
        parent,
        Some(vec![Acl {
            owner: PUBLIC_GROUP.to_string(),
            level: AclLevel::Read,
            zone: None,
        }]),
    );
    let opts = ChmodOptions { recursive: true };
    chmod_one(&mut conn, input, &opts).expect("chmod_one --recurse");

    // Parent collection.
    let parent_access = fetch_access(&mut conn, collection_target(parent, None));
    assert!(
        parent_access
            .iter()
            .any(|a| a.owner == PUBLIC_GROUP && a.level == AclLevel::Read),
        "parent should have public:read; got {:?}",
        parent_access
    );

    // Sub-collection.
    let sub_access = fetch_access(&mut conn, collection_target(&sub_coll, None));
    assert!(
        sub_access
            .iter()
            .any(|a| a.owner == PUBLIC_GROUP && a.level == AclLevel::Read),
        "sub-collection should have public:read after --recurse; got {:?}",
        sub_access
    );

    // Child data object.
    let obj_access = fetch_access(&mut conn, data_object_target(parent, data_object, None));
    assert!(
        obj_access
            .iter()
            .any(|a| a.owner == PUBLIC_GROUP && a.level == AclLevel::Read),
        "child data object should have public:read after --recurse; got {:?}",
        obj_access
    );
}

#[test]
fn chmod_empty_access_is_no_op() {
    // No access entries on the input → no rcModAccessControl calls,
    // no error, output echoes input. Pin that absence ≠ failure.
    let coll = "/testZone/home/irods/baton_rs_chmod_empty";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let pre = fetch_access(&mut conn, collection_target(coll, None));

    // Empty Vec — has the field, but no entries.
    let input = collection_target(coll, Some(Vec::new()));
    let output = chmod_one(&mut conn, input, &ChmodOptions::default())
        .expect("chmod_one empty access should succeed");

    let post = fetch_access(&mut conn, collection_target(coll, None));
    assert_eq!(
        pre, post,
        "empty access input should leave the catalog untouched"
    );

    // The output target echoes the input — empty access list
    // preserved (Some(vec![])), not collapsed to None.
    match output {
        Target::Collection(c) => assert_eq!(c.access, Some(Vec::new())),
        other => panic!("expected Collection, got {:?}", other),
    }

    // None access — same no-op behaviour, output preserves None.
    let input_none = collection_target(coll, None);
    let output_none = chmod_one(&mut conn, input_none, &ChmodOptions::default())
        .expect("chmod_one None access should succeed");
    match output_none {
        Target::Collection(c) => assert_eq!(c.access, None),
        other => panic!("expected Collection, got {:?}", other),
    }
}

#[test]
fn chmod_breaks_on_first_failure_in_array() {
    // Multi-entry access array where the *second* entry has a
    // bogus user. Per upstream baton (operations.c:420 — `goto
    // finally`), iteration stops at the failing entry: the first
    // entry is applied, the third is not. baton-rs mirrors this
    // for compat (#34 tracks the accumulate alternative).
    let coll = "/testZone/home/irods/baton_rs_chmod_break";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    let bogus_user = format!("baton_rs_no_such_user_break_{}", std::process::id());
    assert!(
        !user_or_group_exists(&bogus_user),
        "test prerequisite: iRODS already has a user named {bogus_user:?}",
    );

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = collection_target(
        coll,
        Some(vec![
            Acl {
                // First entry: public read — should apply.
                owner: PUBLIC_GROUP.to_string(),
                level: AclLevel::Read,
                zone: None,
            },
            Acl {
                // Second entry: bogus user — should error here.
                owner: bogus_user.clone(),
                level: AclLevel::Read,
                zone: None,
            },
            Acl {
                // Third entry: public own — should NOT be applied,
                // because iteration breaks at the second.
                owner: PUBLIC_GROUP.to_string(),
                level: AclLevel::Own,
                zone: None,
            },
        ]),
    );
    let output = chmod_one_annotated(&mut conn, input, &ChmodOptions::default());
    let err = match &output {
        Target::Collection(c) => &c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        err.is_some(),
        "expected error annotation for bogus user in middle position"
    );

    // Check post-state: public should have read (first entry
    // applied), NOT own (third entry skipped due to break-on-first-
    // failure). This is the load-bearing assertion that pins the
    // upstream-parity break behaviour.
    let access = fetch_access(&mut conn, collection_target(coll, None));
    let public_entry = access.iter().find(|a| a.owner == PUBLIC_GROUP);
    assert!(
        matches!(public_entry, Some(a) if a.level == AclLevel::Read),
        "first entry (public:read) should have been applied before the failure; \
         third entry (public:own) should NOT have been applied. Got {:?}",
        access
    );
}

#[test]
fn chmod_recovers_from_error_on_same_connection() {
    // Failing record (bogus user → annotated error) followed by a
    // valid record on the same RodsConnection both processed.
    // Pins that the close-on-error path inside chmod_one /
    // mod_access_control leaves the connection clean for the next
    // iteration — the contract baton-chmod's NDJSON loop relies
    // on. Mirrors the equivalent put / get tests.
    let coll = "/testZone/home/irods/baton_rs_chmod_recover";
    imkdir(coll);
    let _cleanup = IrodsCleanup(coll.to_string());

    let bogus_user = format!("baton_rs_no_such_user_recover_{}", std::process::id());
    assert!(!user_or_group_exists(&bogus_user));

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // Bad input first.
    let bad_input = collection_target(
        coll,
        Some(vec![Acl {
            owner: bogus_user,
            level: AclLevel::Read,
            zone: None,
        }]),
    );
    let bad_out = chmod_one_annotated(&mut conn, bad_input, &ChmodOptions::default());
    let bad_err = match bad_out {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(bad_err.is_some(), "expected error annotation on bogus user");

    // Valid input on the same connection.
    let good_input = collection_target(
        coll,
        Some(vec![Acl {
            owner: PUBLIC_GROUP.to_string(),
            level: AclLevel::Read,
            zone: None,
        }]),
    );
    chmod_one(&mut conn, good_input, &ChmodOptions::default())
        .expect("chmod_one after annotated error on same connection");

    let access = fetch_access(&mut conn, collection_target(coll, None));
    assert!(
        access
            .iter()
            .any(|a| a.owner == PUBLIC_GROUP && a.level == AclLevel::Read),
        "post-recovery grant should have applied; got {:?}",
        access
    );
}
