// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! Best-effort compatibility check between baton-rs's `baton-list` and
//! the upstream baton-list shipped by the iRODS dev image.
//!
//! Skips cleanly if upstream baton-list isn't on `PATH` — neither the
//! devcontainer nor the CI matrix is guaranteed to ship it. The
//! definitive partisan-driven equivalence test lives in Session 8.

use std::io::Write;
use std::process::{Command, Stdio};

use serde_json::Value;

/// Returns `true` if `baton-list --help` runs successfully — i.e. the
/// upstream binary is on PATH and at least responsive.
fn upstream_available() -> bool {
    Command::new("baton-list")
        .arg("--help")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .is_ok()
}

/// Spawn `bin` with `args`, write `input` to its stdin, capture stdout.
/// Panics on spawn / write / non-zero exit — these are test-setup
/// failures, not signal we're trying to compare.
fn run_with_input(bin: &str, args: &[&str], input: &str) -> String {
    let mut child = Command::new(bin)
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .unwrap_or_else(|e| panic!("spawn {}: {}", bin, e));

    child
        .stdin
        .as_mut()
        .expect("stdin handle")
        .write_all(input.as_bytes())
        .expect("write stdin");

    let output = child.wait_with_output().expect("wait_with_output");
    assert!(
        output.status.success(),
        "{} {:?} failed: status={:?} stderr={}",
        bin,
        args,
        output.status,
        String::from_utf8_lossy(&output.stderr),
    );
    String::from_utf8(output.stdout).expect("stdout utf-8")
}

/// Parse NDJSON, dropping blank lines.
fn parse_ndjson(s: &str) -> Vec<Value> {
    s.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| serde_json::from_str(l).unwrap_or_else(|e| panic!("parse {:?}: {}", l, e)))
        .collect()
}

/// `iput -K local remote` (re-exported pattern from `tests/list.rs`).
fn iput_with_checksum(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", "-K", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput -K {} {} failed", local, remote);
}

/// Drop guard for `irm -r -f` (handles both data-objects and populated
/// collections).
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

#[test]
fn baton_list_matches_upstream_on_basic_path_and_size_checksum() {
    if !upstream_available() {
        println!("upstream `baton-list` not on PATH; skipping compat test");
        return;
    }

    // Stage one data object whose size + checksum we can pin.
    let local = "/tmp/baton_rs_compat_input";
    std::fs::write(local, b"compat\n").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_compat";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput_with_checksum(local, &remote);
    let _cleanup = IrodsCleanup(remote);

    // NDJSON input: list the parent collection and the data object.
    let input = format!(
        "{{\"collection\":\"{0}\"}}\n{{\"collection\":\"{0}\",\"data_object\":\"{1}\"}}\n",
        remote_coll, data_object
    );

    let upstream = run_with_input(
        "baton-list",
        &["--size", "--checksum"],
        &input,
    );
    let ours = run_with_input(
        env!("CARGO_BIN_EXE_baton-list"),
        &["--size", "--checksum"],
        &input,
    );

    let upstream_lines = parse_ndjson(&upstream);
    let ours_lines = parse_ndjson(&ours);

    assert_eq!(
        upstream_lines.len(),
        ours_lines.len(),
        "expected the same number of output lines\nupstream:\n{}\nours:\n{}",
        upstream,
        ours,
    );

    // Compare fields that should round-trip identically. Deeper
    // compatibility (avus / acl / replicate / timestamp ordering)
    // belongs to the Session 8 partisan run.
    for (u, o) in upstream_lines.iter().zip(ours_lines.iter()) {
        assert_eq!(u.get("collection"), o.get("collection"), "collection match");
        assert_eq!(
            u.get("data_object"),
            o.get("data_object"),
            "data_object match"
        );
        assert_eq!(u.get("size"), o.get("size"), "size match");
        assert_eq!(u.get("checksum"), o.get("checksum"), "checksum match");
    }
}
