// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-29

//! Integration tests for `RodsConnection`.
//!
//! These require a reachable iRODS server and a populated
//! `$HOME/.irods/irods_environment.json`. CI and the devcontainer both set
//! these up before `cargo test` runs.

use baton_rs::RodsConnection;

#[test]
fn connect_and_disconnect() {
    let conn = RodsConnection::connect_from_env().expect("connect_from_env");
    // Explicit drop so the test exercises the disconnect path
    // directly and fails visibly if teardown aborts — otherwise Drop
    // would run at end of scope and any panic would surface only in
    // the test harness.
    drop(conn);
}
