// Generated by:     Claude Opus 4.8 (1M context)
// Generation date:  2026-07-31

//! Fault-injection integration tests for connection recovery (#108).
//! Need a live iRODS server and the `fault-injection` feature:
//!   cargo test --features fault-injection --test fault_injection
//! Without the feature the module compiles to nothing.
#![cfg(feature = "fault-injection")]

use std::time::Duration;

use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::types::Collection;
use baton_rs::{ReconnectingSession, RodsConnection, Target};

fn testzone_home() -> Target {
    Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    })
}

/// Characterisation test for #108 *before* the fix: after a mid-stream
/// drop, every later record fails on the same dead socket because
/// nothing rebuilds the connection on error. The rebuild-and-retry
/// commit flips the post-drop assertions to expect recovery.
#[test]
fn dropped_connection_cascades_to_every_subsequent_record() {
    let mut conn = RodsConnection::connect_from_env().expect("initial connect");
    conn.login_from_auth_file().expect("initial login");
    // Large threshold so the age watchdog never fires — isolates the
    // error-driven reconnect path, which today doesn't exist.
    let mut session = ReconnectingSession::new(conn, Duration::from_secs(600));

    // Record 1: healthy connection, succeeds.
    let conn = session.maybe_reconnect().expect("pre-drop reconnect check");
    list_one(conn, testzone_home(), &ListOptions::default())
        .expect("record 1 should succeed on a healthy connection");

    // Break the socket underneath the session.
    session.conn_mut().test_force_disconnect();

    // Record 2: first op after the drop fails on the dead socket.
    let conn = session.maybe_reconnect().expect("post-drop reconnect check");
    let err2 = list_one(conn, testzone_home(), &ListOptions::default())
        .expect_err("record 2 should fail on the dropped connection");
    assert!(err2.code < 0, "expected a negative iRODS status, got {err2:?}");

    // Record 3: the cascade — same dead socket, still not rebuilt.
    let conn = session.maybe_reconnect().expect("post-drop reconnect check 2");
    let err3 = list_one(conn, testzone_home(), &ListOptions::default())
        .expect_err("record 3 also fails today: dead connection never rebuilt");
    assert!(err3.code < 0, "expected a negative iRODS status, got {err3:?}");
}
