// Generated by:     Claude Opus 4.8 (1M context)
// Generation date:  2026-07-31
// Last modified by: Claude Opus 4.8 (1M context)
// Last modified:    2026-07-31

//! Fault-injection integration tests for connection recovery (#108).
//! Need a live iRODS server and the `fault-injection` feature:
//!   cargo test --features fault-injection --test fault_injection
//! Without the feature the module compiles to nothing.
#![cfg(feature = "fault-injection")]

use std::time::Duration;

use baton_rs::operations::list::{list_one_annotated, ListOptions};
use baton_rs::types::Collection;
use baton_rs::{ReconnectingSession, RodsConnection, Target};

fn testzone_home() -> Target {
    Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    })
}

/// After a mid-stream drop the session rebuilds before the next record,
/// so the stream recovers instead of cascading (#108). The record in
/// flight when the socket died is annotated; the following record
/// succeeds on the rebuilt connection.
#[test]
fn dropped_connection_recovers_on_the_next_record() {
    let mut conn = RodsConnection::connect_from_env().expect("initial connect");
    conn.login_from_auth_file().expect("initial login");
    // Large threshold so the age watchdog never fires — the rebuild here
    // is driven purely by the connection-level error, not by age.
    let mut session = ReconnectingSession::new(conn, Duration::from_secs(600));

    // Record 1: healthy connection succeeds.
    let c = session.maybe_reconnect().expect("reconnect check 1");
    let out1 = list_one_annotated(c, testzone_home(), &ListOptions::default());
    assert!(out1.error().is_none(), "record 1 should succeed on a healthy connection");

    // Break the socket underneath the session.
    session.conn_mut().test_force_disconnect();

    // Record 2: the in-flight op hits the dead socket and is annotated.
    // note_error flags the session to rebuild before the next record.
    let c = session.maybe_reconnect().expect("reconnect check 2");
    let out2 = list_one_annotated(c, testzone_home(), &ListOptions::default());
    assert!(out2.error().is_some(), "record 2 should fail on the dropped connection");
    session.note_error(out2.error());

    // Record 3: maybe_reconnect honours the flag, rebuilds, and the op
    // succeeds — no cascade.
    let c = session.maybe_reconnect().expect("reconnect check 3 (rebuild)");
    let out3 = list_one_annotated(c, testzone_home(), &ListOptions::default());
    assert!(
        out3.error().is_none(),
        "record 3 should recover on the rebuilt connection; got {:?}",
        out3.error()
    );
}
