// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! Integration test for `operations::list::list_one`.
//!
//! Requires a live iRODS server and an authenticated session — the usual
//! devcontainer / CI setup.

use std::process::Command;

use baton_rs::connection::ObjType;
use baton_rs::operations::list::{list_one, list_one_annotated, ListOptions};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop-guard that removes a remote iRODS path via `irm -f` on Drop,
/// so the test stays idempotent even if its assertions panic.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-f", &self.0]).status();
    }
}

/// `iput -K local remote`: upload and register a server-side checksum.
/// Panics on failure — this is test setup, not an assertion.
fn iput_with_checksum(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", "-K", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput -K {} {} failed", local, remote);
}

#[test]
fn list_home_collection_returns_target_unchanged() {
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        error: None,
    });

    let result = list_one(&mut conn, input, &ListOptions::default()).expect("list_one");

    match result {
        Target::Collection(c) => assert_eq!(c.collection, "/testZone/home/irods"),
        _ => panic!("expected Collection on output, got {:?}", result),
    }
}

#[test]
fn stat_home_collection_reports_collection_type() {
    // A slightly more focused test against the stat wrapper itself — no
    // list_one involvement. Gives us an early signal if a future FFI change
    // breaks the stat return shape specifically.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let stat = conn.stat("/testZone/home/irods").expect("stat");
    assert_eq!(stat.obj_type, ObjType::Collection);
}

#[test]
fn list_data_object_with_size_and_checksum_flags() {
    // Pre-stage a data object we can stat with known size and a server-side
    // checksum. iput -K registers the MD5 as part of the put so stat picks
    // it up without a subsequent ichksum round-trip.
    let local = "/tmp/baton_rs_test_file";
    let content = b"hello world\n";
    std::fs::write(local, content).expect("write local test file");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_test_file";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput_with_checksum(local, &remote);
    let _cleanup = IrodsCleanup(remote.clone());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });

    let opts = ListOptions {
        size: true,
        checksum: true,
        ..Default::default()
    };
    let result = list_one(&mut conn, input, &opts).expect("list_one");

    let d = match result {
        Target::DataObject(d) => d,
        _ => panic!("expected DataObject in output"),
    };
    assert_eq!(d.size, Some(content.len() as u64), "size flag populated");
    assert!(
        d.checksum
            .as_ref()
            .map(|s| !s.is_empty())
            .unwrap_or(false),
        "checksum flag populated (got {:?})",
        d.checksum,
    );
}

#[test]
fn list_data_object_without_flags_preserves_none_fields() {
    // Same path as the previous test — reusing the pre-staged object lets
    // the two tests share an iput, but each one creates its own cleanup
    // guard, and iput -f is idempotent so running them in either order is
    // safe.
    let local = "/tmp/baton_rs_test_file_noflags";
    std::fs::write(local, b"noflags").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_test_file_noflags";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput_with_checksum(local, &remote);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });

    let result = list_one(&mut conn, input, &ListOptions::default()).expect("list_one");
    let d = match result {
        Target::DataObject(d) => d,
        _ => panic!("expected DataObject"),
    };
    assert_eq!(d.size, None, "size stays None when flag is off");
    assert_eq!(d.checksum, None, "checksum stays None when flag is off");
}

#[test]
fn list_one_annotated_annotates_error_for_missing_path() {
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::Collection(Collection {
        collection: "/testZone/home/irods/definitely_not_here_baton_rs".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        error: None,
    });

    // Returns a Target (not a Result) — iRODS error is folded into the
    // output's `error` field instead of propagated.
    let result = list_one_annotated(&mut conn, input, &ListOptions::default());
    let c = match result {
        Target::Collection(c) => c,
        _ => panic!("expected Collection"),
    };
    let err = c.error.as_ref().expect("error field populated");
    // -310000 = USER_FILE_DOES_NOT_EXIST (same code we hit in the
    // fail-fast smoke test before in-band annotation was wired).
    assert_eq!(err.code, -310000, "got {:?}", err);
    assert!(
        err.message.starts_with("USER_FILE_DOES_NOT_EXIST"),
        "expected USER_FILE_DOES_NOT_EXIST in message, got {:?}",
        err.message
    );
}
