// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-28

//! Integration tests for `operations::metaquery`.
//!
//! Each test stages an iRODS object plus AVUs, runs metaquery, and
//! asserts that the staged path turns up in the results. Drop guards
//! tear down on Drop (including across panic).

use std::process::Command;

use baton_rs::operations::metaquery::{metaquery, MetaqueryFlags};
use baton_rs::types::{AvuQuery, MetaqueryInput, Operator};
use baton_rs::{RodsConnection, Target};

struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

fn imeta_add(kind_flag: &str, path: &str, attr: &str, value: &str, units: Option<&str>) {
    let mut args: Vec<String> = vec![
        "add".to_string(),
        kind_flag.to_string(),
        path.to_string(),
        attr.to_string(),
        value.to_string(),
    ];
    if let Some(u) = units {
        args.push(u.to_string());
    }
    let status = Command::new("imeta")
        .args(&args)
        .status()
        .expect("failed to spawn imeta");
    assert!(status.success(), "imeta add {} {} failed", kind_flag, path);
}

#[test]
fn metaquery_finds_data_object_by_avu_equals() {
    let local = "/tmp/baton_rs_metaquery_eq";
    std::fs::write(local, b"metaquery eq").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_metaquery_eq";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote.clone());

    // Use a deliberately unique attribute name so other concurrent
    // tests / leftover state can't pollute the result set.
    imeta_add("-d", &remote, "baton_rs_metaquery_eq_attr", "12345", None);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = MetaqueryInput {
        avus: vec![AvuQuery {
            attribute: "baton_rs_metaquery_eq_attr".to_string(),
            value: "12345".to_string(),
            units: None,
            operator: Operator::Equals,
        }],
        timestamps: vec![],
        access: vec![],
        collection: None,
        zone: None,
    };

    let results = metaquery(
        &mut conn,
        &input,
        &MetaqueryFlags {
            include_data_objects: true,
            include_collections: false,
        },
    )
    .expect("metaquery");

    let found = results.iter().any(|t| match t {
        Target::DataObject(d) => d.collection == remote_coll && d.data_object == data_object,
        _ => false,
    });
    assert!(
        found,
        "expected data object {} in results, got {:?}",
        remote, results
    );
}

#[test]
fn metaquery_with_like_operator_finds_glob_match() {
    let local = "/tmp/baton_rs_metaquery_like";
    std::fs::write(local, b"metaquery like").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_metaquery_like";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote.clone());

    imeta_add("-d", &remote, "baton_rs_metaquery_like_attr", "value-1234", None);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = MetaqueryInput {
        avus: vec![AvuQuery {
            attribute: "baton_rs_metaquery_like_attr".to_string(),
            // Match value-* via SQL LIKE.
            value: "value-%".to_string(),
            units: None,
            operator: Operator::Like,
        }],
        timestamps: vec![],
        access: vec![],
        collection: None,
        zone: None,
    };

    let results = metaquery(
        &mut conn,
        &input,
        &MetaqueryFlags::default(),
    )
    .expect("metaquery");

    let found = results.iter().any(|t| match t {
        Target::DataObject(d) => d.collection == remote_coll && d.data_object == data_object,
        _ => false,
    });
    assert!(
        found,
        "expected data object {} in like-search results, got {:?}",
        remote, results
    );
}

#[test]
fn metaquery_empty_input_returns_empty_results() {
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = MetaqueryInput {
        avus: vec![],
        timestamps: vec![],
        access: vec![],
        collection: None,
        zone: None,
    };

    // Empty criteria deliberately short-circuits to an empty Vec rather
    // than running an unbounded "all rows" query.
    let results = metaquery(&mut conn, &input, &MetaqueryFlags::default())
        .expect("metaquery on empty input");
    assert!(results.is_empty(), "expected no results, got {:?}", results);
}
