// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! Integration tests for `operations::mkdir`.
//!
//! Existence verification goes through `list_one` rather than
//! `ils` parsing — a successful `list_one` against the freshly-
//! created collection proves the catalog now sees the path. Same
//! pattern `tests/chmod.rs` uses for ACL fetch verification.

use std::process::Command;

use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::operations::mkdir::{mkdir_one, mkdir_one_annotated, MkdirOptions};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed because a test that
/// failed before staging may have nothing to clean up.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn collection_target(path: &str) -> Target {
    Target::Collection(Collection {
        collection: path.to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    })
}

/// True iff `path` exists as a collection in the catalog. Goes
/// through `list_one` with default options — the well-tested
/// reader is the right oracle for "what's in the catalog right
/// now". A non-existent path returns Err; an existing path of the
/// wrong type would return a DataObject (not exercised here).
fn collection_exists(conn: &mut RodsConnection, path: &str) -> bool {
    matches!(
        list_one(conn, collection_target(path), &ListOptions::default()),
        Ok(Target::Collection(_))
    )
}

#[test]
fn mkdir_creates_a_new_collection() {
    // Happy path: parent exists (`/testZone/home/irods` is the
    // user's own home), recurse=false. The new leaf collection
    // doesn't exist before the call and does exist after.
    let leaf = "/testZone/home/irods/baton_rs_mkdir_basic";
    let _cleanup = IrodsCleanup(leaf.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    assert!(
        !collection_exists(&mut conn, leaf),
        "test prerequisite: {leaf:?} should not exist before the call"
    );

    let input = collection_target(leaf);
    let input_clone = input.clone();
    let output = mkdir_one(&mut conn, input, &MkdirOptions::default())
        .expect("mkdir_one should succeed against a fresh path with extant parent");

    // Echo byte-equality on success — mkdir_one is a pure
    // side-effect operation, so the output Target must equal the
    // input. Pins against future regressions that mutate, drop,
    // or reorder fields.
    assert_eq!(
        output, input_clone,
        "mkdir_one should echo the input on success without mutating any field"
    );

    assert!(
        collection_exists(&mut conn, leaf),
        "{leaf:?} should exist after mkdir_one"
    );
}

#[test]
fn mkdir_recursive_creates_intermediate_parents() {
    // Nested path several levels deep with recurse=true. The
    // intermediate `level1` and `level2` collections don't exist
    // before the call; both must exist after, plus the leaf. Pins
    // the RECURSIVE_OPR__KW plumbing through the shim.
    let root = "/testZone/home/irods/baton_rs_mkdir_recurse";
    let level1 = format!("{}/level1", root);
    let level2 = format!("{}/level2", level1);
    let leaf = format!("{}/leaf", level2);
    let _cleanup = IrodsCleanup(root.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let opts = MkdirOptions { recurse: true };
    mkdir_one(&mut conn, collection_target(&leaf), &opts).expect("mkdir -p");

    assert!(
        collection_exists(&mut conn, root),
        "root parent should exist after mkdir -p"
    );
    assert!(
        collection_exists(&mut conn, &level1),
        "intermediate level1 should exist after mkdir -p"
    );
    assert!(
        collection_exists(&mut conn, &level2),
        "intermediate level2 should exist after mkdir -p"
    );
    assert!(
        collection_exists(&mut conn, &leaf),
        "leaf should exist after mkdir -p"
    );
}

#[test]
fn mkdir_without_recurse_errors_when_parent_missing() {
    // Nested path with recurse=false → annotated error.
    // Load-bearing pin for "default mkdir doesn't auto-create
    // parents". A regression that always-set RECURSIVE_OPR__KW
    // would silently make this case succeed and the assertion
    // would catch it.
    let absent_parent = "/testZone/home/irods/baton_rs_mkdir_no_parent";
    let leaf = format!("{}/leaf", absent_parent);
    // Cleanup just in case a previous run leaked something.
    let _cleanup = IrodsCleanup(absent_parent.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    assert!(
        !collection_exists(&mut conn, absent_parent),
        "test prerequisite: {absent_parent:?} should not exist"
    );

    let output = mkdir_one_annotated(
        &mut conn,
        collection_target(&leaf),
        &MkdirOptions::default(),
    );
    let err = match output {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        err.is_some(),
        "mkdir_one without recurse should error when the parent is missing"
    );

    // Defensive: confirm the leaf wasn't somehow created despite
    // the error.
    assert!(
        !collection_exists(&mut conn, &leaf),
        "leaf should not exist after a failed mkdir; got it anyway"
    );
}

#[test]
fn mkdir_on_data_object_target_is_error() {
    // mkdir is a collection-only operation. A DataObject target
    // surfaces as a typed BatonError before any iRODS call —
    // matches the symmetric guards in operations::checksum /
    // operations::get / operations::put.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: "/testZone/home/irods".to_string(),
        data_object: "baton_rs_mkdir_data_object_target".to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        file: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });

    let result = mkdir_one(&mut conn, input, &MkdirOptions::default());
    assert!(
        result.is_err(),
        "expected error for data-object target on mkdir, got {:?}",
        result
    );
    let err = result.unwrap_err();
    assert!(
        err.message.contains("data object"),
        "error message should mention data-object target: {:?}",
        err
    );
}

#[test]
fn mkdir_recovers_from_error_on_same_connection() {
    // Failing input (missing parent without recurse → annotated
    // error) followed by a valid input on the same RodsConnection
    // both processed. Pins that the error path inside mkdir_one
    // leaves the connection clean for the next iteration of the
    // NDJSON loop — the contract baton-do's dispatcher will rely
    // on. Mirrors the equivalent rm / chmod / put / get tests.
    let absent_parent = "/testZone/home/irods/baton_rs_mkdir_recover_no_parent";
    let bad_leaf = format!("{}/leaf", absent_parent);

    let good_leaf = "/testZone/home/irods/baton_rs_mkdir_recover_good";
    let _cleanup_bad = IrodsCleanup(absent_parent.to_string());
    let _cleanup_good = IrodsCleanup(good_leaf.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // Bad input first: nested path without recurse.
    let bad_out = mkdir_one_annotated(
        &mut conn,
        collection_target(&bad_leaf),
        &MkdirOptions::default(),
    );
    let bad_err = match bad_out {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        bad_err.is_some(),
        "expected error annotation on missing-parent input"
    );

    // Valid input on the same connection — should succeed even
    // after the previous failure.
    mkdir_one(
        &mut conn,
        collection_target(good_leaf),
        &MkdirOptions::default(),
    )
    .expect("mkdir_one after annotated error on same connection");

    assert!(
        collection_exists(&mut conn, good_leaf),
        "good leaf should exist after recovery"
    );
}

#[test]
fn mkdir_on_existing_collection_is_error() {
    // iRODS returns CAT_NAME_EXISTS_AS_COLLECTION (or similar) when
    // the target is already a collection. The annotated wrapper
    // catches it; pinning this so a future "silently succeed on
    // existing" change is loud rather than silent.
    let coll = "/testZone/home/irods/baton_rs_mkdir_existing";
    let _cleanup = IrodsCleanup(coll.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // First mkdir: succeeds.
    mkdir_one(
        &mut conn,
        collection_target(coll),
        &MkdirOptions::default(),
    )
    .expect("first mkdir should succeed");

    // Second mkdir against the same path: error.
    let output = mkdir_one_annotated(
        &mut conn,
        collection_target(coll),
        &MkdirOptions::default(),
    );
    let err = match output {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        err.is_some(),
        "second mkdir against an existing collection should annotate an error"
    );
}
