// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! Integration tests for `operations::mv`.
//!
//! State verification goes through `list_one` rather than `ils`
//! parsing — `list_one` against the destination should succeed
//! after the move, and against the source should fail
//! (catalog says "not found"). Same oracle pattern the other 7a
//! operation tests use.

use std::process::Command;

use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::operations::mv::{mv_one, mv_one_annotated};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

fn imkdir(remote: &str) {
    let status = Command::new("imkdir")
        .args(["-p", remote])
        .status()
        .expect("failed to spawn imkdir");
    assert!(status.success(), "imkdir -p {} failed", remote);
}

fn data_object_target(collection: &str, data_object: &str) -> Target {
    Target::DataObject(DataObject {
        collection: collection.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    })
}

fn collection_target(path: &str) -> Target {
    Target::Collection(Collection {
        collection: path.to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    })
}

fn data_object_exists(conn: &mut RodsConnection, collection: &str, data_object: &str) -> bool {
    matches!(
        list_one(
            conn,
            data_object_target(collection, data_object),
            &ListOptions::default(),
        ),
        Ok(Target::DataObject(_))
    )
}

fn collection_exists(conn: &mut RodsConnection, path: &str) -> bool {
    matches!(
        list_one(conn, collection_target(path), &ListOptions::default()),
        Ok(Target::Collection(_))
    )
}

#[test]
fn mv_renames_data_object_within_collection() {
    // Happy path: rename within the same collection. The source
    // is gone after, the destination exists and shares the same
    // parent collection.
    let local = "/tmp/baton_rs_mv_rename_src";
    std::fs::write(local, b"mv rename").expect("write");

    let coll = "/testZone/home/irods";
    let src_object = "baton_rs_mv_rename_src";
    let dst_object = "baton_rs_mv_rename_dst";
    let src_path = format!("{}/{}", coll, src_object);
    let dst_path = format!("{}/{}", coll, dst_object);
    iput(local, &src_path);
    // Cleanup catches both — we don't know which path holds the
    // object after the test (assertion failures could leave
    // either).
    let _cleanup_src = IrodsCleanup(src_path);
    let _cleanup_dst = IrodsCleanup(dst_path.clone());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = data_object_target(coll, src_object);
    let input_clone = input.clone();
    let output = mv_one(&mut conn, input, &dst_path).expect("mv_one rename");

    // Echo byte-equality on success — mv_one returns the input
    // describing the *source* path, not the destination. Pins
    // that semantic and catches any future regression that
    // silently rewrites the output to track the destination.
    assert_eq!(
        output, input_clone,
        "mv_one should echo the input describing the source on success"
    );

    assert!(
        !data_object_exists(&mut conn, coll, src_object),
        "source data object should be gone after rename"
    );
    assert!(
        data_object_exists(&mut conn, coll, dst_object),
        "destination data object should exist after rename"
    );
}

#[test]
fn mv_moves_data_object_across_collections() {
    // Cross-collection move. iRODS resolves the destination
    // against the catalog without any client-side scoping check
    // (matches upstream baton — there is no in-zone restriction
    // on the destination).
    let local = "/tmp/baton_rs_mv_cross_src";
    std::fs::write(local, b"mv cross").expect("write");

    let src_coll = "/testZone/home/irods";
    let dst_coll = "/testZone/home/irods/baton_rs_mv_cross_dst";
    imkdir(dst_coll);
    let _cleanup_dst_coll = IrodsCleanup(dst_coll.to_string());

    let object = "baton_rs_mv_cross_obj";
    let src_path = format!("{}/{}", src_coll, object);
    let dst_path = format!("{}/{}", dst_coll, object);
    iput(local, &src_path);
    let _cleanup_src = IrodsCleanup(src_path);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    mv_one(
        &mut conn,
        data_object_target(src_coll, object),
        &dst_path,
    )
    .expect("mv_one cross-collection");

    assert!(
        !data_object_exists(&mut conn, src_coll, object),
        "source should be gone after cross-collection move"
    );
    assert!(
        data_object_exists(&mut conn, dst_coll, object),
        "destination should exist in the new collection after move"
    );
}

#[test]
fn mv_renames_collection() {
    // Collection rename uses RENAME_COLL oprType internally
    // (vs RENAME_DATA_OBJ for data objects). The shim derives
    // the type flag from the Target variant, so this test pins
    // the collection-side path through shim_rename.
    let src_coll = "/testZone/home/irods/baton_rs_mv_coll_src";
    let dst_coll = "/testZone/home/irods/baton_rs_mv_coll_dst";
    imkdir(src_coll);
    let _cleanup_src = IrodsCleanup(src_coll.to_string());
    let _cleanup_dst = IrodsCleanup(dst_coll.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    mv_one(&mut conn, collection_target(src_coll), dst_coll)
        .expect("mv_one collection rename");

    assert!(
        !collection_exists(&mut conn, src_coll),
        "source collection should be gone after rename"
    );
    assert!(
        collection_exists(&mut conn, dst_coll),
        "destination collection should exist after rename"
    );
}

#[test]
fn mv_on_missing_source_annotates_error() {
    // Source path doesn't exist. iRODS returns a not-found code;
    // the annotated wrapper catches it and the stream continues.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let coll = "/testZone/home/irods";
    let src_object = "definitely_not_here_baton_rs_mv";
    let dst_path = format!("{}/baton_rs_mv_unreachable_dst", coll);

    let output = mv_one_annotated(
        &mut conn,
        data_object_target(coll, src_object),
        &dst_path,
    );
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        d.error.is_some(),
        "mv_one against a missing source should annotate an error"
    );
}

#[test]
fn mv_to_existing_destination_annotates_error() {
    // Destination already exists as a data object. iRODS errors
    // (CAT_NAME_EXISTS_AS_DATAOBJ or similar). Pin that the
    // operation doesn't silently overwrite — same defensive
    // posture as mkdir against an existing collection.
    let local = "/tmp/baton_rs_mv_dst_clash";
    std::fs::write(local, b"mv dst clash").expect("write");

    let coll = "/testZone/home/irods";
    let src_object = "baton_rs_mv_clash_src";
    let dst_object = "baton_rs_mv_clash_dst";
    let src_path = format!("{}/{}", coll, src_object);
    let dst_path = format!("{}/{}", coll, dst_object);
    iput(local, &src_path);
    iput(local, &dst_path);
    let _cleanup_src = IrodsCleanup(src_path);
    let _cleanup_dst = IrodsCleanup(dst_path.clone());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let output = mv_one_annotated(
        &mut conn,
        data_object_target(coll, src_object),
        &dst_path,
    );
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        d.error.is_some(),
        "mv_one to an existing destination should annotate an error"
    );

    // Defensive: source should still be in place after the
    // failed move.
    assert!(
        data_object_exists(&mut conn, coll, src_object),
        "source should still exist after a failed move"
    );
}

#[test]
fn mv_with_empty_destination_is_typed_error() {
    // Empty destination is caught client-side with a clearer
    // message than iRODS's USER_INPUT_PATH_ERR. Pure client-side
    // guard, no iRODS round-trip.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let result = mv_one(
        &mut conn,
        data_object_target("/testZone/home/irods", "irrelevant"),
        "",
    );
    assert!(
        result.is_err(),
        "empty destination should error before any iRODS call, got {:?}",
        result
    );
    let err = result.unwrap_err();
    assert!(
        err.message.contains("destination"),
        "error message should mention 'destination': {:?}",
        err
    );
}

#[test]
fn mv_recovers_from_error_on_same_connection() {
    // Failing input (missing source → annotated error) followed
    // by a valid input on the same RodsConnection both processed.
    // Pins that the error path inside mv_one leaves the
    // connection clean for the next NDJSON-loop iteration.
    // Mirrors the equivalent rm / chmod / put / get tests.
    let local = "/tmp/baton_rs_mv_recover_src";
    std::fs::write(local, b"mv recover").expect("write");

    let coll = "/testZone/home/irods";
    let good_src = "baton_rs_mv_recover_src";
    let good_dst = "baton_rs_mv_recover_dst";
    let good_src_path = format!("{}/{}", coll, good_src);
    let good_dst_path = format!("{}/{}", coll, good_dst);
    iput(local, &good_src_path);
    let _cleanup_src = IrodsCleanup(good_src_path);
    let _cleanup_dst = IrodsCleanup(good_dst_path.clone());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // Bad input first: missing source.
    let bad_dst_path = format!("{}/baton_rs_mv_recover_unreachable_dst", coll);
    let bad_out = mv_one_annotated(
        &mut conn,
        data_object_target(coll, "definitely_not_here_baton_rs_mv_recover"),
        &bad_dst_path,
    );
    let bad_err = match bad_out {
        Target::DataObject(d) => d.error,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        bad_err.is_some(),
        "expected error annotation on missing-source input"
    );

    // Valid input on the same connection — should rename.
    mv_one(
        &mut conn,
        data_object_target(coll, good_src),
        &good_dst_path,
    )
    .expect("mv_one after annotated error on same connection");

    assert!(
        !data_object_exists(&mut conn, coll, good_src),
        "good source should have been moved despite the prior failure"
    );
    assert!(
        data_object_exists(&mut conn, coll, good_dst),
        "good destination should exist after recovery"
    );
}
