// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-01
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01


//! Integration tests for `operations::put`.
//!
//! Each test stages a local file under /tmp and tears down the
//! corresponding iRODS data object via `irm -r -f`. Round-trip
//! assertions go through `operations::get::get_one` (already covered
//! end-to-end in 5a) so a put failure that produces wrong bytes is
//! detectable without depending on an out-of-process command.

use std::path::PathBuf;
use std::process::Command;

use base64::engine::general_purpose;
use base64::Engine;

use baton_rs::operations::get::{get_one, GetOptions};
use baton_rs::operations::put::{put_one, put_one_annotated, PutOptions};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed because a test that fails
/// before staging may have nothing to clean up.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

/// Drop guard for a local file written during test setup. Errors
/// swallowed for the same reason — best-effort cleanup.
struct LocalCleanup(PathBuf);
impl Drop for LocalCleanup {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

/// MD5 digest of `bytes` as 32 lowercase hex chars. Used by the
/// `--checksum` cross-check tests to compute an independent oracle
/// for the digest baton-put returns from the server. Pure-Rust via
/// the `md5` runtime dep (also used by `--verify` in
/// `operations::put`); avoiding a system `md5sum` dependency keeps
/// the tests portable across the iRODS dev images.
fn md5_hex(bytes: &[u8]) -> String {
    format!("{:x}", md5::compute(bytes))
}

/// Round-trip helper: pull the freshly-put object back via inline get
/// and base64-decode the result. `operations::get::get_one` is the
/// well-tested oracle for "what's actually on the server right now".
fn fetch_inline_bytes(conn: &mut RodsConnection, collection: &str, data_object: &str) -> Vec<u8> {
    let target = Target::DataObject(DataObject {
        collection: collection.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let out = get_one(conn, target, &GetOptions::default()).expect("get_one for round-trip");
    match out {
        Target::DataObject(d) => general_purpose::STANDARD
            .decode(d.data.as_deref().expect("data field populated"))
            .expect("base64 decode"),
        other => panic!("expected DataObject, got {:?}", other),
    }
}

#[test]
fn put_round_trips_small_data_object() {
    // Uses a byte-cyclic 256-byte payload so any sign-extension /
    // base64 / encoding bug shows up symmetrically with the get
    // tests.
    let upload_dir = "/tmp/baton_rs_put_small_dir";
    let data_object = "baton_rs_put_small_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    let content: Vec<u8> = (0u8..=255u8).collect();
    std::fs::write(&upload_local, &content).expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    put_one(&mut conn, input, &PutOptions::default()).expect("put_one");

    let fetched = fetch_inline_bytes(&mut conn, remote_coll, data_object);
    assert_eq!(fetched, content, "byte mismatch in put → get round-trip");
}

#[test]
fn put_streams_multi_chunk_payload() {
    // ~200 KiB exercises ~3 write iterations through the streaming
    // loop. Catches a regression where bytes go missing between
    // chunk boundaries on the write side.
    let upload_dir = "/tmp/baton_rs_put_multi_dir";
    let data_object = "baton_rs_put_multi_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    let content: Vec<u8> = (0u8..=255u8).cycle().take(200 * 1024).collect();
    std::fs::write(&upload_local, &content).expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    put_one(&mut conn, input, &PutOptions::default()).expect("put_one multi-chunk");

    let fetched = fetch_inline_bytes(&mut conn, remote_coll, data_object);
    assert_eq!(fetched.len(), content.len(), "length mismatch");
    assert!(
        fetched == content,
        "byte mismatch in multi-chunk put → get round-trip"
    );
}

#[test]
fn put_overwrites_existing_data_object() {
    // SHIM_OPEN_WRITE maps to O_WRONLY|O_CREAT|O_TRUNC, so a put over
    // an existing object replaces it wholesale. Pre-seed with longer
    // stale content so a non-truncating write would leave a trailing
    // tail observable through get.
    let upload_dir = "/tmp/baton_rs_put_overwrite_dir";
    let data_object = "baton_rs_put_overwrite_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    let new_content: &[u8] = b"new and shorter";
    std::fs::write(&upload_local, new_content).expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);

    // Pre-seed iRODS with stale content via a separate iput.
    let stale_local = "/tmp/baton_rs_put_overwrite_stale";
    std::fs::write(
        stale_local,
        b"stale content that is longer than the new payload",
    )
    .expect("write stale");
    let stale_status = Command::new("iput")
        .args(["-f", stale_local, &remote])
        .status()
        .expect("iput stale");
    assert!(stale_status.success(), "stale iput failed");
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    put_one(&mut conn, input, &PutOptions::default()).expect("put_one overwrite");

    let fetched = fetch_inline_bytes(&mut conn, remote_coll, data_object);
    assert_eq!(
        fetched, new_content,
        "stale content should have been replaced wholesale by the new put"
    );
}

#[test]
fn put_annotated_error_for_missing_local_file() {
    // No file at <directory>/<data_object>. File::open fails before
    // we touch the network. Surface as an annotated error so the
    // NDJSON stream keeps going.
    let upload_dir = "/tmp/baton_rs_put_missing_local_dir";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let data_object = "baton_rs_put_missing_local_obj";
    // Note: no file written at upload_dir/data_object.

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let output = put_one_annotated(&mut conn, input, &PutOptions::default());
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    let err = d.error.as_ref().expect("expected error annotation");
    assert!(
        err.message.contains("local file"),
        "error message should mention the local file: {:?}",
        err
    );
}

#[test]
fn put_annotated_error_for_missing_directory_field() {
    // The input record carries no `directory` field. `baton-put`
    // refuses early — there's no sensible default for the local
    // source — and surfaces the error in band.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: "/testZone/home/irods".to_string(),
        data_object: "baton_rs_put_no_dir_obj".to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let output = put_one_annotated(&mut conn, input, &PutOptions::default());
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    let err = d.error.as_ref().expect("expected error annotation");
    assert!(
        err.message.contains("directory"),
        "error message should mention the missing directory field: {:?}",
        err
    );
}

// --- --checksum mode ---------------------------------------------------------

#[test]
fn put_with_checksum_populates_output_field() {
    // Smoke test: --checksum populates the output `checksum` field
    // with a non-empty string. The matches-independent-MD5 test
    // below cross-checks the value's correctness.
    let upload_dir = "/tmp/baton_rs_put_chksum_basic_dir";
    let data_object = "baton_rs_put_chksum_basic_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    std::fs::write(&upload_local, b"checksum me").expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let opts = PutOptions {
        checksum: true,
        verify: false,
    };
    let output = put_one(&mut conn, input, &opts).expect("put_one with --checksum");
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };

    let chksum = d
        .checksum
        .as_deref()
        .expect("checksum field populated by --checksum");
    assert!(
        !chksum.is_empty(),
        "checksum field should be a non-empty digest"
    );
}

#[test]
fn put_with_checksum_matches_independent_md5() {
    // Cross-check: with the iRODS client default pinned to MD5 (#25),
    // the server-side digest from rcDataObjChksum must match the MD5
    // of the local source bytes computed by the `md5` dev-dep. This
    // is the strongest guarantee available — proves the bytes the
    // server holds match the bytes the test wrote, not just that
    // *some* digest came back.
    //
    // Multi-chunk payload (~200 KiB) so the test also exercises the
    // streaming-write path, not just the digest plumbing.
    let upload_dir = "/tmp/baton_rs_put_chksum_match_dir";
    let data_object = "baton_rs_put_chksum_match_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    let content: Vec<u8> = (0u8..=255u8).cycle().take(200 * 1024).collect();
    std::fs::write(&upload_local, &content).expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let opts = PutOptions {
        checksum: true,
        verify: false,
    };
    let output = put_one(&mut conn, input, &opts).expect("put_one with --checksum");
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    let server_chksum = d
        .checksum
        .as_deref()
        .expect("checksum field populated by --checksum")
        .to_lowercase();
    let local_md5 = md5_hex(&content);

    // Allow an algorithm prefix on the server side ("MD5:abcd...");
    // bare hex is the typical shape with the pinned MD5 default but
    // the contains() check is robust if iRODS or the test image ever
    // surfaces a prefix. SHA2 servers would be caught by issue #27's
    // matrix work and aren't in scope here.
    assert!(
        server_chksum.contains(&local_md5),
        "server checksum {server_chksum:?} should contain local MD5 {local_md5:?}"
    );
}

#[test]
fn put_without_checksum_leaves_checksum_field_unset() {
    // Symmetric counter-test: a put without --checksum must NOT
    // populate the checksum field. Pins that the wiring is gated on
    // opts.checksum and not unconditionally enabled.
    let upload_dir = "/tmp/baton_rs_put_no_chksum_dir";
    let data_object = "baton_rs_put_no_chksum_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    std::fs::write(&upload_local, b"no checksum requested").expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let output = put_one(&mut conn, input, &PutOptions::default()).expect("put_one");
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        d.checksum.is_none(),
        "put without --checksum should not populate the checksum field; got {:?}",
        d.checksum
    );
}

// --- --verify mode -----------------------------------------------------------
//
// Unhappy-path coverage for --verify lives in operations::put's unit
// tests for `checksums_match` and `verify_checksum` — those exercise
// the comparison logic and the error-message shape directly, without
// having to fault-inject a real client/server byte mismatch (which
// would require either a test-only hook on PutOptions or a race
// against the post-close digest call). The integration tests below
// pin the happy-path wiring: a clean upload through --verify
// returns Ok and populates the checksum field even though --checksum
// wasn't explicitly set.

#[test]
fn put_with_verify_succeeds_on_clean_upload() {
    // Smoke test: --verify on a clean upload (server bytes match
    // local bytes by construction) returns Ok and populates the
    // checksum field. Confirms the verify branch is wired in and
    // doesn't false-fail on an honest upload.
    let upload_dir = "/tmp/baton_rs_put_verify_basic_dir";
    let data_object = "baton_rs_put_verify_basic_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    std::fs::write(&upload_local, b"verify me").expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let opts = PutOptions {
        checksum: false,
        verify: true,
    };
    let output = put_one(&mut conn, input, &opts).expect("put_one with --verify");
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    // --verify implies --checksum on the output: a successful verify
    // populates the checksum field even though the caller didn't
    // explicitly set --checksum. Indirectly proves put_one actually
    // ran the verify branch — if it had skipped the branch the field
    // would still be None.
    assert!(
        d.checksum.is_some(),
        "--verify should populate the checksum field on success; got {:?}",
        d.checksum,
    );
}

#[test]
fn put_with_verify_succeeds_on_multi_chunk_upload() {
    // ~200 KiB payload — the streaming-MD5 context consumes ~3
    // chunks via stream_file_to_handle. A bug in chunk-boundary
    // hashing (wrong slice, missed bytes between iterations) would
    // produce a client digest that disagrees with iRODS's compute
    // over the actual server-side bytes, and verify_checksum would
    // surface the mismatch as an error.
    //
    // Belt-and-braces: cross-check the populated checksum against
    // an independently-computed MD5 of the source bytes. Same shape
    // as the --checksum cross-check, but routed through the verify
    // path so a passing verify_checksum is also proved to have
    // hashed the right bytes.
    let upload_dir = "/tmp/baton_rs_put_verify_multi_dir";
    let data_object = "baton_rs_put_verify_multi_obj";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");
    let upload_local = PathBuf::from(format!("{}/{}", upload_dir, data_object));
    let content: Vec<u8> = (0u8..=255u8).cycle().take(200 * 1024).collect();
    std::fs::write(&upload_local, &content).expect("write source");
    let _local_cleanup = LocalCleanup(upload_local);

    let remote_coll = "/testZone/home/irods";
    let remote = format!("{}/{}", remote_coll, data_object);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let opts = PutOptions {
        checksum: false,
        verify: true,
    };
    let output =
        put_one(&mut conn, input, &opts).expect("put_one with --verify multi-chunk");
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    let server_chksum = d
        .checksum
        .as_deref()
        .expect("--verify should populate the checksum field on success")
        .to_lowercase();
    let local_md5 = md5_hex(&content);
    // contains() rather than == so a future server image surfacing
    // an "MD5:" prefix doesn't false-fail; bare hex is the expected
    // shape under the pinned MD5 client default.
    assert!(
        server_chksum.contains(&local_md5),
        "checksum populated by --verify should match independent MD5: \
         server={server_chksum:?} local={local_md5:?}"
    );
}

// --- connection-reuse cases --------------------------------------------------

#[test]
fn put_handles_sequential_calls_on_same_connection() {
    // baton-put keeps a single RodsConnection alive across every
    // input record in the NDJSON stream. Pin that one
    // open → write → close cycle leaves no residual state on the
    // connection: a second put against a different object after the
    // first must produce that object's bytes — not the previous
    // object's, not a truncated copy, not an iRODS error.
    let upload_dir = "/tmp/baton_rs_put_seq_dir";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");

    let object_a = "baton_rs_put_seq_a";
    let object_b = "baton_rs_put_seq_b";
    let bytes_a: &[u8] = b"first object content";
    let bytes_b: &[u8] = b"second OBJECT content";
    let local_a = PathBuf::from(format!("{}/{}", upload_dir, object_a));
    let local_b = PathBuf::from(format!("{}/{}", upload_dir, object_b));
    std::fs::write(&local_a, bytes_a).expect("write a");
    std::fs::write(&local_b, bytes_b).expect("write b");
    let _local_cleanup_a = LocalCleanup(local_a);
    let _local_cleanup_b = LocalCleanup(local_b);

    let remote_coll = "/testZone/home/irods";
    let remote_a = format!("{}/{}", remote_coll, object_a);
    let remote_b = format!("{}/{}", remote_coll, object_b);
    let _cleanup_a = IrodsCleanup(remote_a);
    let _cleanup_b = IrodsCleanup(remote_b);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let make_input = |name: &str| -> Target {
        Target::DataObject(DataObject {
            collection: remote_coll.to_string(),
            data_object: name.to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: Some(upload_dir.to_string()),
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        })
    };

    // Two sequential puts on the same connection. If the first leaks
    // any state (open L1 descriptor, dangling kw, etc.) the second
    // would either error or write the wrong bytes.
    put_one(&mut conn, make_input(object_a), &PutOptions::default()).expect("put a");
    put_one(&mut conn, make_input(object_b), &PutOptions::default()).expect("put b");

    // Same connection round-trips both reads. fetch_inline_bytes
    // reuses get_one, which is itself well-tested in tests/get.rs.
    let fetched_a = fetch_inline_bytes(&mut conn, remote_coll, object_a);
    let fetched_b = fetch_inline_bytes(&mut conn, remote_coll, object_b);
    assert_eq!(fetched_a, bytes_a, "first object's bytes diverged after sequential put");
    assert_eq!(fetched_b, bytes_b, "second object's bytes diverged after sequential put");
}

#[test]
fn put_recovers_from_error_on_same_connection() {
    // The annotated wrapper must not poison the connection after a
    // per-input failure. Pin: put_one_annotated on a record whose
    // local source is missing (annotates an error), followed by
    // put_one on a real record (succeeds), all on the same
    // RodsConnection. This is the actual contract the NDJSON loop
    // in baton-put relies on — without it, the first bad input
    // would silently break every subsequent line.
    //
    // We use the missing-local-file fault because it's deterministic
    // and exits before any iRODS call. A mid-stream / network fault
    // would be more thorough but is not reproducible from a black-
    // box test.
    let upload_dir = "/tmp/baton_rs_put_recover_dir";
    std::fs::create_dir_all(upload_dir).expect("create upload dir");

    let good_object = "baton_rs_put_recover_obj";
    let good_bytes: &[u8] = b"recovered ok";
    let good_local = PathBuf::from(format!("{}/{}", upload_dir, good_object));
    std::fs::write(&good_local, good_bytes).expect("write source");
    let _local_cleanup = LocalCleanup(good_local);
    // Note: no file written for the bad input below — that's the
    // fault we're injecting.

    let remote_coll = "/testZone/home/irods";
    let remote_good = format!("{}/{}", remote_coll, good_object);
    let _cleanup = IrodsCleanup(remote_good);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let bad_input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: "no_local_file_for_this_record".to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    let bad_output = put_one_annotated(&mut conn, bad_input, &PutOptions::default());
    let bad_d = match bad_output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        bad_d.error.is_some(),
        "expected error annotation on missing-local-file input, got {:?}",
        bad_d
    );

    // Same connection, real input now. If the previous failure
    // leaked any state into the connection, this would either error
    // or upload the wrong bytes.
    let good_input = Target::DataObject(DataObject {
        collection: remote_coll.to_string(),
        data_object: good_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: Some(upload_dir.to_string()),
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });
    put_one(&mut conn, good_input, &PutOptions::default())
        .expect("put_one after annotated error on same connection");

    let fetched = fetch_inline_bytes(&mut conn, remote_coll, good_object);
    assert_eq!(fetched, good_bytes);
}

// --- error / typed-error cases -----------------------------------------------

#[test]
fn put_on_collection_is_error() {
    // Symmetric with get_on_collection_is_error: collection input is
    // an early-rejected error, not a silent no-op.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    });
    let result = put_one(&mut conn, input, &PutOptions::default());
    assert!(
        result.is_err(),
        "expected error when calling put_one on a collection, got {:?}",
        result
    );
}
