// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01

//! Integration tests for `RodsConnection::reconnect` and the
//! `ReconnectingSession` wrapper that drives `--connect-time`.

use std::time::Duration;

use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::types::Collection;
use baton_rs::{ReconnectingSession, RodsConnection, Target};

#[test]
fn reconnect_rebuilds_connection_and_reauthenticates() {
    let mut conn = RodsConnection::connect_from_env().expect("initial connect");
    conn.login_from_auth_file().expect("initial login");

    // Tear down and rebuild in a single call. The full close → open
    // → login chain runs through the C shim; any step failing
    // surfaces as an Err here.
    conn.reconnect().expect("reconnect");

    // If we got here, the fresh connection is authenticated and
    // usable. Drop tears it down on exit.
}

#[test]
fn reconnecting_session_force_reconnects_when_threshold_is_zero() {
    // Threshold = 0 forces a reconnect on every maybe_reconnect()
    // call. The post-reconnect connection must remain usable for
    // ordinary operations — drive a stat through list_one to
    // confirm the rebuilt session can still talk to the server.
    let mut conn = RodsConnection::connect_from_env().expect("initial connect");
    conn.login_from_auth_file().expect("initial login");
    let mut session = ReconnectingSession::new(conn, Duration::from_secs(0));

    let target = Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    });

    // First record after construction: threshold is 0, so
    // maybe_reconnect tears down and rebuilds before this op runs.
    let conn = session
        .maybe_reconnect()
        .expect("first reconnect via session");
    let _ = list_one(conn, target.clone(), &ListOptions::default())
        .expect("list_one after first reconnect");

    // Second record on the same session: threshold is still 0 so
    // reconnect fires again. Pins that the session is reusable
    // across many records — what the NDJSON loop in the binaries
    // relies on.
    let conn = session
        .maybe_reconnect()
        .expect("second reconnect via session");
    let _ = list_one(conn, target, &ListOptions::default())
        .expect("list_one after second reconnect");
}

#[test]
fn reconnecting_session_skips_reconnect_when_within_threshold() {
    // Conventional 600s threshold: maybe_reconnect should be a
    // no-op for a freshly-constructed session and the underlying
    // connection's identity should be preserved across the call.
    // We can't directly observe "did we reconnect?" — but we can
    // observe that a sequence of operations keeps working with no
    // sleep, and that's what production binaries actually need.
    let mut conn = RodsConnection::connect_from_env().expect("initial connect");
    conn.login_from_auth_file().expect("initial login");
    let mut session = ReconnectingSession::new(conn, Duration::from_secs(600));

    let target = Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    });

    // Three back-to-back records inside the threshold window — the
    // wrapper should keep using the same underlying connection.
    for i in 0..3 {
        let conn = session
            .maybe_reconnect()
            .unwrap_or_else(|e| panic!("session healthy at iteration {i}: {e}"));
        let _ = list_one(conn, target.clone(), &ListOptions::default())
            .unwrap_or_else(|e| panic!("list_one healthy at iteration {i}: {e}"));
    }
}
