// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! Integration test for `RodsConnection::reconnect`.
//!
//! Exercises the "disconnect then bring the connection back" path that
//! will eventually sit behind the `--connect-time` CLI flag. Doing it
//! explicitly (no timer) keeps the test deterministic — no `sleep`, no
//! dependence on session-idle behaviour of the server.

use baton_rs::RodsConnection;

#[test]
fn reconnect_rebuilds_connection_and_reauthenticates() {
    let mut conn = RodsConnection::connect_from_env().expect("initial connect");
    conn.login_from_auth_file().expect("initial login");

    // Tear down and rebuild in a single call. Internally: rcDisconnect,
    // rcConnect, obfGetPw, clientLoginWithPassword — any step failing
    // surfaces as an Err here.
    conn.reconnect().expect("reconnect");

    // If we got here, the fresh connection is authenticated and usable.
    // Drop runs rcDisconnect on exit.
}
