// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! Integration tests for `operations::rm`.
//!
//! Removal verification goes through `list_one` rather than `ils`
//! parsing — `list_one` returns Err for paths the catalog doesn't
//! know about, which we treat as the "removed" signal. Same
//! pattern `tests/rmdir.rs` and `tests/mkdir.rs` use.

use std::process::Command;

use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::operations::rm::{rm_one, rm_one_annotated};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed because rm tests will
/// usually have already removed the staged object themselves;
/// this is purely a safety-net for failed runs.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

fn data_object_target(collection: &str, data_object: &str) -> Target {
    Target::DataObject(DataObject {
        collection: collection.to_string(),
        data_object: data_object.to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    })
}

/// True iff `path` exists as a data object in the catalog.
/// `list_one` returns Err for unknown paths — we treat that as
/// "removed".
fn data_object_exists(conn: &mut RodsConnection, collection: &str, data_object: &str) -> bool {
    matches!(
        list_one(
            conn,
            data_object_target(collection, data_object),
            &ListOptions::default(),
        ),
        Ok(Target::DataObject(_))
    )
}

#[test]
fn rm_removes_data_object() {
    // Happy path: iput a file, rm it via rm_one, confirm the
    // catalog no longer sees it.
    let local = "/tmp/baton_rs_rm_basic_src";
    std::fs::write(local, b"rm basic").expect("write");

    let remote_coll = "/testZone/home/irods";
    let data_object = "baton_rs_rm_basic_obj";
    let remote = format!("{}/{}", remote_coll, data_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    assert!(
        data_object_exists(&mut conn, remote_coll, data_object),
        "test prerequisite: object should exist after iput"
    );

    let input = data_object_target(remote_coll, data_object);
    let input_clone = input.clone();
    let output = rm_one(&mut conn, input)
        .expect("rm_one should succeed against an existing data object");

    // Echo byte-equality on success — rm_one is a pure
    // side-effect operation, so the output Target must equal the
    // input describing the (now-removed) data object.
    assert_eq!(
        output, input_clone,
        "rm_one should echo the input on success without mutating any field"
    );

    assert!(
        !data_object_exists(&mut conn, remote_coll, data_object),
        "data object should not exist after rm_one"
    );
}

#[test]
fn rm_on_collection_target_is_error() {
    // rm is data-objects-only. A Collection target surfaces as a
    // typed BatonError before any iRODS call — matches upstream
    // baton's `represents_data_object` guard
    // (baton/src/operations.c:752-755) and the symmetric guard
    // in operations::rmdir for the inverse case.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::Collection(Collection {
        collection: "/testZone/home/irods".to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    });

    let result = rm_one(&mut conn, input);
    assert!(
        result.is_err(),
        "expected error for collection target on rm, got {:?}",
        result
    );
    let err = result.unwrap_err();
    assert!(
        err.message.contains("collection"),
        "error message should mention 'collection': {:?}",
        err
    );
}

#[test]
fn rm_on_missing_data_object_annotates_error() {
    // Path that doesn't exist on the server. iRODS returns a
    // not-found code; the annotated wrapper catches it and the
    // stream continues.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = data_object_target(
        "/testZone/home/irods",
        "definitely_not_here_baton_rs_rm",
    );
    let output = rm_one_annotated(&mut conn, input);
    let d = match output {
        Target::DataObject(d) => d,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(
        d.error.is_some(),
        "rm_one against a non-existent path should annotate an error"
    );
}

#[test]
fn rm_recovers_from_error_on_same_connection() {
    // Failing input (missing path → annotated error) followed by
    // a valid input on the same RodsConnection both processed.
    // Mirrors the equivalent put / get / chmod tests — pins that
    // the error path inside rm_one leaves the connection clean
    // for the next iteration of the NDJSON loop.
    let local = "/tmp/baton_rs_rm_recover_src";
    std::fs::write(local, b"rm recover").expect("write");

    let remote_coll = "/testZone/home/irods";
    let good_object = "baton_rs_rm_recover_obj";
    let remote = format!("{}/{}", remote_coll, good_object);
    iput(local, &remote);
    let _cleanup = IrodsCleanup(remote);

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // Bad input first.
    let bad_input = data_object_target(
        remote_coll,
        "no_such_data_object_baton_rs_rm_recover",
    );
    let bad_out = rm_one_annotated(&mut conn, bad_input);
    let bad_err = match bad_out {
        Target::DataObject(d) => d.error,
        other => panic!("expected DataObject, got {:?}", other),
    };
    assert!(bad_err.is_some(), "expected error on missing-path input");

    // Valid input on the same connection — should remove the
    // object even after the previous failure.
    rm_one(&mut conn, data_object_target(remote_coll, good_object))
        .expect("rm_one after annotated error on same connection");

    assert!(
        !data_object_exists(&mut conn, remote_coll, good_object),
        "good object should have been removed despite the prior failure"
    );
}
