// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-12

//! Integration tests for `operations::rmdir`.
//!
//! Existence verification goes through `list_one` rather than
//! `ils` parsing — a `list_one` against a removed path returns an
//! `Err` (catalog says "not found"), which we treat as the
//! "collection no longer exists" signal. Same oracle pattern
//! `tests/mkdir.rs` and `tests/chmod.rs` use.

use std::process::Command;

use baton_rs::operations::list::{list_one, ListOptions};
use baton_rs::operations::rmdir::{rmdir_one, rmdir_one_annotated, RmdirOptions};
use baton_rs::types::{Collection, DataObject};
use baton_rs::{RodsConnection, Target};

/// Drop guard: `irm -r -f` removes data objects and populated
/// collections alike. Errors are swallowed — defensive cleanup
/// even after a successful rmdir test, in case an assertion
/// failed before the rmdir ran.
struct IrodsCleanup(String);
impl Drop for IrodsCleanup {
    fn drop(&mut self) {
        let _ = Command::new("irm").args(["-r", "-f", &self.0]).status();
    }
}

fn collection_target(path: &str) -> Target {
    Target::Collection(Collection {
        collection: path.to_string(),
        avus: None,
        access: None,
        timestamps: None,
        contents: None,
        error: None,
    })
}

/// True iff `path` exists as a collection in the catalog.
/// `list_one` returns Err for paths the catalog doesn't know
/// about; we treat that as "removed" for the rmdir tests.
fn collection_exists(conn: &mut RodsConnection, path: &str) -> bool {
    matches!(
        list_one(conn, collection_target(path), &ListOptions::default()),
        Ok(Target::Collection(_))
    )
}

/// Stage an empty collection via `imkdir`. Returns once it's in
/// the catalog. Panics on failure — test setup, not assertion.
fn imkdir(remote: &str) {
    let status = Command::new("imkdir")
        .args(["-p", remote])
        .status()
        .expect("failed to spawn imkdir");
    assert!(status.success(), "imkdir -p {} failed", remote);
}

/// `iput -f` for the populated-collection tests where we need a
/// real data object as a child.
fn iput(local: &str, remote: &str) {
    let status = Command::new("iput")
        .args(["-f", local, remote])
        .status()
        .expect("failed to spawn iput");
    assert!(status.success(), "iput {} {} failed", local, remote);
}

#[test]
fn rmdir_removes_empty_collection() {
    // Happy path: pre-staged empty collection, recurse=false,
    // force=false. After the rmdir the catalog no longer sees
    // the path.
    let coll = "/testZone/home/irods/baton_rs_rmdir_empty";
    imkdir(coll);
    // Cleanup guard runs after the test so failure paths don't
    // leak the staged collection.
    let _cleanup = IrodsCleanup(coll.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    assert!(
        collection_exists(&mut conn, coll),
        "test prerequisite: {coll:?} should exist after imkdir"
    );

    let input = collection_target(coll);
    let input_clone = input.clone();
    let output = rmdir_one(&mut conn, input, &RmdirOptions::default())
        .expect("rmdir_one against an empty collection should succeed");

    // Echo byte-equality on success — rmdir_one is a pure
    // side-effect operation, so the output Target must equal the
    // input describing the (now-removed) collection.
    assert_eq!(
        output, input_clone,
        "rmdir_one should echo the input on success without mutating any field"
    );

    assert!(
        !collection_exists(&mut conn, coll),
        "{coll:?} should not exist after rmdir_one"
    );
}

#[test]
fn rmdir_recursive_removes_populated_collection() {
    // Populated collection: parent + child data object + sub-
    // collection. recurse=true → iRODS walks server-side and
    // removes everything in one call. Pins the
    // RECURSIVE_OPR__KW plumbing through the shim.
    let parent = "/testZone/home/irods/baton_rs_rmdir_recurse";
    let sub_coll = format!("{}/sub", parent);
    let data_path = format!("{}/child.txt", parent);

    imkdir(parent);
    imkdir(&sub_coll);
    let local = "/tmp/baton_rs_rmdir_recurse_child";
    std::fs::write(local, b"recurse child").expect("write child");
    iput(local, &data_path);
    let _cleanup = IrodsCleanup(parent.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let opts = RmdirOptions {
        recurse: true,
        force: false,
    };
    rmdir_one(&mut conn, collection_target(parent), &opts)
        .expect("rmdir_one --recurse should succeed against a populated collection");

    assert!(
        !collection_exists(&mut conn, parent),
        "parent {parent:?} should not exist after recursive rmdir"
    );
    assert!(
        !collection_exists(&mut conn, &sub_coll),
        "sub-collection should have been removed by recurse"
    );
}

#[test]
fn rmdir_without_recurse_errors_on_populated_collection() {
    // Load-bearing pin for "default rmdir doesn't auto-remove
    // children". iRODS returns CAT_COLLECTION_NOT_EMPTY (or
    // similar) when recurse is unset on a populated target. A
    // regression that always-set RECURSIVE_OPR__KW would
    // silently succeed; this test catches it.
    let parent = "/testZone/home/irods/baton_rs_rmdir_no_recurse_populated";
    let data_path = format!("{}/child.txt", parent);

    imkdir(parent);
    let local = "/tmp/baton_rs_rmdir_no_recurse_child";
    std::fs::write(local, b"populated child").expect("write child");
    iput(local, &data_path);
    let _cleanup = IrodsCleanup(parent.to_string());

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let output = rmdir_one_annotated(
        &mut conn,
        collection_target(parent),
        &RmdirOptions::default(),
    );
    let err = match output {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        err.is_some(),
        "rmdir_one without recurse should annotate an error on a populated collection"
    );

    // Defensive: confirm the parent (and child) are still in
    // place after the failed call.
    assert!(
        collection_exists(&mut conn, parent),
        "parent should still exist after a failed rmdir; got it removed"
    );
}

#[test]
fn rmdir_on_data_object_target_is_error() {
    // rmdir is a collection-only operation. A DataObject target
    // surfaces as a typed BatonError before any iRODS call —
    // matches upstream's symmetric type-mismatch guard for
    // `remove` vs `rmdir` at baton/src/operations.c:752-755 and
    // 822-827.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let input = Target::DataObject(DataObject {
        collection: "/testZone/home/irods".to_string(),
        data_object: "baton_rs_rmdir_data_object_target".to_string(),
        size: None,
        checksum: None,
        data: None,
        directory: None,
        file: None,
        avus: None,
        access: None,
        replicates: None,
        timestamps: None,
        error: None,
    });

    let result = rmdir_one(&mut conn, input, &RmdirOptions::default());
    assert!(
        result.is_err(),
        "expected error for data-object target on rmdir, got {:?}",
        result
    );
    let err = result.unwrap_err();
    assert_eq!(
        err.code, -310000,
        "rmdir on a data-object target should surface as -310000 (USER_FILE_DOES_NOT_EXIST): {:?}",
        err
    );
    assert!(
        err.message.contains("data object"),
        "error message should mention data-object target: {:?}",
        err
    );
}

#[test]
fn rmdir_recovers_from_error_on_same_connection() {
    // Failing input (missing collection → annotated error)
    // followed by a valid input on the same RodsConnection both
    // processed. Pins that the error path inside rmdir_one
    // leaves the connection clean for the next NDJSON-loop
    // iteration. Mirrors the equivalent rm / chmod / put / get
    // tests.
    let good_coll = "/testZone/home/irods/baton_rs_rmdir_recover_good";
    imkdir(good_coll);
    let _cleanup_good = IrodsCleanup(good_coll.to_string());

    let bad_coll = "/testZone/home/irods/baton_rs_rmdir_recover_bad_does_not_exist";

    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    // Bad input first.
    let bad_out = rmdir_one_annotated(
        &mut conn,
        collection_target(bad_coll),
        &RmdirOptions::default(),
    );
    let bad_err = match bad_out {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        bad_err.is_some(),
        "expected error annotation on missing-collection input"
    );

    // Valid input on the same connection — empty collection,
    // should be removed.
    rmdir_one(
        &mut conn,
        collection_target(good_coll),
        &RmdirOptions::default(),
    )
    .expect("rmdir_one after annotated error on same connection");

    assert!(
        !collection_exists(&mut conn, good_coll),
        "good collection should have been removed despite the prior failure"
    );
}

#[test]
fn rmdir_on_missing_collection_annotates_error() {
    // Path that doesn't exist on the server. iRODS returns a
    // collection-not-found code; the annotated wrapper catches
    // it and the stream continues.
    let mut conn = RodsConnection::connect_from_env().expect("connect_from_env");
    conn.login_from_auth_file().expect("login_from_auth_file");

    let absent = "/testZone/home/irods/baton_rs_rmdir_definitely_not_here";
    let output = rmdir_one_annotated(
        &mut conn,
        collection_target(absent),
        &RmdirOptions::default(),
    );
    let err = match output {
        Target::Collection(c) => c.error,
        other => panic!("expected Collection, got {:?}", other),
    };
    assert!(
        err.is_some(),
        "rmdir_one against a non-existent path should annotate an error"
    );
}
