// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-28
//
// baton-rs C shim — stable, version-agnostic API over the iRODS client
// libraries, narrowed to just the surface baton-rs uses.
//
// The point of this layer is to give bindgen a tractable input. iRODS's
// own headers transitively pull in modern C++ constructs that older
// libclang releases (notably the 3.8 shipped in Ubuntu 16.04, which is
// the base for the iRODS 4.2.7 dev image) cannot parse — see issue #9
// for the full root-cause writeup.
//
// All iRODS-specific types are kept opaque or remapped to plain-C
// structs. Per-iRODS-major-version differences (4.2 vs 4.3 vs 5.x)
// live behind `#ifdef` blocks in `ffi_shim.c`, never in callers'
// generated bindings.

#ifndef BATON_RS_FFI_SHIM_H
#define BATON_RS_FFI_SHIM_H

#ifdef __cplusplus
extern "C" {
#endif

// (Function declarations and type definitions arrive subsystem-by-
// subsystem in the following commits — connection lifecycle first,
// then queries, then metamod, then error-name lookup.)

#ifdef __cplusplus
}
#endif

#endif // BATON_RS_FFI_SHIM_H
