// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-28
//
// Implementation of the baton-rs C shim. See `ffi_shim.h` for the
// rationale and intended scope.
//
// This translation unit will grow as each subsystem is migrated:
//
//   1. Connection lifecycle (rcConnect / clientLoginWithPassword /
//      obfGetPw / getRodsEnv / rcObjStat / rcDisconnect / freeRodsObjStat)
//   2. Catalog queries (rcGenQuery + addInxIval / addInxVal /
//      clearGenQueryInp / freeGenQueryOut)
//   3. AVU mutation (rcModAVUMetadata)
//   4. Error-name lookup (rodsErrorName)
//
// At which point Rust callers stop touching iRODS APIs directly,
// `wrapper.h` switches from `rodsClient.h` to this header, and the
// libclang version constraint that forces 4.2.7 into experimental
// mode goes away. iRODS's own headers will only be `#include`d by
// this file (per-version-gated where needed).

#include "ffi_shim.h"
