// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-28
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-28
//
// Implementation of the baton-rs C shim. See `ffi_shim.h` for the
// rationale and intended scope.
//
// This translation unit is the *only* place baton-rs `#include`s the
// iRODS client headers. All Rust callers see only the opaque types and
// POD structs declared in `ffi_shim.h`. Per-version differences
// belong here behind `#ifdef` blocks.
//
// `shim_rods_conn_t` is a forward-declared opaque alias for iRODS's
// `rcComm_t` — we cast at the function boundaries. There's no separate
// allocation; the lifetime of a `shim_rods_conn_t *` is exactly the
// lifetime of the underlying `rcComm_t *` returned by `rcConnect`.

#include "ffi_shim.h"

#include <stdlib.h>
#include <string.h>

#include <rodsClient.h>

// --- Connection lifecycle ----------------------------------------------------

int shim_get_env(shim_env_t *out) {
    if (!out) return -1;

    rodsEnv env;
    memset(&env, 0, sizeof(env));
    int status = getRodsEnv(&env);
    if (status != 0) return status;

    // strncpy + explicit NUL gives well-defined truncation on inputs
    // that exceed our shim_env_t buffer. iRODS's NAME_LEN is 64; our
    // SHIM_ENV_FIELD_LEN is 256, so truncation is unlikely in practice.
    strncpy(out->host, env.rodsHost, SHIM_ENV_FIELD_LEN - 1);
    out->host[SHIM_ENV_FIELD_LEN - 1] = '\0';
    out->port = env.rodsPort;
    strncpy(out->user, env.rodsUserName, SHIM_ENV_FIELD_LEN - 1);
    out->user[SHIM_ENV_FIELD_LEN - 1] = '\0';
    strncpy(out->zone, env.rodsZone, SHIM_ENV_FIELD_LEN - 1);
    out->zone[SHIM_ENV_FIELD_LEN - 1] = '\0';

    return 0;
}

shim_rods_conn_t *shim_open(
    const char *host,
    int         port,
    const char *user,
    const char *zone,
    int        *status_out,
    char       *err_msg,
    int         err_msg_len)
{
    rErrMsg_t err;
    memset(&err, 0, sizeof(err));

    rcComm_t *conn = rcConnect(host, port, user, zone, /* reconnFlag */ 0, &err);
    if (!conn) {
        if (status_out) *status_out = err.status;
        if (err_msg && err_msg_len > 0) {
            strncpy(err_msg, err.msg, (size_t)(err_msg_len - 1));
            err_msg[err_msg_len - 1] = '\0';
        }
        return NULL;
    }
    if (status_out) *status_out = 0;
    return (shim_rods_conn_t *)conn;
}

int shim_close(shim_rods_conn_t *conn) {
    if (!conn) return 0;
    return rcDisconnect((rcComm_t *)conn);
}

// --- Authentication ----------------------------------------------------------

int shim_get_password(char *buf, int buf_len) {
    // obfGetPw doesn't accept a length argument — it just writes into
    // the caller's buffer and trusts the buffer is large enough for
    // MAX_PASSWORD_LEN (~50 bytes). Sanity-check on the way in so a
    // caller passing a tiny buffer fails predictably here rather than
    // corrupting memory.
    if (!buf || buf_len < 64) return -1;
    return obfGetPw(buf);
}

int shim_login_password(shim_rods_conn_t *conn, const char *password) {
    // clientLoginWithPassword takes a non-const char* for legacy
    // reasons; the cast is safe because the function uses the password
    // as input only.
    return clientLoginWithPassword((rcComm_t *)conn, (char *)password);
}

// --- Stat --------------------------------------------------------------------

int shim_stat(shim_rods_conn_t *conn, const char *path, shim_stat_t *out) {
    if (!out || !path) return -1;

    dataObjInp_t inp;
    memset(&inp, 0, sizeof(inp));

    size_t path_len = strlen(path);
    if (path_len >= MAX_NAME_LEN) return -1;
    memcpy(inp.objPath, path, path_len);
    // memset above zero-initialised the rest of objPath, so the
    // NUL terminator is already in place.

    rodsObjStat_t *stat = NULL;
    int status = rcObjStat((rcComm_t *)conn, &inp, &stat);
    if (status < 0) return status;
    if (!stat) return -1;

    out->size = (long long)stat->objSize;
    strncpy(out->checksum, stat->chksum, SHIM_STAT_CHECKSUM_LEN - 1);
    out->checksum[SHIM_STAT_CHECKSUM_LEN - 1] = '\0';
    out->obj_type = (int)stat->objType;

    freeRodsObjStat(stat);
    return 0;
}
