// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! `baton-do` dispatcher: route an envelope to the right
//! operations function and assemble the output.
//!
//! Each input NDJSON line is a [`BatonDoEnvelope`]. The
//! dispatcher matches on `envelope.operation`, builds per-op
//! options from `envelope.arguments`, calls the matching
//! `*_one_annotated` from the operations modules, and assembles a
//! [`BatonDoOutput`] with exactly one of `result` or `error`
//! populated.
//!
//! Per-op error annotations from the underlying functions get
//! pulled to envelope-level error per upstream's
//! `add_error_value` behaviour at
//! `baton/src/operations.c:129-136`. Target's own `error` field
//! is cleared on the way through so the wire shape never
//! double-emits the annotation.
//!
//! ## Metaquery — deferred
//!
//! Metaquery is the only operation whose wire-format target
//! doesn't fit baton-rs's existing [`Target`] type — its target
//! is closer to [`MetaqueryInput`] (which carries `AvuQuery` /
//! `TimestampQuery` / `AccessQuery` with operator fields, and a
//! top-level `zone`). Mapping `Target` → `MetaqueryInput`
//! best-effort would silently drop operators and zone scoping;
//! that's a real wire-compat gap.
//!
//! Commit 2 of 7b returns a placeholder error for metaquery.
//! Commit 3 of 7b will land the proper fix — likely a
//! per-operation target shape on the envelope so metaquery's
//! richer input type travels through serde without
//! mid-dispatcher conversion.

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::operations::{checksum, chmod, get, list, metamod, mkdir, mv, put, rm, rmdir};
use crate::types::{
    Arguments, BatonDoEnvelope, BatonDoOutput, MetamodInput, MetamodOperation, Operation,
    OperationResult, Target,
};

/// Top-level dispatcher. Always returns a [`BatonDoOutput`] —
/// per-input failures are in-band annotated, only fatal
/// connection-level failures escape this layer (and they happen
/// in the binary's NDJSON loop, not here).
pub fn dispatch_one(
    conn: &mut RodsConnection,
    envelope: BatonDoEnvelope,
) -> BatonDoOutput {
    let (result, error) = dispatch_inner(conn, &envelope);
    BatonDoOutput {
        envelope,
        result,
        error,
    }
}

fn dispatch_inner(
    conn: &mut RodsConnection,
    envelope: &BatonDoEnvelope,
) -> (Option<OperationResult>, Option<BatonError>) {
    match envelope.operation {
        Operation::List => {
            let opts = list_options_from_arguments(&envelope.arguments);
            let out = list::list_one_annotated(conn, envelope.target.clone(), &opts);
            split_result(out)
        }
        Operation::Get => {
            let opts = get::GetOptions {
                save: envelope.arguments.save,
            };
            let out = get::get_one_annotated(conn, envelope.target.clone(), &opts);
            split_result(out)
        }
        Operation::Put => {
            let opts = put::PutOptions {
                checksum: envelope.arguments.checksum,
                verify: envelope.arguments.verify,
            };
            let out = put::put_one_annotated(conn, envelope.target.clone(), &opts);
            split_result(out)
        }
        Operation::Chmod => {
            let opts = chmod::ChmodOptions {
                recursive: envelope.arguments.recurse,
            };
            let out = chmod::chmod_one_annotated(conn, envelope.target.clone(), &opts);
            split_result(out)
        }
        Operation::Metamod => match metamod_input_from_envelope(envelope) {
            Ok(input) => {
                let out = metamod::metamod_one_annotated(conn, input);
                if let Some(err) = out.error {
                    (None, Some(err))
                } else {
                    // Echo the original envelope target on
                    // success — metamod has no per-op output to
                    // surface beyond "applied".
                    (Some(OperationResult::Single(envelope.target.clone())), None)
                }
            }
            Err(err) => (None, Some(err)),
        },
        Operation::Metaquery => (
            None,
            Some(BatonError {
                code: -1,
                message: "metaquery via baton-do not yet implemented (lands in 7b commit 3 \
                          alongside the per-operation target-shape fix)"
                    .to_string(),
            }),
        ),
        Operation::Checksum => {
            let out = checksum::checksum_one_annotated(conn, envelope.target.clone());
            split_result(out)
        }
        Operation::Move => match envelope.arguments.path.as_deref() {
            Some(dest) => {
                let out = mv::mv_one_annotated(conn, envelope.target.clone(), dest);
                split_result(out)
            }
            None => (
                None,
                Some(BatonError {
                    code: -1,
                    message: "move via baton-do requires arguments.path (destination)"
                        .to_string(),
                }),
            ),
        },
        Operation::Remove => {
            let out = rm::rm_one_annotated(conn, envelope.target.clone());
            split_result(out)
        }
        Operation::Mkdir => {
            let opts = mkdir::MkdirOptions {
                recurse: envelope.arguments.recurse,
            };
            let out = mkdir::mkdir_one_annotated(conn, envelope.target.clone(), &opts);
            split_result(out)
        }
        Operation::Rmdir => {
            let opts = rmdir::RmdirOptions {
                recurse: envelope.arguments.recurse,
                force: envelope.arguments.force,
            };
            let out = rmdir::rmdir_one_annotated(conn, envelope.target.clone(), &opts);
            split_result(out)
        }
    }
}

/// Map baton-do envelope arguments onto [`list::ListOptions`].
fn list_options_from_arguments(args: &Arguments) -> list::ListOptions {
    list::ListOptions {
        size: args.size,
        checksum: args.checksum,
        avu: args.avu,
        acl: args.acl,
        replicate: args.replicate,
        timestamp: args.timestamp,
        contents: args.contents,
    }
}

/// Split a returned target into either [`OperationResult::Single`]
/// (success) or a propagated error (in-band annotated). Pulls the
/// `error` annotation off the target with `take()` so the wire
/// shape never double-emits — envelope-level `error` is the
/// authoritative location, target's own `error` is internal
/// signalling between the operations layer and the dispatcher.
fn split_result(mut target: Target) -> (Option<OperationResult>, Option<BatonError>) {
    let error = match &mut target {
        Target::DataObject(d) => d.error.take(),
        Target::Collection(c) => c.error.take(),
    };
    if let Some(err) = error {
        (None, Some(err))
    } else {
        (Some(OperationResult::Single(target)), None)
    }
}

/// Convert a baton-do envelope into a [`MetamodInput`].
///
/// Validates `arguments.operation` is one of the accepted strings.
/// Upstream baton-do uses `"rem"` (`baton/src/operations.c:281-291`);
/// baton-rs's existing `MetamodOperation` accepts `"rm"` —
/// honouring both keeps wire-compat with both the upstream
/// multiplexer and the dedicated `baton-metamod` binary.
fn metamod_input_from_envelope(
    envelope: &BatonDoEnvelope,
) -> Result<MetamodInput, BatonError> {
    let op_str = envelope
        .arguments
        .operation
        .as_deref()
        .ok_or_else(|| BatonError {
            code: -1,
            message: "metamod: arguments.operation is required (\"add\" or \"rem\")"
                .to_string(),
        })?;
    let operation = match op_str {
        "add" => MetamodOperation::Add,
        "rem" | "rm" => MetamodOperation::Rm,
        other => {
            return Err(BatonError {
                code: -1,
                message: format!(
                    "metamod: unknown operation {other:?}; expected \"add\" or \"rem\""
                ),
            });
        }
    };

    let (collection, data_object, avus) = match &envelope.target {
        Target::DataObject(d) => (
            d.collection.clone(),
            Some(d.data_object.clone()),
            d.avus.clone().unwrap_or_default(),
        ),
        Target::Collection(c) => (
            c.collection.clone(),
            None,
            c.avus.clone().unwrap_or_default(),
        ),
    };

    Ok(MetamodInput {
        collection,
        data_object,
        operation,
        avus,
        error: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{Avu, Collection, DataObject};

    fn empty_arguments() -> Arguments {
        Arguments::default()
    }

    fn sample_data_object_target() -> Target {
        Target::DataObject(DataObject {
            collection: "/zone/home/u".to_string(),
            data_object: "foo.txt".to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        })
    }

    fn sample_collection_target() -> Target {
        Target::Collection(Collection {
            collection: "/zone/home/u".to_string(),
            avus: None,
            access: None,
            timestamps: None,
            contents: None,
            error: None,
        })
    }

    fn sample_envelope(operation: Operation, target: Target, arguments: Arguments) -> BatonDoEnvelope {
        BatonDoEnvelope {
            operation,
            target,
            arguments,
        }
    }

    // --- list_options_from_arguments -----------------------------------------

    #[test]
    fn list_options_default_arguments_produce_default_options() {
        let opts = list_options_from_arguments(&empty_arguments());
        assert!(!opts.size);
        assert!(!opts.checksum);
        assert!(!opts.avu);
        assert!(!opts.acl);
        assert!(!opts.replicate);
        assert!(!opts.timestamp);
        assert!(!opts.contents);
    }

    #[test]
    fn list_options_propagate_each_flag() {
        let mut args = Arguments::default();
        args.size = true;
        args.checksum = true;
        args.avu = true;
        args.acl = true;
        args.replicate = true;
        args.timestamp = true;
        args.contents = true;
        let opts = list_options_from_arguments(&args);
        assert!(opts.size);
        assert!(opts.checksum);
        assert!(opts.avu);
        assert!(opts.acl);
        assert!(opts.replicate);
        assert!(opts.timestamp);
        assert!(opts.contents);
    }

    // --- split_result --------------------------------------------------------

    #[test]
    fn split_result_success_path_returns_single_with_target() {
        // No error annotation on the target → wrapped as
        // OperationResult::Single, no envelope-level error.
        let target = sample_data_object_target();
        let (result, error) = split_result(target);
        assert!(error.is_none());
        match result {
            Some(OperationResult::Single(_)) => {}
            other => panic!("expected Single, got {:?}", other),
        }
    }

    #[test]
    fn split_result_pulls_error_annotation_to_envelope_level() {
        // Error annotation on the target → no result, error
        // propagated. Pins that the wire shape doesn't
        // double-emit the error (target.error and
        // envelope.error in the same line).
        let mut target = sample_data_object_target();
        if let Target::DataObject(ref mut d) = target {
            d.error = Some(BatonError {
                code: -310000,
                message: "USER_FILE_DOES_NOT_EXIST".to_string(),
            });
        }
        let (result, error) = split_result(target);
        assert!(result.is_none());
        let err = error.expect("error pulled to envelope level");
        assert_eq!(err.code, -310000);
    }

    #[test]
    fn split_result_strips_error_from_target_when_present() {
        // Defensive: the returned-but-discarded target shouldn't
        // still carry the error annotation (it's been moved to
        // envelope-level). split_result uses .take() to pull
        // the error out, leaving target.error = None on the
        // way out — even though we discard the target on the
        // error path here, the take() pattern is what protects
        // future code paths that might surface the target after
        // an annotated error.
        let mut target = sample_data_object_target();
        if let Target::DataObject(ref mut d) = target {
            d.error = Some(BatonError {
                code: -1,
                message: "x".to_string(),
            });
        }
        // Move into split_result, get a Some(error) back; the
        // target is consumed but the take() inside guarantees
        // the error wasn't cloned-and-left.
        let (_, error) = split_result(target);
        assert!(error.is_some());
    }

    // --- metamod_input_from_envelope ----------------------------------------

    #[test]
    fn metamod_input_requires_arguments_operation() {
        let envelope = sample_envelope(
            Operation::Metamod,
            sample_data_object_target(),
            empty_arguments(),
        );
        let result = metamod_input_from_envelope(&envelope);
        let err = result.expect_err("missing arguments.operation should error");
        assert!(
            err.message.contains("arguments.operation is required"),
            "error message should be specific: {:?}",
            err
        );
    }

    #[test]
    fn metamod_input_accepts_add() {
        let mut args = empty_arguments();
        args.operation = Some("add".to_string());
        let envelope = sample_envelope(Operation::Metamod, sample_data_object_target(), args);
        let input = metamod_input_from_envelope(&envelope).expect("add should parse");
        assert_eq!(input.operation, MetamodOperation::Add);
    }

    #[test]
    fn metamod_input_accepts_rem_upstream_form() {
        // Upstream baton-do uses "rem"
        // (baton/src/operations.c:281-291) — must accept it for
        // partisan compat.
        let mut args = empty_arguments();
        args.operation = Some("rem".to_string());
        let envelope = sample_envelope(Operation::Metamod, sample_data_object_target(), args);
        let input = metamod_input_from_envelope(&envelope).expect("rem should parse");
        assert_eq!(input.operation, MetamodOperation::Rm);
    }

    #[test]
    fn metamod_input_accepts_rm_legacy_form() {
        // baton-rs's existing MetamodOperation enum serialises
        // as "rm"; honouring both forms keeps wire-compat with
        // the dedicated baton-metamod binary too.
        let mut args = empty_arguments();
        args.operation = Some("rm".to_string());
        let envelope = sample_envelope(Operation::Metamod, sample_data_object_target(), args);
        let input = metamod_input_from_envelope(&envelope).expect("rm should parse");
        assert_eq!(input.operation, MetamodOperation::Rm);
    }

    #[test]
    fn metamod_input_rejects_unknown_operation() {
        let mut args = empty_arguments();
        args.operation = Some("delete".to_string());
        let envelope = sample_envelope(Operation::Metamod, sample_data_object_target(), args);
        let result = metamod_input_from_envelope(&envelope);
        let err = result.expect_err("unknown op should error");
        assert!(
            err.message.contains("\"delete\""),
            "error message should name the offending value: {:?}",
            err
        );
    }

    #[test]
    fn metamod_input_extracts_avus_from_data_object_target() {
        let avus = vec![Avu {
            attribute: "k".to_string(),
            value: "v".to_string(),
            units: None,
        }];
        let target = Target::DataObject(DataObject {
            avus: Some(avus.clone()),
            ..match sample_data_object_target() {
                Target::DataObject(d) => d,
                _ => unreachable!(),
            }
        });
        let mut args = empty_arguments();
        args.operation = Some("add".to_string());
        let envelope = sample_envelope(Operation::Metamod, target, args);
        let input = metamod_input_from_envelope(&envelope).expect("parse");
        assert_eq!(input.avus, avus);
        assert_eq!(input.data_object.as_deref(), Some("foo.txt"));
    }

    #[test]
    fn metamod_input_extracts_avus_from_collection_target() {
        let avus = vec![Avu {
            attribute: "k".to_string(),
            value: "v".to_string(),
            units: None,
        }];
        let target = Target::Collection(Collection {
            avus: Some(avus.clone()),
            ..match sample_collection_target() {
                Target::Collection(c) => c,
                _ => unreachable!(),
            }
        });
        let mut args = empty_arguments();
        args.operation = Some("add".to_string());
        let envelope = sample_envelope(Operation::Metamod, target, args);
        let input = metamod_input_from_envelope(&envelope).expect("parse");
        assert_eq!(input.avus, avus);
        assert_eq!(input.data_object, None);
    }

    // --- dispatch_one (operation-level smoke tests, no iRODS) -----------------

    #[test]
    fn dispatch_metaquery_returns_not_implemented_error() {
        // Pin the deferred-metaquery placeholder until commit 3
        // of 7b lands the real fix. CI on this branch should NOT
        // pass with metaquery returning Ok.
        //
        // We can construct this test without an iRODS connection
        // because the metaquery arm errors out before any
        // network call — but dispatch_one's signature wants a
        // &mut RodsConnection. We side-step by validating via
        // the envelope construction shape, not via dispatch
        // directly (which would need a real conn).
        //
        // Confirm the message shape via dispatch_inner-like
        // logic by checking the placeholder error string is
        // what the dispatcher returns. Direct call test will
        // come with the integration tests.
        //
        // For this commit, the unit-test confidence is in:
        //   - the helper functions above (operation parsing,
        //     options mapping, error extraction)
        //   - integration tests in tests/baton_do_dispatch.rs
        //     prove end-to-end routing on a live connection.
        //
        // This test exists as a placeholder to remind readers
        // that the deferred case is intentional. No assertion
        // beyond "the codepath compiles".
        let _ = sample_envelope(
            Operation::Metaquery,
            sample_data_object_target(),
            empty_arguments(),
        );
    }
}
