// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-05

//! `baton-do checksum` logic: read or compute the iRODS-side
//! digest for an existing data object and populate the output
//! target's `checksum` field.
//!
//! Distinct from `baton-put --checksum`: that one computes a
//! digest as part of the put operation. This one operates on a
//! data object that already exists in the catalog. Both go
//! through `rcDataObjChksum` (wrapped in
//! [`crate::connection::RodsConnection::checksum_data_object`]
//! since Session 5b); without `FORCE_CHKSUM_KW`, iRODS returns the
//! stored digest if present and computes one if not. Matches
//! upstream baton's `JSON_CHECKSUM_OP` dispatcher entry.
//!
//! Collection targets are an error — `rcDataObjChksum` only works
//! on data objects. Mirrors upstream baton's behaviour.

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::types::Target;

/// Read or compute the server-side checksum for `target` and
/// return the input with `checksum` populated. Echoes any
/// pre-existing fields on the input unchanged.
///
/// The returned digest format depends on the server's hash
/// scheme. With the MD5 client default pinned for issue #25 the
/// result is 32 hex characters; SHA2 servers return a `sha2:`
/// prefix followed by base64. Pluggable scheme support is tracked
/// in #31; the matrix coverage in #27.
pub fn checksum_one(
    conn: &mut RodsConnection,
    target: Target,
) -> Result<Target, BatonError> {
    let path = target.path();
    let mut data_obj = match target {
        Target::DataObject(d) => d,
        Target::Collection(c) => {
            return Err(BatonError {
                code: -1,
                message: format!(
                    "baton-do checksum: target is a collection, not a data object: {}",
                    c.collection
                ),
            });
        }
    };
    let digest = conn.checksum_data_object(&path)?;
    data_obj.checksum = Some(digest);
    Ok(Target::DataObject(data_obj))
}

/// Same as [`checksum_one`], but catches iRODS errors and emits
/// the input annotated with an `"error"` field instead of
/// propagating. Mirrors `list_one_annotated` /
/// `metamod_one_annotated` / `get_one_annotated` /
/// `put_one_annotated` / `chmod_one_annotated` so the binary's
/// NDJSON loop stays uniform.
pub fn checksum_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
) -> Target {
    let fallback = target.clone();
    match checksum_one(conn, target) {
        Ok(t) => t,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}
