// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-12

//! `baton-do checksum` logic: read or compute the iRODS-side
//! digest for an existing data object and populate the output
//! target's `checksum` field.
//!
//! Distinct from `baton-put --checksum`: that one computes a
//! digest as part of the put operation. This one operates on a
//! data object that already exists in the catalog. Both go
//! through `rcDataObjChksum` (wrapped in
//! [`crate::connection::RodsConnection::checksum_data_object`]
//! since Session 5b). Wire-arg behaviour mirrors upstream
//! baton's CALCULATE / VERIFY / FORCE flag triple
//! (`baton/src/read.c:610-625`):
//!
//! - `calculate` (= `arguments.checksum`) → `CHKSUM_ALL_KW`
//!   (compute on all replicates).
//! - `verify` → `VERIFY_CHKSUM_KW` (re-verify recorded digest).
//! - `force` → `FORCE_CHKSUM_KW`, only meaningful with `calculate`.
//! - `calculate` + `verify` together is rejected with
//!   USER_INPUT_OPTION_ERR (matches upstream).
//!
//! Default when no flag is set: upstream falls back to
//! CALCULATE; baton-rs's dispatcher applies the same default
//! before calling `checksum_one`.
//!
//! VERIFY semantics: iRODS' `rcDataObjChksum` in VERIFY mode
//! signals match (success) vs mismatch (`CHECK_VERIFICATION_RESULTS`,
//! -407000) and doesn't always populate its out-parameter digest.
//! `checksum_one` therefore follows a successful verify with a
//! no-flags catalog read so the returned `checksum` field is
//! always a non-empty string — partisan's
//! `obj.checksum(verify_checksum=True)` asserts truthiness on the
//! returned value (`partisan/tests/test_irods.py::test_verify_checksum_good`,
//! #57 Cluster E).
//!
//! Collection targets are an error — `rcDataObjChksum` only works
//! on data objects. Mirrors upstream baton's behaviour.

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::ffi;
use crate::types::Target;

/// Per-call options for the checksum operation. Each field maps
/// to a `SHIM_CHKSUM_*` flag bit; the C shim enforces the
/// mutual-exclusion rule between `calculate` and `verify`, and the
/// dispatcher above this layer rejects the combination with a
/// clearer error.
///
/// `Default` is all-false — the post-put-checksum call site in
/// `operations::put` uses it to preserve the keyword-less
/// behaviour. The dispatcher path always sets at least one of
/// `calculate` or `verify` before constructing this.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct ChecksumOptions {
    pub calculate: bool,
    pub verify: bool,
    pub force: bool,
}

impl ChecksumOptions {
    /// Pack to the `SHIM_CHKSUM_*` bitfield expected by the FFI
    /// shim. Layered packing (rather than passing three booleans)
    /// keeps the FFI surface narrow.
    pub fn to_flags(self) -> std::os::raw::c_int {
        let mut flags = 0;
        if self.calculate {
            flags |= ffi::SHIM_CHKSUM_CALCULATE;
        }
        if self.verify {
            flags |= ffi::SHIM_CHKSUM_VERIFY;
        }
        if self.force {
            flags |= ffi::SHIM_CHKSUM_FORCE;
        }
        flags
    }
}

/// Read or compute the server-side checksum for `target` and
/// return the input with `checksum` populated. Echoes any
/// pre-existing fields on the input unchanged.
///
/// The returned digest format depends on the server's hash
/// scheme. With the MD5 client default pinned for issue #25 the
/// result is 32 hex characters; SHA2 servers return a `sha2:`
/// prefix followed by base64. Pluggable scheme support is tracked
/// in #31; the matrix coverage in #27.
pub fn checksum_one(
    conn: &mut RodsConnection,
    target: Target,
    opts: &ChecksumOptions,
) -> Result<Target, BatonError> {
    if opts.calculate && opts.verify {
        // -403000 USER_INPUT_OPTION_ERR. Same code upstream
        // baton emits at `baton/src/read.c:603-607` for this
        // exact mutual-exclusion failure.
        return Err(BatonError::from_irods_with_context(
            -403000,
            &format!(
                "baton-do checksum: cannot both verify and calculate the checksum of '{}'",
                target.path()
            ),
        ));
    }
    let path = target.path();
    let mut data_obj = match target {
        Target::DataObject(d) => d,
        Target::Collection(c) => {
            // -310000 USER_FILE_DOES_NOT_EXIST. Wire-shape align
            // with upstream baton; see audit on PR #80's thread.
            return Err(BatonError::from_irods_with_context(
                -310000,
                &format!(
                    "baton-do checksum: target is a collection, not a data object: {}",
                    c.collection
                ),
            ));
        }
    };
    let digest = conn.checksum_data_object(&path, opts.to_flags())?;
    // iRODS' `rcDataObjChksum` in VERIFY mode only signals
    // match-or-mismatch — it doesn't always populate the digest
    // buffer. The shim returns success with an empty buffer in that
    // case (see #57 Cluster E). Fetch the catalog digest with a
    // follow-up no-flags call so partisan-style callers always get
    // a non-empty string back from a successful verify (their
    // `obj.checksum(verify_checksum=True)` returns whatever's in
    // the `checksum` field and asserts truthiness).
    let digest = if opts.verify && digest.is_empty() {
        conn.checksum_data_object(&path, 0)?
    } else {
        digest
    };
    data_obj.checksum = Some(digest);
    Ok(Target::DataObject(data_obj))
}

/// Same as [`checksum_one`], but catches iRODS errors and emits
/// the input annotated with an `"error"` field instead of
/// propagating. Mirrors `list_one_annotated` /
/// `metamod_one_annotated` / `get_one_annotated` /
/// `put_one_annotated` / `chmod_one_annotated` so the binary's
/// NDJSON loop stays uniform.
pub fn checksum_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
    opts: &ChecksumOptions,
) -> Target {
    super::annotate_failure(target, |t| checksum_one(conn, t, opts))
}
