// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-01
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01

//! `baton-chmod` logic: apply an ACL grant or revoke list to an
//! iRODS data object or collection.
//!
//! Each input record carries an `access[]` array in the existing
//! `DataObject.access` / `Collection.access` field — the same shape
//! `baton-list --acl` emits on output, mirroring upstream baton.
//! `chmod_one` iterates the array and dispatches one
//! `rcModAccessControl` round-trip per entry via
//! [`crate::connection::RodsConnection::mod_access_control`].
//!
//! Per upstream baton (`baton/src/operations.c:416-421`),
//! iteration **breaks on the first failure**: subsequent entries
//! in the same record are skipped, the input record is annotated
//! with the failing entry's error, and the NDJSON stream
//! continues to the next record. The accumulate-instead-of-break
//! alternative is tracked in #34 for a future session.
//!
//! `--recurse` only takes effect on collection targets; iRODS
//! performs the traversal server-side via `recursiveFlag`. Data
//! object targets ignore the flag (they have no children).

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::types::{Acl, Target};

/// Caller-controlled flags for [`chmod_one`].
#[derive(Debug, Default, Clone, Copy)]
pub struct ChmodOptions {
    /// Apply the ACL change to every child of the target collection
    /// in addition to the collection itself. Ignored for data
    /// object targets — they have no children.
    pub recursive: bool,
}

/// Apply each ACL entry on `target.access[]` to the target via
/// `rcModAccessControl`. Empty or absent `access` is a no-op
/// success.
///
/// Echoes the input target unchanged on success. On the first
/// failed entry, returns the iRODS error verbatim — the caller can
/// either propagate (fail-fast) or wrap via [`chmod_one_annotated`]
/// for in-band per-input annotation.
pub fn chmod_one(
    conn: &mut RodsConnection,
    target: Target,
    opts: &ChmodOptions,
) -> Result<Target, BatonError> {
    let target_is_collection = matches!(target, Target::Collection(_));
    // Clone the access list so the per-entry calls below can
    // re-borrow `target` without fighting the borrow checker over
    // a shared immutable slice. ACL lists are small in practice
    // (a handful of entries per record); the clone is cheap.
    let access: Option<Vec<Acl>> = match &target {
        Target::DataObject(d) => d.access.clone(),
        Target::Collection(c) => c.access.clone(),
    };

    if let Some(acls) = access {
        for acl in &acls {
            // recursive only takes effect on collections — iRODS
            // ignores the flag on data-object inputs but we mask
            // it client-side so the wire log stays clean.
            let recursive = opts.recursive && target_is_collection;
            conn.mod_access_control(&target, acl, recursive)?;
        }
    }

    Ok(target)
}

/// Same as [`chmod_one`], but catches iRODS errors and emits the
/// input annotated with an `"error"` field instead of propagating.
/// Mirrors `list_one_annotated` / `metamod_one_annotated` /
/// `get_one_annotated` / `put_one_annotated` so the binary's
/// NDJSON loop stays uniform.
pub fn chmod_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
    opts: &ChmodOptions,
) -> Target {
    let fallback = target.clone();
    match chmod_one(conn, target, opts) {
        Ok(t) => t,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}
