// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-29
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-29

//! `baton-get` logic: read a data object's bytes back to the caller.
//!
//! Inline mode (default) base64-encodes the bytes and emits them on
//! the output JSON's `data` field. `--save` file mode (5b) streams
//! bytes directly to disk under the per-record `directory` and skips
//! the inline `data` field — matches upstream baton's per-record
//! save-destination convention.

use std::fs::File;
use std::io::Write;
use std::path::PathBuf;

use base64::engine::general_purpose;
use base64::Engine;

use crate::connection::{OpenMode, RodsConnection};
use crate::error::BatonError;
use crate::types::Target;

/// Caller-controlled flags for [`get_one`].
#[derive(Debug, Default, Clone, Copy)]
pub struct GetOptions {
    /// `--save` file mode. When `true`, [`get_one`] streams bytes from
    /// iRODS to a local file under each input record's `directory`
    /// field and leaves the `data` field unset on the output. When
    /// `false`, the inline base64 path is used.
    pub save: bool,
}

// 64 KiB is a moderate compromise: small enough that the per-call
// memory cost is negligible for tiny files, large enough that the
// rcDataObjRead overhead doesn't dominate for objects that span
// multiple chunks. Same chunk size for inline and save paths so
// behaviour stays uniform; the save path additionally avoids the
// O(file size) memory cost of accumulating into a single Vec.
const READ_CHUNK_SIZE: usize = 64 * 1024;

/// Read a single data object end-to-end.
///
/// Inline mode (`opts.save == false`): bytes accumulated in memory,
/// base64-encoded, returned on the output `data` field.
///
/// Save mode (`opts.save == true`): bytes streamed to
/// `<input.directory>/<input.data_object>` on disk; `data` left
/// unset on the output. The input record's `directory` field is
/// required in this mode and is echoed unchanged on the output.
///
/// Collections are an error: there's nothing to download for a
/// collection in baton's data model. Upstream baton-get returns an
/// equivalent error, so we mirror that.
pub fn get_one(
    conn: &mut RodsConnection,
    target: Target,
    opts: &GetOptions,
) -> Result<Target, BatonError> {
    let path = target.path();
    let mut data_obj = match target {
        Target::DataObject(d) => d,
        Target::Collection(c) => {
            return Err(BatonError {
                code: -1,
                message: format!(
                    "baton-get: target is a collection, not a data object: {}",
                    c.collection
                ),
            });
        }
    };

    if opts.save {
        // The local destination is <directory>/<data_object>. iRODS
        // never sees this path; the directory must exist on the local
        // host before the call (baton itself doesn't auto-create).
        let directory = data_obj.directory.as_deref().ok_or(BatonError {
            code: -1,
            message: "baton-get --save requires a `directory` field on each input record"
                .to_string(),
        })?;
        let mut local_path = PathBuf::from(directory);
        local_path.push(&data_obj.data_object);

        let mut file = File::create(&local_path).map_err(|e| BatonError {
            code: -1,
            message: format!("could not create local file {}: {}", local_path.display(), e),
        })?;

        let handle = conn.open_data_object(&path, OpenMode::Read)?;
        let result = stream_to_writer(conn, handle, &mut file);
        let _ = conn.close_data_object(handle);
        result?;

        // Ensure bytes hit the OS before we declare success. Without
        // this, a concurrent reader (e.g. a downstream pipeline) could
        // see a short file when --save returns.
        file.sync_all().map_err(|e| BatonError {
            code: -1,
            message: format!("flushing local file {}: {}", local_path.display(), e),
        })?;
    } else {
        let handle = conn.open_data_object(&path, OpenMode::Read)?;
        let read_result = read_to_end(conn, handle);
        // Best-effort close on both success and failure paths. A close
        // failure on the success path is logged-but-ignored: the bytes
        // are already in hand and there's nothing useful for the
        // caller to do with a stale L1 descriptor.
        let _ = conn.close_data_object(handle);
        let bytes = read_result?;
        data_obj.data = Some(general_purpose::STANDARD.encode(&bytes));
    }

    Ok(Target::DataObject(data_obj))
}

/// Same as [`get_one`], but catches iRODS errors and emits the input
/// annotated with an `"error"` field instead of propagating. Mirrors
/// `list_one_annotated` and `metamod_one_annotated` so binaries can
/// keep their NDJSON loops uniform.
pub fn get_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
    opts: &GetOptions,
) -> Target {
    let fallback = target.clone();
    match get_one(conn, target, opts) {
        Ok(t) => t,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}

fn read_to_end(conn: &mut RodsConnection, handle: i32) -> Result<Vec<u8>, BatonError> {
    let mut buf = vec![0u8; READ_CHUNK_SIZE];
    let mut content = Vec::new();
    loop {
        let n = conn.read_data_object(handle, &mut buf)?;
        if n == 0 {
            break;
        }
        content.extend_from_slice(&buf[..n]);
    }
    Ok(content)
}

/// Stream the data object behind `handle` into `out`, chunk by chunk.
/// Used by the `--save` path to avoid accumulating the entire object
/// in memory before writing.
fn stream_to_writer<W: Write>(
    conn: &mut RodsConnection,
    handle: i32,
    out: &mut W,
) -> Result<(), BatonError> {
    let mut buf = vec![0u8; READ_CHUNK_SIZE];
    loop {
        let n = conn.read_data_object(handle, &mut buf)?;
        if n == 0 {
            break;
        }
        out.write_all(&buf[..n]).map_err(|e| BatonError {
            code: -1,
            message: format!("writing local file: {}", e),
        })?;
    }
    Ok(())
}
