// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! `baton-list` logic: stat a target and optionally enrich the output with
//! metadata requested by the caller's flags.
//!
//! Session 3a handles the path-only case (stat only) plus `--size` and
//! `--checksum`. Metadata flags (`--avu`, `--acl`, `--replicate`,
//! `--timestamp`) and `--contents` arrive in Sessions 3b / 3c respectively.

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::types::Target;

/// Which optional fields the caller wants populated in the output.
#[derive(Debug, Default, Clone, Copy)]
pub struct ListOptions {
    pub size: bool,
    pub checksum: bool,
    pub avu: bool,
    pub acl: bool,
    pub replicate: bool,
    pub timestamp: bool,
    pub contents: bool,
}

/// Process a single listing input.
///
/// Calls [`RodsConnection::stat`] to confirm the path exists and to pull
/// back the fields that [`ListOptions::size`] / [`ListOptions::checksum`]
/// need. `--size` and `--checksum` only apply to data objects; collections
/// have no such fields in the baton JSON schema and flags are silently
/// ignored for them (matching baton's own behaviour).
///
/// A recorded iRODS checksum of empty string (which is what servers return
/// for data objects that have never been checksummed, and for collections)
/// is treated the same as "no checksum" — we only set the field when a
/// real value is present.
pub fn list_one(
    conn: &mut RodsConnection,
    mut target: Target,
    opts: &ListOptions,
) -> Result<Target, BatonError> {
    let path = target.path();
    let stat = conn.stat(&path)?;

    if let Target::DataObject(d) = &mut target {
        if opts.size {
            d.size = Some(stat.size);
        }
        if opts.checksum && !stat.checksum.is_empty() {
            d.checksum = Some(stat.checksum);
        }
    }

    Ok(target)
}
