// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01

//! `baton-list` logic: stat a target and optionally enrich the output with
//! metadata requested by the caller's flags.
//!
//! Per-flag fetchers (`fetch_avus`, `fetch_acl`, …) are crate-internal
//! helpers shared with `baton-metaquery` (Session 4c) via
//! [`enrich_with_metadata`].

use crate::connection::{GenQuery, RodsConnection};
use crate::error::BatonError;
use crate::ffi;
use crate::types::{Acl, AclLevel, Avu, Collection, DataObject, Item, Replicate, Target, Timestamp};

/// Which optional fields the caller wants populated in the output.
#[derive(Debug, Default, Clone, Copy)]
pub struct ListOptions {
    pub size: bool,
    pub checksum: bool,
    pub avu: bool,
    pub acl: bool,
    pub replicate: bool,
    pub timestamp: bool,
    pub contents: bool,
}

impl ListOptions {
    /// Slice out the metadata-flag subset that [`enrich_with_metadata`]
    /// consumes — i.e. the flags shared between `baton-list` and
    /// `baton-metaquery`. Excludes `size` / `checksum` (caller-controlled
    /// stat) and `contents` (collection-listing-specific).
    pub fn enrich_options(&self) -> EnrichOptions {
        EnrichOptions {
            avu: self.avu,
            acl: self.acl,
            replicate: self.replicate,
            timestamp: self.timestamp,
        }
    }
}

/// Subset of [`ListOptions`] covering the metadata flags that produce one
/// extra catalog query per flag and apply to both data objects and
/// collections (with the per-flag rules around when a field gets set).
///
/// Used by [`enrich_with_metadata`] so `baton-metaquery` (Session 4c)
/// can decorate its result rows with the same per-flag behaviour
/// `baton-list` exposes, without duplicating the dispatch logic.
#[derive(Debug, Default, Clone, Copy)]
pub struct EnrichOptions {
    pub avu: bool,
    pub acl: bool,
    pub replicate: bool,
    pub timestamp: bool,
}

/// Apply the metadata enrichment flags to `target` in place.
///
/// One catalog round-trip per requested flag. `--replicate` is silently
/// a no-op on collections (data-object-only concept); the other three
/// apply to both kinds. Public because `baton-metaquery` (a separate
/// binary crate) calls it directly to decorate query results with the
/// same per-flag behaviour `baton-list` exposes.
pub fn enrich_with_metadata(
    conn: &mut RodsConnection,
    target: &mut Target,
    opts: &EnrichOptions,
) -> Result<(), BatonError> {
    if opts.avu {
        let avus = fetch_avus(conn, target)?;
        match target {
            Target::DataObject(d) => d.avus = Some(avus),
            Target::Collection(c) => c.avus = Some(avus),
        }
    }

    if opts.acl {
        let acls = fetch_acl(conn, target)?;
        match target {
            Target::DataObject(d) => d.access = Some(acls),
            Target::Collection(c) => c.access = Some(acls),
        }
    }

    // Replicates are a data-object concept; baton silently ignores
    // --replicate on collections, and we follow suit.
    if opts.replicate {
        if let Target::DataObject(d) = target {
            d.replicates = Some(fetch_replicates(conn, d)?);
        }
    }

    if opts.timestamp {
        let timestamps = fetch_timestamps(conn, target)?;
        match target {
            Target::DataObject(d) => d.timestamps = Some(timestamps),
            Target::Collection(c) => c.timestamps = Some(timestamps),
        }
    }

    Ok(())
}

/// Process a single listing input.
///
/// Calls [`RodsConnection::stat`] to confirm the path exists and to pull
/// back the fields that [`ListOptions::size`] / [`ListOptions::checksum`]
/// need. `--size` and `--checksum` only apply to data objects; collections
/// have no such fields in the baton JSON schema and flags are silently
/// ignored for them (matching baton's own behaviour).
///
/// A recorded iRODS checksum of empty string (which is what servers return
/// for data objects that have never been checksummed, and for collections)
/// is treated the same as "no checksum" — we only set the field when a
/// real value is present.
pub fn list_one(
    conn: &mut RodsConnection,
    mut target: Target,
    opts: &ListOptions,
) -> Result<Target, BatonError> {
    let path = target.path();
    let stat = conn.stat(&path)?;

    if let Target::DataObject(d) = &mut target {
        if opts.size || opts.checksum {
            // Pull size and checksum from the canonical replica
            // (highest-numbered with DATA_REPL_STATUS = 1) rather
            // than rcObjStat. Mid-replication state can leave
            // replicas disagreeing on size; reporting the latest
            // good replica's values matches upstream baton and
            // gives the caller a self-consistent (size, checksum)
            // pair.
            //
            // Fall back to stat when the catalog has no valid
            // replicas — defensive for transient states where the
            // path exists per stat but every replica is mid-write.
            // Cost: one extra catalog round-trip per data object on
            // --size or --checksum. The optimisation (skip stat
            // when we're going to query the catalog anyway) can
            // land in Session 8 polish.
            let canonical = fetch_canonical_replica_state(conn, d)?;
            let (size_v, checksum_v) = match canonical.as_ref() {
                Some(state) => (state.size, state.checksum.as_str()),
                None => (stat.size, stat.checksum.as_str()),
            };
            if opts.size {
                d.size = Some(size_v);
            }
            if opts.checksum && !checksum_v.is_empty() {
                d.checksum = Some(checksum_v.to_string());
            }
        }
    }

    enrich_with_metadata(conn, &mut target, &opts.enrich_options())?;

    // Contents apply only to collections; baton silently ignores --contents
    // on data-object inputs and we follow suit.
    if opts.contents {
        if let Target::Collection(c) = &target {
            let contents = fetch_contents(conn, &c.collection)?;
            if let Target::Collection(c) = &mut target {
                c.contents = Some(contents);
            }
        }
    }

    Ok(target)
}

// --- catalog query helpers ----------------------------------------------------
//
// `sql_escape` is shared with `crate::operations::metaquery`, hence
// pub(crate). The query builder itself ([`GenQuery`]) lives in
// `crate::connection` so its lifecycle stays next to `RodsConnection`.

/// Escape single quotes for inclusion in a genQuery WHERE-clause literal.
///
/// Paths and metadata values can legitimately contain `'`; the iRODS
/// query parser accepts the SQL-style `''` doubled form. Upstream baton
/// uses the same approach, and iRODS's genQuery has no parameterised-
/// query equivalent of SQL prepared statements, so this is the
/// available defence against catalog-query injection from caller-
/// supplied collection / data-object / AVU strings.
///
/// Other special characters (backslash, NUL, wildcards) are not escaped:
/// `CString::new` already rejects interior NULs at the FFI boundary,
/// and iRODS's parser is not documented to give backslash any special
/// meaning inside literals. If a future iRODS release changes that, the
/// catalog would refuse the query rather than silently mis-route it —
/// the caller still gets an error rather than wrong data.
pub(crate) fn sql_escape(s: &str) -> String {
    s.replace('\'', "''")
}

// --- per-flag fetchers --------------------------------------------------------

/// Fetch the AVUs attached to a target.
///
/// Data objects use the `META_DATA_*` columns and need both
/// `COLL_NAME` and `DATA_NAME` in the WHERE clause; collections use the
/// `META_COLL_*` columns and only need `COLL_NAME`.
fn fetch_avus(conn: &mut RodsConnection, target: &Target) -> Result<Vec<Avu>, BatonError> {
    let mut q = GenQuery::new();

    let (col_attr, col_value, col_units) = match target {
        Target::DataObject(_) => (
            ffi::SHIM_COL_META_DATA_ATTR_NAME,
            ffi::SHIM_COL_META_DATA_ATTR_VALUE,
            ffi::SHIM_COL_META_DATA_ATTR_UNITS,
        ),
        Target::Collection(_) => (
            ffi::SHIM_COL_META_COLL_ATTR_NAME,
            ffi::SHIM_COL_META_COLL_ATTR_VALUE,
            ffi::SHIM_COL_META_COLL_ATTR_UNITS,
        ),
    };
    q.add_select(col_attr);
    q.add_select(col_value);
    q.add_select(col_units);

    match target {
        Target::DataObject(d) => {
            q.add_where(
                ffi::SHIM_COL_COLL_NAME,
                &format!("= '{}'", sql_escape(&d.collection)),
            )?;
            q.add_where(
                ffi::SHIM_COL_DATA_NAME,
                &format!("= '{}'", sql_escape(&d.data_object)),
            )?;
        }
        Target::Collection(c) => {
            q.add_where(
                ffi::SHIM_COL_COLL_NAME,
                &format!("= '{}'", sql_escape(&c.collection)),
            )?;
        }
    }

    let rows = conn.query(&mut q)?;

    Ok(rows
        .into_iter()
        .map(|row| {
            // Defensive .get/.cloned: rcGenQuery should always populate every
            // selected column, but treating a missing column as empty string
            // keeps the helper from panicking on an unexpectedly truncated
            // row.
            let attribute = row.first().cloned().unwrap_or_default();
            let value = row.get(1).cloned().unwrap_or_default();
            let units_raw = row.get(2).cloned().unwrap_or_default();
            // iRODS returns an empty string for unitless AVUs; fold that
            // back to None so the JSON output omits the `units` key
            // (matches baton's behaviour).
            let units = if units_raw.is_empty() {
                None
            } else {
                Some(units_raw)
            };
            Avu {
                attribute,
                value,
                units,
            }
        })
        .collect())
}

/// Fetch the ACL entries attached to a target.
///
/// Collection ACLs need the *collection-specific* user-name and zone
/// columns (`COL_COLL_USER_NAME` / `COL_COLL_USER_ZONE`) — the generic
/// `COL_USER_NAME` / `COL_USER_ZONE` columns join via the data-access
/// path, so on a collection input they yield zero rows. baton's own
/// source uses the same split.
fn fetch_acl(conn: &mut RodsConnection, target: &Target) -> Result<Vec<Acl>, BatonError> {
    let mut q = GenQuery::new();

    let (col_user_name, col_user_zone, col_access_name) = match target {
        Target::DataObject(_) => (
            ffi::SHIM_COL_USER_NAME,
            ffi::SHIM_COL_USER_ZONE,
            ffi::SHIM_COL_DATA_ACCESS_NAME,
        ),
        Target::Collection(_) => (
            ffi::SHIM_COL_COLL_USER_NAME,
            ffi::SHIM_COL_COLL_USER_ZONE,
            ffi::SHIM_COL_COLL_ACCESS_NAME,
        ),
    };
    q.add_select(col_user_name);
    q.add_select(col_user_zone);
    q.add_select(col_access_name);

    match target {
        Target::DataObject(d) => {
            q.add_where(
                ffi::SHIM_COL_COLL_NAME,
                &format!("= '{}'", sql_escape(&d.collection)),
            )?;
            q.add_where(
                ffi::SHIM_COL_DATA_NAME,
                &format!("= '{}'", sql_escape(&d.data_object)),
            )?;
        }
        Target::Collection(c) => {
            q.add_where(
                ffi::SHIM_COL_COLL_NAME,
                &format!("= '{}'", sql_escape(&c.collection)),
            )?;
        }
    }

    let rows = conn.query(&mut q)?;

    rows.into_iter()
        .map(|row| {
            let owner = row.first().cloned().unwrap_or_default();
            let zone_raw = row.get(1).cloned().unwrap_or_default();
            let level_str = row.get(2).cloned().unwrap_or_default();
            let level = parse_acl_level(&level_str)?;
            // baton's schema treats `zone` as optional; fold an empty
            // server-side zone string to None so the JSON omits it.
            let zone = if zone_raw.is_empty() {
                None
            } else {
                Some(zone_raw)
            };
            Ok(Acl { owner, level, zone })
        })
        .collect()
}

/// Map iRODS's catalog access-level string into our typed enum. iRODS
/// uses the verbose forms `read object` / `modify object`; baton (and
/// our JSON schema) prefer the compact `read` / `write`. Both forms are
/// accepted here so behaviour is stable across iRODS server versions
/// that have shipped slightly different strings.
//
// (Definition lives further down with the other crate-private parsers.)

/// Size and checksum of a data object's canonical replica.
///
/// "Canonical" = the highest-numbered replica with
/// `DATA_REPL_STATUS = 1` (a "good" replica). Reporting that one's
/// size and checksum matches upstream baton and gives callers a
/// self-consistent pair even when iRODS is mid-replication and
/// replicas disagree on size.
#[derive(Debug, Clone, PartialEq, Eq)]
struct CanonicalReplicaState {
    size: u64,
    checksum: String,
}

/// Run a catalog query for the data object's per-replica
/// `(repl_num, size, checksum, status)` rows and return the
/// canonical replica's state. `Ok(None)` if no row has
/// `DATA_REPL_STATUS = 1` — the caller should fall back to
/// `rcObjStat` in that case.
fn fetch_canonical_replica_state(
    conn: &mut RodsConnection,
    d: &DataObject,
) -> Result<Option<CanonicalReplicaState>, BatonError> {
    let mut q = GenQuery::new();
    q.add_select(ffi::SHIM_COL_DATA_REPL_NUM);
    q.add_select(ffi::SHIM_COL_DATA_SIZE);
    q.add_select(ffi::SHIM_COL_D_DATA_CHECKSUM);
    q.add_select(ffi::SHIM_COL_D_REPL_STATUS);
    q.add_where(
        ffi::SHIM_COL_COLL_NAME,
        &format!("= '{}'", sql_escape(&d.collection)),
    )?;
    q.add_where(
        ffi::SHIM_COL_DATA_NAME,
        &format!("= '{}'", sql_escape(&d.data_object)),
    )?;
    let rows = conn.query(&mut q)?;
    Ok(pick_canonical_replica(&rows))
}

/// Pure selection logic: from rows of
/// `[repl_num, size, checksum, status]`, pick the highest-numbered
/// row with `status == "1"` and surface its size + checksum.
///
/// Rows with non-numeric `repl_num` or `size`, or with statuses
/// other than `"1"`, are skipped silently — same defensive shape as
/// other catalog parsers in this module. Extracted so the selection
/// rule can be unit-tested with synthetic input, without driving a
/// real iRODS connection.
fn pick_canonical_replica(rows: &[Vec<String>]) -> Option<CanonicalReplicaState> {
    rows.iter()
        .filter_map(|row| {
            let num: u32 = row.first()?.parse().ok()?;
            let size: u64 = row.get(1)?.parse().ok()?;
            let checksum = row.get(2)?.clone();
            let status = row.get(3)?;
            if status == "1" {
                Some((num, size, checksum))
            } else {
                None
            }
        })
        .max_by_key(|(num, _, _)| *num)
        .map(|(_, size, checksum)| CanonicalReplicaState { size, checksum })
}

/// Fetch the replicas of a data object. Each row from the catalog becomes
/// one [`Replicate`].
///
/// `valid` is derived from `COL_D_REPL_STATUS`: iRODS uses `1` for a good
/// replica and `0` (or `4` mid-write, etc.) for not-good. We collapse
/// anything other than literal `"1"` to `false` — matches baton's
/// behaviour and keeps callers from having to know iRODS's status codes.
fn fetch_replicates(
    conn: &mut RodsConnection,
    d: &DataObject,
) -> Result<Vec<Replicate>, BatonError> {
    let mut q = GenQuery::new();

    // Naming inconsistency note: iRODS 4.3.5's bindings expose this set
    // as a mix of long-form (COL_DATA_REPL_NUM) and short-form
    // (COL_D_DATA_CHECKSUM / COL_D_RESC_NAME / COL_D_REPL_STATUS) — not a
    // typo, that's actually how the headers are. Compiler "similar name"
    // hints were the source of truth.
    q.add_select(ffi::SHIM_COL_DATA_REPL_NUM);
    q.add_select(ffi::SHIM_COL_D_DATA_CHECKSUM);
    q.add_select(ffi::SHIM_COL_R_LOC);
    q.add_select(ffi::SHIM_COL_D_RESC_NAME);
    q.add_select(ffi::SHIM_COL_D_REPL_STATUS);

    q.add_where(
        ffi::SHIM_COL_COLL_NAME,
        &format!("= '{}'", sql_escape(&d.collection)),
    )?;
    q.add_where(
        ffi::SHIM_COL_DATA_NAME,
        &format!("= '{}'", sql_escape(&d.data_object)),
    )?;

    let rows = conn.query(&mut q)?;

    rows.into_iter()
        .map(|row| {
            let number_str = row.first().cloned().unwrap_or_default();
            let checksum = row.get(1).cloned().unwrap_or_default();
            let location = row.get(2).cloned().unwrap_or_default();
            let resource = row.get(3).cloned().unwrap_or_default();
            let status = row.get(4).cloned().unwrap_or_default();

            let number: u32 = number_str.parse().map_err(|_| BatonError {
                code: -1,
                message: format!("non-numeric replica number: {:?}", number_str),
            })?;

            Ok(Replicate {
                checksum,
                location,
                resource,
                number,
                valid: status == "1",
            })
        })
        .collect()
}

/// Fetch the create/modify timestamps for a target.
///
/// Each catalog row carries both timestamps for the same scope (per-replica
/// for a data object, single per-collection). We fan out to two
/// [`Timestamp`] entries per row — one with `created`, one with `modified`
/// — so the JSON output matches baton's per-event shape.
fn fetch_timestamps(
    conn: &mut RodsConnection,
    target: &Target,
) -> Result<Vec<Timestamp>, BatonError> {
    let mut q = GenQuery::new();

    let with_replicate = matches!(target, Target::DataObject(_));

    match target {
        Target::DataObject(d) => {
            // Data object: per-replica timestamps. SELECT order matches the
            // row indices we read out below.
            q.add_select(ffi::SHIM_COL_D_CREATE_TIME);
            q.add_select(ffi::SHIM_COL_D_MODIFY_TIME);
            q.add_select(ffi::SHIM_COL_DATA_REPL_NUM);
            q.add_where(
                ffi::SHIM_COL_COLL_NAME,
                &format!("= '{}'", sql_escape(&d.collection)),
            )?;
            q.add_where(
                ffi::SHIM_COL_DATA_NAME,
                &format!("= '{}'", sql_escape(&d.data_object)),
            )?;
        }
        Target::Collection(c) => {
            q.add_select(ffi::SHIM_COL_COLL_CREATE_TIME);
            q.add_select(ffi::SHIM_COL_COLL_MODIFY_TIME);
            q.add_where(
                ffi::SHIM_COL_COLL_NAME,
                &format!("= '{}'", sql_escape(&c.collection)),
            )?;
        }
    }

    let rows = conn.query(&mut q)?;

    let mut timestamps = Vec::with_capacity(rows.len() * 2);
    for row in rows {
        let created = row.first().cloned().unwrap_or_default();
        let modified = row.get(1).cloned().unwrap_or_default();
        let replicate = if with_replicate {
            row.get(2)
                .and_then(|s| s.parse::<u32>().ok())
        } else {
            None
        };

        timestamps.push(Timestamp {
            created: Some(created),
            modified: None,
            replicate,
        });
        timestamps.push(Timestamp {
            created: None,
            modified: Some(modified),
            replicate,
        });
    }
    Ok(timestamps)
}

/// List the direct children of a collection: sub-collections + data
/// objects, merged into one `Vec<Item>`.
///
/// iRODS doesn't expose both in a single `genQuery`, so we run two
/// queries — one filtering on `COL_COLL_PARENT_NAME` for the immediate
/// child collections, one filtering on `COL_COLL_NAME` for the data
/// objects directly under this collection. The result preserves
/// catalog order (sub-collections first, then data objects); baton's
/// own behaviour is also unsorted.
///
/// Each returned `Item` carries only path identity — no AVUs, ACLs,
/// timestamps, replicates, or recursive contents. Callers wanting
/// deeper detail can re-run `baton-list` with the appropriate flags
/// against each child.
fn fetch_contents(conn: &mut RodsConnection, parent: &str) -> Result<Vec<Item>, BatonError> {
    let mut items = Vec::new();

    // 1. Sub-collections directly under `parent`.
    let mut q = GenQuery::new();
    q.add_select(ffi::SHIM_COL_COLL_NAME);
    q.add_where(
        ffi::SHIM_COL_COLL_PARENT_NAME,
        &format!("= '{}'", sql_escape(parent)),
    )?;
    let sub_rows = conn.query(&mut q)?;
    for row in sub_rows {
        let path = row.into_iter().next().unwrap_or_default();
        items.push(Target::Collection(Collection {
            collection: path,
            avus: None,
            access: None,
            timestamps: None,
            contents: None,
            error: None,
        }));
    }

    // 2. Data objects directly under `parent`.
    let mut q = GenQuery::new();
    q.add_select(ffi::SHIM_COL_DATA_NAME);
    q.add_where(
        ffi::SHIM_COL_COLL_NAME,
        &format!("= '{}'", sql_escape(parent)),
    )?;
    let data_rows = conn.query(&mut q)?;
    for row in data_rows {
        let name = row.into_iter().next().unwrap_or_default();
        items.push(Target::DataObject(DataObject {
            collection: parent.to_string(),
            data_object: name,
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        }));
    }

    Ok(items)
}

fn parse_acl_level(s: &str) -> Result<AclLevel, BatonError> {
    match s {
        "null" => Ok(AclLevel::Null),
        "read" | "read object" => Ok(AclLevel::Read),
        "write" | "modify object" => Ok(AclLevel::Write),
        "own" => Ok(AclLevel::Own),
        other => Err(BatonError {
            code: -1,
            message: format!("unknown iRODS access level: {:?}", other),
        }),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_acl_level_accepts_compact_and_verbose_forms() {
        assert_eq!(parse_acl_level("null").unwrap(), AclLevel::Null);
        assert_eq!(parse_acl_level("read").unwrap(), AclLevel::Read);
        assert_eq!(parse_acl_level("read object").unwrap(), AclLevel::Read);
        assert_eq!(parse_acl_level("write").unwrap(), AclLevel::Write);
        assert_eq!(parse_acl_level("modify object").unwrap(), AclLevel::Write);
        assert_eq!(parse_acl_level("own").unwrap(), AclLevel::Own);
    }

    #[test]
    fn parse_acl_level_errors_on_unknown_string() {
        let err = parse_acl_level("inherit").unwrap_err();
        assert!(
            err.message.contains("unknown iRODS access level"),
            "got {:?}",
            err
        );
    }

    #[test]
    fn sql_escape_doubles_single_quotes() {
        assert_eq!(sql_escape("plain"), "plain");
        assert_eq!(sql_escape("O'Brien"), "O''Brien");
        assert_eq!(sql_escape("''"), "''''");
    }

    // --- pick_canonical_replica --------------------------------------------------

    /// Helper: build a row in the order pick_canonical_replica
    /// expects, so the tests below stay readable.
    fn row(num: u32, size: u64, checksum: &str, status: &str) -> Vec<String> {
        vec![
            num.to_string(),
            size.to_string(),
            checksum.to_string(),
            status.to_string(),
        ]
    }

    #[test]
    fn pick_canonical_replica_returns_none_for_empty_input() {
        // Empty catalog rows = no data object found in the join.
        // Caller falls back to rcObjStat for size / checksum.
        assert_eq!(pick_canonical_replica(&[]), None);
    }

    #[test]
    fn pick_canonical_replica_returns_the_only_valid_row() {
        // Single-replica steady state — what every iput produces on
        // a non-replicating resource. The lone valid row is the
        // canonical answer.
        let rows = vec![row(0, 1024, "abc", "1")];
        let got = pick_canonical_replica(&rows).expect("non-empty");
        assert_eq!(
            got,
            CanonicalReplicaState {
                size: 1024,
                checksum: "abc".to_string()
            }
        );
    }

    #[test]
    fn pick_canonical_replica_picks_highest_numbered_when_all_valid() {
        // Replicating resource in steady state: all replicas valid,
        // typically same size / checksum. Pinning the
        // highest-numbered selection rule explicitly so a future
        // refactor can't quietly switch to first-valid or
        // primary-valid.
        let rows = vec![
            row(0, 1024, "aaa", "1"),
            row(2, 1024, "ccc", "1"),
            row(1, 1024, "bbb", "1"),
        ];
        let got = pick_canonical_replica(&rows).expect("non-empty");
        assert_eq!(got.checksum, "ccc");
    }

    #[test]
    fn pick_canonical_replica_skips_invalid_replicas() {
        // Mid-replication state: replica 2 is in flight (status=0)
        // and disagrees with the others. We must not pick it.
        let rows = vec![
            row(0, 1024, "aaa", "1"),
            row(1, 1024, "bbb", "1"),
            row(2, 9999, "wrong", "0"),
        ];
        let got = pick_canonical_replica(&rows).expect("non-empty");
        assert_eq!(
            got,
            CanonicalReplicaState {
                size: 1024,
                checksum: "bbb".to_string()
            },
            "should pick highest-numbered VALID replica, not highest-numbered overall"
        );
    }

    #[test]
    fn pick_canonical_replica_returns_none_when_no_replica_is_valid() {
        // Every replica mid-write or otherwise stale. Caller falls
        // back to rcObjStat — better some answer than no answer for
        // a transient state.
        let rows = vec![
            row(0, 1024, "aaa", "0"),
            row(1, 1024, "bbb", "0"),
        ];
        assert_eq!(pick_canonical_replica(&rows), None);
    }

    #[test]
    fn pick_canonical_replica_skips_rows_with_unparseable_numbers() {
        // Defensive: if iRODS ever surfaces an unexpected non-numeric
        // in repl_num or size, the row is silently skipped rather
        // than poisoning the whole result. Same defensive shape as
        // fetch_replicates / fetch_avus.
        let rows = vec![
            row(0, 1024, "good", "1"),
            vec![
                "not_a_number".to_string(),
                "1024".to_string(),
                "bad".to_string(),
                "1".to_string(),
            ],
        ];
        let got = pick_canonical_replica(&rows).expect("non-empty");
        assert_eq!(got.checksum, "good");
    }
}

/// Same as [`list_one`], but catches iRODS errors and emits the input
/// annotated with an `"error"` field instead of propagating. The driving
/// binary uses this so one bad input doesn't abort the entire stream.
///
/// JSON-parse errors and other non-iRODS failures stay fail-fast at the
/// binary level — we can't annotate an input we couldn't parse in the
/// first place.
pub fn list_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
    opts: &ListOptions,
) -> Target {
    // Keep a copy we can annotate if list_one consumes and then errors.
    let fallback = target.clone();
    match list_one(conn, target, opts) {
        Ok(t) => t,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}
