// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-28

//! `baton-metamod` logic: apply one [`MetamodInput`] envelope at a time.
//!
//! Mirrors the shape of [`crate::operations::list`] — a fail-fast
//! `metamod_one` for callers that want to handle errors themselves, and
//! an `_annotated` wrapper that folds iRODS errors into the input's
//! `error` field so the driving binary can keep the NDJSON stream
//! flowing past a bad record.

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::types::MetamodInput;

/// Apply every AVU in `input` using `input.operation`. Returns the input
/// echoed back on success.
///
/// Stops at the first per-AVU failure and returns the iRODS error.
/// Earlier AVUs in the same input that already succeeded are NOT rolled
/// back — iRODS doesn't expose a transaction over individual AVU
/// modifications, so partial application is observable. Callers that
/// need atomicity should pre-validate inputs.
///
/// An empty `avus` list is a successful no-op — useful for inputs that
/// just want to round-trip through the binary unchanged.
pub fn metamod_one(
    conn: &mut RodsConnection,
    input: MetamodInput,
) -> Result<MetamodInput, BatonError> {
    let target = input.target();
    for avu in &input.avus {
        conn.mod_avu(input.operation, &target, avu)?;
    }
    Ok(input)
}

/// Same as [`metamod_one`], but catches iRODS errors and emits the
/// input annotated with an `"error"` field instead of propagating.
/// The driving binary uses this so one bad input doesn't abort the
/// entire stream.
///
/// Parse / IO errors at the binary boundary stay fail-fast — we can't
/// annotate something we couldn't parse.
pub fn metamod_one_annotated(
    conn: &mut RodsConnection,
    input: MetamodInput,
) -> MetamodInput {
    // Keep a copy we can annotate if metamod_one consumes and then
    // errors. Cheap clone — MetamodInput is shallow.
    let fallback = input.clone();
    match metamod_one(conn, input) {
        Ok(out) => out,
        Err(err) => {
            let mut annotated = fallback;
            annotated.error = Some(err);
            annotated
        }
    }
}
