// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-12

//! Per-operation logic shared between binaries.
//!
//! Each submodule here implements one baton command; `src/bin/baton-<name>.rs`
//! is a thin clap shell that parses arguments and calls into the matching
//! function here. Keeping operations out of `src/bin/` lets integration tests
//! drive them directly.

pub mod baton_do;
pub mod checksum;
pub mod chmod;
pub mod get;
pub mod list;
pub mod metamod;
pub mod metaquery;
pub mod mkdir;
pub mod mv;
pub mod put;
pub mod rm;
pub mod rmdir;

use crate::error::BatonError;
use crate::types::{MetamodInput, Target};

/// Types whose in-band error annotation can be set in place.
///
/// `Target` and [`MetamodInput`] both carry an `error: Option<BatonError>`
/// field that the operations layer populates on per-input failure. This
/// trait abstracts that single setter so [`annotate_failure`] can drive
/// both uniformly without two near-identical helpers.
pub trait Annotatable: Clone {
    fn set_error(&mut self, err: BatonError);
}

impl Annotatable for Target {
    fn set_error(&mut self, err: BatonError) {
        Target::set_error(self, err);
    }
}

impl Annotatable for MetamodInput {
    fn set_error(&mut self, err: BatonError) {
        MetamodInput::set_error(self, err);
    }
}

/// Run `op` against `input`; on success return its output unchanged,
/// on failure return the original `input` annotated with the error.
///
/// Collapses the boilerplate of each operation's `*_one_annotated`
/// wrapper. The pre-call clone is the cost of being able to echo the
/// input back on failure (so the NDJSON loop sees a fully-formed
/// envelope on every iteration).
pub fn annotate_failure<T, F>(input: T, op: F) -> T
where
    T: Annotatable,
    F: FnOnce(T) -> Result<T, BatonError>,
{
    let fallback = input.clone();
    match op(input) {
        Ok(out) => out,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}

// --- checksum comparison -----------------------------------------------------

/// Test whether a client-computed hex digest agrees with iRODS's
/// `rcDataObjChksum` output. Server-side digests may carry an
/// algorithm prefix (e.g. `MD5:abcd...` or `sha2:<base64>`); this
/// strips anything before the first colon and does a case-insensitive
/// ASCII compare on what remains. With the MD5 client default pinned
/// for issue #25 the server typically returns bare hex, but the
/// stripping keeps the comparison robust if an iRODS image surfaces a
/// prefix.
///
/// Crate-private; shared between `put_one --verify` (post-upload
/// digest verify) and `get_one --verify` (post-download digest
/// verify). Exercised by the unit tests below.
pub(crate) fn checksums_match(client_hex: &str, server: &str) -> bool {
    let server_digest = match server.split_once(':') {
        Some((_algo, digest)) => digest,
        None => server,
    };
    client_hex.eq_ignore_ascii_case(server_digest)
}

/// Wrap [`checksums_match`] with the error-construction the verify
/// path uses on a mismatch. `op_name` (e.g. `"put"` / `"get"`) goes
/// into the error message so log readers know which side noticed the
/// divergence. Kept separate from `checksums_match` so the polarity
/// (we error on mismatch, not on match) and the message shape are
/// independently pinnable in unit tests, without the test having to
/// drive a real iRODS connection.
pub(crate) fn verify_checksum(
    client_hex: &str,
    server: &str,
    op_name: &str,
) -> Result<(), BatonError> {
    if checksums_match(client_hex, server) {
        Ok(())
    } else {
        // -407000 CHECK_VERIFICATION_RESULTS. Matches the code
        // iRODS returns from server-side verify (the shim's
        // VERIFY_CHKSUM_KW path) so client-side and server-side
        // mismatch surface identically to downstream consumers.
        // Partisan's `test_verify_checksum_bad` asserts
        // `e.code == -407000` and the message matches `"checksum"`
        // — both pin tests against the upstream iRODS code, not
        // baton-rs's previous synthetic -1.
        //
        // Goes through `from_irods_with_context` so the
        // descriptive-phrase lookup adds "checksum verification
        // failed" prose alongside the symbolic name. See the
        // table in `error::descriptive_phrase`.
        Err(BatonError::from_irods_with_context(
            -407000,
            &format!(
                "checksum mismatch after {}: client {} != server {}",
                op_name, client_hex, server
            ),
        ))
    }
}

#[cfg(test)]
mod checksum_tests {
    use super::*;

    #[test]
    fn checksums_match_returns_true_on_exact_match() {
        assert!(checksums_match(
            "abcdef0123456789",
            "abcdef0123456789",
        ));
    }

    #[test]
    fn checksums_match_strips_md5_prefix_on_server_side() {
        // Some iRODS images surface a `MD5:` prefix; we tolerate it.
        assert!(checksums_match(
            "abcdef0123456789",
            "MD5:abcdef0123456789",
        ));
    }

    #[test]
    fn checksums_match_handles_sha2_format() {
        // SHA2 is out of scope for the current MD5-only client, but
        // the prefix-stripping path runs the same way; pin it so the
        // pluggable hash-scheme work (issue #31) and its matrix
        // tests (issue #27) can plug in without rewriting the
        // comparison.
        assert!(checksums_match(
            "deadbeefcafe",
            "sha2:deadbeefcafe",
        ));
    }

    #[test]
    fn checksums_match_is_case_insensitive_on_ascii() {
        // md5 crate emits lowercase hex; server may return upper or
        // mixed case across iRODS versions.
        assert!(checksums_match(
            "ABCDEF0123456789",
            "abcdef0123456789",
        ));
        assert!(checksums_match(
            "abcdef0123456789",
            "ABCDEF0123456789",
        ));
    }

    #[test]
    fn checksums_match_returns_false_on_mismatch() {
        assert!(!checksums_match(
            "abcdef0123456789",
            "fedcba9876543210",
        ));
    }

    #[test]
    fn checksums_match_returns_false_on_mismatch_with_prefix() {
        // Prefix-stripping must not create a false positive — only
        // the post-colon digest is compared.
        assert!(!checksums_match(
            "abcdef0123456789",
            "MD5:fedcba9876543210",
        ));
    }

    #[test]
    fn verify_checksum_ok_on_match() {
        assert!(verify_checksum("abcdef", "abcdef", "put").is_ok());
    }

    #[test]
    fn verify_checksum_err_on_mismatch_names_op_and_both_digests() {
        let err = verify_checksum("abcdef", "fedcba", "get").unwrap_err();
        // -407000 CHECK_VERIFICATION_RESULTS. Matches the
        // server-side mismatch code iRODS returns from
        // `rcDataObjChksum` in VERIFY mode (see the shim's
        // `VERIFY_CHKSUM_KW` path), so client-side and
        // server-side mismatch surface identically to downstream
        // consumers. Partisan's `test_verify_checksum_bad` pins
        // this code.
        assert_eq!(
            err.code, -407000,
            "client-side checksum mismatch should surface as -407000 (CHECK_VERIFICATION_RESULTS): {:?}",
            err
        );
        assert!(
            err.message.contains("get"),
            "error message should name the operation: {:?}",
            err
        );
        assert!(
            err.message.contains("abcdef"),
            "error message should name the client digest: {:?}",
            err
        );
        assert!(
            err.message.contains("fedcba"),
            "error message should name the server digest: {:?}",
            err
        );
        assert!(
            err.message.contains("mismatch"),
            "error message should mention 'mismatch': {:?}",
            err
        );
    }

    #[test]
    fn verify_checksum_polarity_errs_only_on_mismatch() {
        assert!(verify_checksum("aa", "aa", "put").is_ok());
        assert!(verify_checksum("aa", "bb", "put").is_err());
    }
}
