// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! Per-operation logic shared between binaries.
//!
//! Each submodule here implements one baton command; `src/bin/baton-<name>.rs`
//! is a thin clap shell that parses arguments and calls into the matching
//! function here. Keeping operations out of `src/bin/` lets integration tests
//! drive them directly.

pub mod list;
