// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-06

//! Per-operation logic shared between binaries.
//!
//! Each submodule here implements one baton command; `src/bin/baton-<name>.rs`
//! is a thin clap shell that parses arguments and calls into the matching
//! function here. Keeping operations out of `src/bin/` lets integration tests
//! drive them directly.

pub mod baton_do;
pub mod checksum;
pub mod chmod;
pub mod get;
pub mod list;
pub mod metamod;
pub mod metaquery;
pub mod mkdir;
pub mod mv;
pub mod put;
pub mod rm;
pub mod rmdir;

use crate::error::BatonError;
use crate::types::{MetamodInput, Target};

/// Types whose in-band error annotation can be set in place.
///
/// `Target` and [`MetamodInput`] both carry an `error: Option<BatonError>`
/// field that the operations layer populates on per-input failure. This
/// trait abstracts that single setter so [`annotate_failure`] can drive
/// both uniformly without two near-identical helpers.
pub trait Annotatable: Clone {
    fn set_error(&mut self, err: BatonError);
}

impl Annotatable for Target {
    fn set_error(&mut self, err: BatonError) {
        Target::set_error(self, err);
    }
}

impl Annotatable for MetamodInput {
    fn set_error(&mut self, err: BatonError) {
        MetamodInput::set_error(self, err);
    }
}

/// Run `op` against `input`; on success return its output unchanged,
/// on failure return the original `input` annotated with the error.
///
/// Collapses the boilerplate of each operation's `*_one_annotated`
/// wrapper. The pre-call clone is the cost of being able to echo the
/// input back on failure (so the NDJSON loop sees a fully-formed
/// envelope on every iteration).
pub fn annotate_failure<T, F>(input: T, op: F) -> T
where
    T: Annotatable,
    F: FnOnce(T) -> Result<T, BatonError>,
{
    let fallback = input.clone();
    match op(input) {
        Ok(out) => out,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}
