// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-05
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-06

//! `baton-do move` logic: rename or relocate a data object or
//! collection.
//!
//! Wraps the existing `RodsConnection::rename` (which itself
//! wraps `shim_rename` over `rcDataObjRename`). Source path is
//! read from `target.path()`; destination is a separate
//! parameter — the dispatcher in `baton-do` pulls it from the
//! envelope's `arguments.path` field, matching upstream
//! (`baton/src/operations.c:707-737`,
//! `baton/src/baton.c:442-502`).
//!
//! The same iRODS C call handles both data-object and collection
//! moves; the source-type flag (`RENAME_DATA_OBJ` vs
//! `RENAME_COLL` `oprType`) derives from the [`Target`] variant
//! inside the connection wrapper. Cross-collection moves work
//! without a client-side scoping check; iRODS resolves the
//! destination against the catalog (matches upstream baton).
//!
//! Echoes the input target unchanged on success. The output line
//! describes the source path; consumers tracking destination
//! state should query separately if needed.

use crate::connection::RodsConnection;
use crate::error::BatonError;
use crate::types::Target;

/// Rename `target` to `dest_path`. Source's path and source-type
/// flag both derive from the [`Target`] variant; destination is
/// taken verbatim — the dispatcher in `baton-do` is responsible
/// for pulling it out of `arguments.path` and passing the
/// resolved string here.
///
/// Empty destination paths are rejected client-side with a
/// typed [`BatonError`] (clearer than letting iRODS return
/// `USER_INPUT_PATH_ERR`).
///
/// Echoes the input target unchanged on success.
pub fn mv_one(
    conn: &mut RodsConnection,
    target: Target,
    dest_path: &str,
) -> Result<Target, BatonError> {
    if dest_path.is_empty() {
        return Err(BatonError {
            code: -1,
            message: "baton-do move: destination path is empty".to_string(),
        });
    }
    conn.rename(&target, dest_path)?;
    Ok(target)
}

/// Same as [`mv_one`], but catches iRODS errors and emits the
/// input annotated with an `"error"` field instead of
/// propagating. Mirrors the rest of the operations layer's
/// `*_one_annotated` wrappers.
pub fn mv_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
    dest_path: &str,
) -> Target {
    super::annotate_failure(target, |t| mv_one(conn, t, dest_path))
}
