// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-01
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01

//! `baton-put` logic: stream a local file up to an iRODS data object.
//!
//! Symmetric with `baton-get --save`: the input record names the
//! iRODS destination via `collection` + `data_object` and the local
//! source via `directory` (the local file is `<directory>/<data_object>`).
//! Same name on both sides; renaming is out of scope.
//!
//! `--checksum` (server-side digest after upload) and `--verify`
//! (client-side streaming MD5 + server compare) land in the next two
//! commits. The `PutOptions` flags are present here so the API
//! shape doesn't churn.

use std::fs::File;
use std::io::Read;
use std::path::PathBuf;

use crate::connection::{OpenMode, RodsConnection};
use crate::error::BatonError;
use crate::types::Target;

/// Caller-controlled flags for [`put_one`].
#[derive(Debug, Default, Clone, Copy)]
pub struct PutOptions {
    /// Compute and record a server-side checksum after the upload
    /// completes via `rcDataObjChksum`; populated on the output
    /// `checksum` field. The format depends on the server hash
    /// scheme — bare 32-char hex for MD5 (the client default pinned
    /// for issue #25), `sha2:<base64>` for SHA2.
    pub checksum: bool,

    /// Compute MD5 client-side as bytes are streamed up, then
    /// compare against the server's checksum after close. Mismatch
    /// surfaces as a per-input error. Wired in the next commit.
    pub verify: bool,
}

// Same chunk size as the read path — keeps memory pressure
// predictable across get/put and lets the future streaming-MD5 path
// hash exactly the bytes that were written.
const WRITE_CHUNK_SIZE: usize = 64 * 1024;

/// Stream a local file up to an iRODS data object.
///
/// Required input fields:
///   - `collection`: target iRODS collection
///   - `data_object`: target name (also the local filename)
///   - `directory`: local source directory; the file at
///     `<directory>/<data_object>` is uploaded
///
/// The output is the input record echoed unchanged. The
/// `--checksum` and `--verify` flags will populate the `checksum`
/// field once they're wired (next two commits).
///
/// Collections are an error: there's nothing to put for a
/// collection. Matches the symmetric behaviour of [`crate::operations::get::get_one`].
pub fn put_one(
    conn: &mut RodsConnection,
    target: Target,
    opts: &PutOptions,
) -> Result<Target, BatonError> {
    let path = target.path();
    let mut data_obj = match target {
        Target::DataObject(d) => d,
        Target::Collection(c) => {
            return Err(BatonError {
                code: -1,
                message: format!(
                    "baton-put: target is a collection, not a data object: {}",
                    c.collection
                ),
            });
        }
    };

    let directory = data_obj.directory.as_deref().ok_or(BatonError {
        code: -1,
        message: "baton-put requires a `directory` field on each input record".to_string(),
    })?;
    let mut local_path = PathBuf::from(directory);
    local_path.push(&data_obj.data_object);

    let mut file = File::open(&local_path).map_err(|e| BatonError {
        code: -1,
        message: format!("could not open local file {}: {}", local_path.display(), e),
    })?;

    let handle = conn.open_data_object(&path, OpenMode::Write)?;
    let stream_result = stream_file_to_handle(conn, handle, &mut file);
    // Close on every path. iRODS server-side state for the L1
    // descriptor lives until close; failing to close on the error
    // path would leak the descriptor for the lifetime of the
    // connection.
    let close_result = conn.close_data_object(handle);
    stream_result?;
    close_result?;

    // Server-side checksum runs after close — `rcDataObjChksum`
    // operates on the catalog state, not the in-flight L1 descriptor.
    // Done unconditionally when --checksum is set; a future --verify
    // path will also need the digest, so no point splitting the call.
    if opts.checksum {
        data_obj.checksum = Some(conn.checksum_data_object(&path)?);
    }

    Ok(Target::DataObject(data_obj))
}

/// Same as [`put_one`], but catches iRODS errors and emits the input
/// annotated with an `"error"` field instead of propagating. Mirrors
/// `get_one_annotated` so binaries can keep their NDJSON loops uniform.
pub fn put_one_annotated(
    conn: &mut RodsConnection,
    target: Target,
    opts: &PutOptions,
) -> Target {
    let fallback = target.clone();
    match put_one(conn, target, opts) {
        Ok(t) => t,
        Err(err) => {
            let mut annotated = fallback;
            annotated.set_error(err);
            annotated
        }
    }
}

/// Read `file` chunk by chunk and write each chunk into `handle`.
/// Stops at EOF (zero-byte read) on the local side. Short writes from
/// `write_data_object` are re-issued for the remainder, even though
/// iRODS doesn't typically short-write — defensive for when iRODS's
/// internals change.
fn stream_file_to_handle<R: Read>(
    conn: &mut RodsConnection,
    handle: i32,
    file: &mut R,
) -> Result<(), BatonError> {
    let mut buf = vec![0u8; WRITE_CHUNK_SIZE];
    loop {
        let n = file.read(&mut buf).map_err(|e| BatonError {
            code: -1,
            message: format!("reading local file: {}", e),
        })?;
        if n == 0 {
            break;
        }
        let mut written = 0;
        while written < n {
            let m = conn.write_data_object(handle, &buf[written..n])?;
            if m == 0 {
                return Err(BatonError {
                    code: -1,
                    message: "rcDataObjWrite accepted 0 bytes; aborting to avoid spinning"
                        .to_string(),
                });
            }
            written += m;
        }
    }
    Ok(())
}
