// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-01

//! Safe wrapper around an iRODS client connection.
//!
//! This module exposes `RodsConnection`, a RAII handle over an opaque
//! `shim_rods_conn_t *` (internally a `rcComm_t *`, hidden inside the C
//! shim — see `shim/ffi_shim.{c,h}` and issue #9 for the rationale).
//! Constructing one calls `shim_open` (`rcConnect`); dropping one
//! calls `shim_close` (`rcDisconnect`). Every iRODS API in use by
//! baton-rs (auth, stat, queries, metamod, error-name lookup) lands
//! through the shim — Rust has no `rcComm_t *` cast site any longer.
//!
//! Connections are single-threaded by default: the underlying iRODS
//! handle is not safe to share across threads, and the raw-pointer
//! field makes `RodsConnection` `!Send` and `!Sync` automatically.

use std::ffi::{CStr, CString};
use std::mem::MaybeUninit;
use std::os::raw::{c_char, c_int, c_void};
use std::time::{Duration, Instant};

use crate::error::BatonError;
use crate::ffi;
use crate::types::{Acl, Avu, MetamodOperation, Target};

/// Default `--connect-time` threshold in seconds. Matches upstream
/// baton's `DEFAULT_MAX_CONNECT_TIME` (600s = 10 minutes) — see
/// `baton/src/baton.h:34`. Long enough that typical short streams
/// never reconnect; short enough that long-running streams cycle the
/// connection before any firewall idle-timeout kicks in.
pub const DEFAULT_CONNECT_TIME_SECS: u64 = 600;

/// Minimum permitted `--connect-time` value. baton enforces ≥10s at
/// `operations.c:77-83`; we mirror that — a one-second threshold
/// would reconnect on almost every record and isn't a useful
/// configuration.
pub const MIN_CONNECT_TIME_SECS: u64 = 10;

/// Wraps a [`RodsConnection`] with a wall-clock watchdog. The
/// driving binary calls [`Self::maybe_reconnect`] before each input
/// record; if the threshold has elapsed since the last reconnect
/// (or the initial connect), the connection is torn down and rebuilt
/// transparently.
///
/// Mirrors upstream baton's `--connect-time` semantics exactly:
/// **between-records only**, never mid-stream. A long-running put or
/// get holds the connection for its full duration; the reconnect
/// fires before the *next* record. iRODS handles never get
/// disconnected mid-write because we only check the threshold at
/// record boundaries.
///
/// The actual reconnect call goes through
/// [`RodsConnection::reconnect`], which already handles teardown +
/// re-auth. Callers don't need to know the details.
pub struct ReconnectingSession {
    conn: RodsConnection,
    last_reconnect: Instant,
    max_connect_time: Duration,
}

impl ReconnectingSession {
    /// Wrap an already-authenticated `conn` with a `--connect-time`
    /// watchdog. The wall-clock starts ticking from this call —
    /// callers should construct the session immediately after
    /// `connect_from_env` + `login_from_auth_file`.
    pub fn new(conn: RodsConnection, max_connect_time: Duration) -> Self {
        Self {
            conn,
            last_reconnect: Instant::now(),
            max_connect_time,
        }
    }

    /// Reconnect if the threshold has elapsed since the last
    /// reconnect (or initial connect). Returns a mutable borrow of
    /// the underlying connection so the caller can drive the next
    /// per-record op against it.
    ///
    /// On reconnect failure, the underlying [`RodsConnection`] is
    /// left in a "null pointer, safe to drop" state per
    /// `RodsConnection::reconnect`'s contract — the error is
    /// returned to the caller, which can either propagate it
    /// (fail-fast) or surface it as an in-band per-input error.
    pub fn maybe_reconnect(&mut self) -> Result<&mut RodsConnection, BatonError> {
        if should_reconnect(self.last_reconnect, self.max_connect_time) {
            self.conn.reconnect()?;
            self.last_reconnect = Instant::now();
        }
        Ok(&mut self.conn)
    }

    /// Borrow the connection without checking the threshold. Used
    /// for the initial setup phase before the NDJSON loop starts —
    /// e.g. the optional `--unsafe` path validation in Session 8.
    pub fn conn_mut(&mut self) -> &mut RodsConnection {
        &mut self.conn
    }
}

/// Pure threshold check, extracted so the rule can be unit-tested
/// without driving a real iRODS connection.
fn should_reconnect(last_reconnect: Instant, max_connect_time: Duration) -> bool {
    last_reconnect.elapsed() >= max_connect_time
}

/// Clap value parser for `--connect-time`. Accepts a positive
/// integer number of seconds, rejecting values below
/// [`MIN_CONNECT_TIME_SECS`] with a user-readable error. Shared
/// across every binary that exposes the flag, so the validation
/// rule lives in one place.
pub fn parse_connect_time(s: &str) -> Result<u64, String> {
    let n: u64 = s.parse().map_err(|e: std::num::ParseIntError| e.to_string())?;
    if n < MIN_CONNECT_TIME_SECS {
        return Err(format!(
            "--connect-time must be >= {} seconds",
            MIN_CONNECT_TIME_SECS
        ));
    }
    Ok(n)
}

/// Distilled-down stat output: just the fields that the listing layer
/// needs. Avoids leaking `rodsObjStat_t` across the public crate boundary.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ObjStat {
    pub size: u64,
    /// Empty string when iRODS has no checksum recorded for this object
    /// (collections, or data objects where `ichksum` has never run).
    pub checksum: String,
    pub obj_type: ObjType,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ObjType {
    DataObject,
    Collection,
    /// iRODS sometimes reports additional types (e.g. spec-coll link targets).
    /// Carry the raw code so callers who care can handle it.
    Other(i32),
}

/// Mode for [`RodsConnection::open_data_object`].
///
/// `Write` maps to `O_WRONLY | O_CREAT | O_TRUNC` inside the shim —
/// overwrite-on-collision, matching `baton-put` and `iput -f`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpenMode {
    Read,
    Write,
}

/// A live connection to an iRODS server.
pub struct RodsConnection {
    conn: *mut ffi::shim_rods_conn,
}

/// Builder over an iRODS general query (`genQueryInp_t`), held opaque
/// behind the C shim. Construct one with [`GenQuery::new`], populate
/// the SELECT and WHERE lists, then run it through
/// [`RodsConnection::query`]. Dropping a `GenQuery` frees the
/// underlying iRODS state via `clearGenQueryInp`.
///
/// `pub(crate)` because the per-flag fetchers in `crate::operations`
/// are the only callers; we don't expose a low-level query builder
/// across the public crate boundary.
pub(crate) struct GenQuery {
    handle: *mut ffi::shim_query,
}

impl GenQuery {
    pub(crate) fn new() -> Self {
        let handle = unsafe { ffi::shim_query_new() };
        // Only failure mode is calloc OOM at construct time. Panicking
        // is appropriate — there's no useful work the caller can do
        // when the allocator is exhausted.
        assert!(!handle.is_null(), "shim_query_new returned NULL");
        Self { handle }
    }

    /// Add `col` to the SELECT list (no aggregation). `col` is one of
    /// the `ffi::SHIM_COL_*` enum values; the shim translates to the
    /// iRODS `COL_*` numeric internally.
    pub(crate) fn add_select(&mut self, col: ffi::shim_col_t) {
        unsafe { ffi::shim_query_add_select(self.handle, col) };
    }

    /// Add a WHERE condition. `condition` is the operator + literal in
    /// the form iRODS's genQuery parser wants, e.g. `"= '/zone/home'"`.
    /// Returns an error if `condition` contains an interior NUL.
    pub(crate) fn add_where(
        &mut self,
        col: ffi::shim_col_t,
        condition: &str,
    ) -> Result<(), BatonError> {
        let c = CString::new(condition).map_err(|_| BatonError {
            code: -1,
            message: "WHERE condition contains interior NUL".to_string(),
        })?;
        let status = unsafe { ffi::shim_query_add_where(self.handle, col, c.as_ptr()) };
        if status != 0 {
            return Err(BatonError::from_irods(status));
        }
        Ok(())
    }
}

impl Drop for GenQuery {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            unsafe { ffi::shim_query_free(self.handle) };
            self.handle = std::ptr::null_mut();
        }
    }
}

impl RodsConnection {
    /// Open a connection using the iRODS environment file at
    /// `$HOME/.irods/irods_environment.json`.
    ///
    /// Performs the TCP handshake and iRODS version negotiation only.
    /// Call [`Self::login_from_auth_file`] afterwards for any iRODS
    /// operation that requires an authenticated session.
    pub fn connect_from_env() -> Result<Self, BatonError> {
        let conn = Self::open_raw()?;
        Ok(Self { conn })
    }

    /// Internal: open a fresh connection using the iRODS environment
    /// file. Shared between [`Self::connect_from_env`] and
    /// [`Self::reconnect`] so both use the same connect parameters.
    ///
    /// Goes through the shim's `shim_get_env` + `shim_open`. The shim
    /// reads `rodsEnv`, calls `rcConnect`, and surfaces the error
    /// message text via a caller-supplied buffer — bindings never see
    /// the iRODS structs.
    fn open_raw() -> Result<*mut ffi::shim_rods_conn, BatonError> {
        let mut env = MaybeUninit::<ffi::shim_env_t>::zeroed();
        let env_status = unsafe { ffi::shim_get_env(env.as_mut_ptr()) };
        if env_status != 0 {
            return Err(BatonError::from_irods(env_status));
        }
        let env = unsafe { env.assume_init() };

        let mut status: std::os::raw::c_int = 0;
        // Buffer size is generous — iRODS error messages are bounded but
        // we'd rather truncate cleanly inside the shim than guess too low.
        let mut err_msg: [std::os::raw::c_char; 1024] = [0; 1024];

        let conn = unsafe {
            ffi::shim_open(
                env.host.as_ptr(),
                env.port,
                env.user.as_ptr(),
                env.zone.as_ptr(),
                &mut status,
                err_msg.as_mut_ptr(),
                err_msg.len() as std::os::raw::c_int,
            )
        };

        if conn.is_null() {
            let msg = unsafe { CStr::from_ptr(err_msg.as_ptr()) }
                .to_string_lossy()
                .into_owned();
            return Err(BatonError::from_irods_with_context(status, &msg));
        }

        Ok(conn)
    }

    /// Stat an iRODS path to confirm existence and discover basic metadata
    /// (size, checksum, object type).
    ///
    /// Wraps `shim_stat`, which internally builds the `dataObjInp_t`,
    /// calls `rcObjStat`, copies the relevant fields, and frees the
    /// iRODS allocation before returning. Callers see only the POD
    /// `shim_stat_t`.
    pub fn stat(&mut self, path: &str) -> Result<ObjStat, BatonError> {
        let path_c = CString::new(path).map_err(|_| BatonError {
            code: -1,
            message: "path contains interior NUL".to_string(),
        })?;

        let mut out = MaybeUninit::<ffi::shim_stat_t>::zeroed();
        let status = unsafe { ffi::shim_stat(self.conn, path_c.as_ptr(), out.as_mut_ptr()) };

        if status < 0 {
            return Err(BatonError::from_irods(status));
        }
        let out = unsafe { out.assume_init() };

        let obj_type = match out.obj_type {
            // 1 = data object, 2 = collection — see shim_stat_t docs.
            1 => ObjType::DataObject,
            2 => ObjType::Collection,
            other => ObjType::Other(other),
        };

        Ok(ObjStat {
            size: out.size as u64,
            checksum: unsafe { CStr::from_ptr(out.checksum.as_ptr()) }
                .to_string_lossy()
                .into_owned(),
            obj_type,
        })
    }

    /// Execute a prepared [`GenQuery`] and return every matching row as
    /// a flat `Vec<Vec<String>>`. Pagination is handled inside the
    /// shim's `shim_query_exec` — callers see one combined result.
    ///
    /// `CAT_NO_ROWS_FOUND` is treated as an empty result, not an error
    /// (the shim absorbs that). Any other negative iRODS status
    /// becomes a `BatonError`.
    ///
    /// `pub(crate)` because [`GenQuery`] is crate-internal; the
    /// per-flag helpers in `crate::operations` build the query locally
    /// and expose typed wrappers.
    pub(crate) fn query(
        &mut self,
        q: &mut GenQuery,
    ) -> Result<Vec<Vec<String>>, BatonError> {
        let mut status: std::os::raw::c_int = 0;
        let result = unsafe { ffi::shim_query_exec(self.conn, q.handle, &mut status) };

        if result.is_null() {
            return Err(BatonError::from_irods(status));
        }

        let n_rows = unsafe { ffi::shim_query_result_row_count(result) };
        let n_cols = unsafe { ffi::shim_query_result_col_count(result) };

        let mut rows: Vec<Vec<String>> = Vec::with_capacity(n_rows as usize);
        for r in 0..n_rows {
            let mut row = Vec::with_capacity(n_cols as usize);
            for c in 0..n_cols {
                let cell = unsafe { ffi::shim_query_result_get(result, r, c) };
                // shim_query_result_get only returns NULL on
                // out-of-range indices — we're inside the bounds we
                // just read, so a NULL here would be a shim bug.
                let s = if cell.is_null() {
                    String::new()
                } else {
                    unsafe { CStr::from_ptr(cell) }
                        .to_string_lossy()
                        .into_owned()
                };
                row.push(s);
            }
            rows.push(row);
        }

        unsafe { ffi::shim_query_result_free(result) };
        Ok(rows)
    }

    /// Add or remove a single AVU on a data object or collection.
    ///
    /// Wraps `shim_mod_avu`, which builds the iRODS
    /// `modAVUMetadataInp_t` (arg0..arg9 stringly-typed positional
    /// layout) and calls `rcModAVUMetadata` internally. Rust just
    /// hands over the named pieces:
    ///   - operation: "add" or "rm"
    ///   - target type: "-d" (data object) or "-C" (collection)
    ///   - path / attribute / value / optional units
    ///
    /// `CString` allocations live only for the call — iRODS does not
    /// retain the pointers past return.
    pub fn mod_avu(
        &mut self,
        operation: MetamodOperation,
        target: &Target,
        avu: &Avu,
    ) -> Result<(), BatonError> {
        // Operation + target-type flag are constants, so CString::new
        // can never fail on them; unwrap is appropriate.
        let op_c = CString::new(match operation {
            MetamodOperation::Add => "add",
            MetamodOperation::Rm => "rm",
        })
        .unwrap();
        let tt_c = CString::new(match target {
            Target::DataObject(_) => "-d",
            Target::Collection(_) => "-C",
        })
        .unwrap();

        // Caller-supplied strings — interior NUL is a programmer/input
        // error we surface as a clean BatonError rather than a panic.
        let path_c = CString::new(target.path()).map_err(|_| BatonError {
            code: -1,
            message: "path contains interior NUL".to_string(),
        })?;
        let attr_c = CString::new(avu.attribute.as_str()).map_err(|_| BatonError {
            code: -1,
            message: "AVU attribute contains interior NUL".to_string(),
        })?;
        let value_c = CString::new(avu.value.as_str()).map_err(|_| BatonError {
            code: -1,
            message: "AVU value contains interior NUL".to_string(),
        })?;
        let units_c = avu
            .units
            .as_ref()
            .map(|u| CString::new(u.as_str()))
            .transpose()
            .map_err(|_| BatonError {
                code: -1,
                message: "AVU units contains interior NUL".to_string(),
            })?;
        let units_ptr = units_c
            .as_ref()
            .map_or(std::ptr::null(), |c| c.as_ptr());

        let status = unsafe {
            ffi::shim_mod_avu(
                self.conn,
                op_c.as_ptr(),
                tt_c.as_ptr(),
                path_c.as_ptr(),
                attr_c.as_ptr(),
                value_c.as_ptr(),
                units_ptr,
            )
        };

        if status != 0 {
            return Err(BatonError::from_irods(status));
        }

        Ok(())
    }

    /// Apply a single ACL grant or revoke to `target`. The level
    /// string is sourced from [`Acl::level`] via
    /// [`crate::types::AclLevel::as_irods_str`]; the user, optional
    /// zone, and `recursive` flag are passed straight through.
    ///
    /// Wraps `shim_mod_access_control`, which builds the
    /// `modAccessControlInp_t` and dispatches one `rcModAccessControl`
    /// round-trip. One call per (path, owner, level) tuple — for a
    /// multi-grant ACL list the caller iterates and re-enters.
    /// Matches upstream baton (`baton/src/operations.c:416-421`).
    ///
    /// `recursive` only takes effect on collection targets — iRODS
    /// performs the traversal server-side. baton-rs does no
    /// client-side walk.
    ///
    /// `acl.zone` is optional. When `None`, the shim sends an empty
    /// zone string and iRODS resolves to the server's local zone.
    /// Mirrors upstream baton's `parseUserName`-driven default.
    pub fn mod_access_control(
        &mut self,
        target: &Target,
        acl: &Acl,
        recursive: bool,
    ) -> Result<(), BatonError> {
        // Caller-supplied strings — interior NUL is a programmer /
        // input error surfaced as a clean BatonError rather than a
        // panic. The level string is internal (came from our own
        // enum), so its CString::new can't fail; unwrap is fine.
        let path_c = CString::new(target.path()).map_err(|_| BatonError {
            code: -1,
            message: "path contains interior NUL".to_string(),
        })?;
        let level_c = CString::new(acl.level.as_irods_str()).unwrap();
        let user_c = CString::new(acl.owner.as_str()).map_err(|_| BatonError {
            code: -1,
            message: "ACL owner contains interior NUL".to_string(),
        })?;
        let zone_c = acl
            .zone
            .as_ref()
            .map(|z| CString::new(z.as_str()))
            .transpose()
            .map_err(|_| BatonError {
                code: -1,
                message: "ACL zone contains interior NUL".to_string(),
            })?;
        let zone_ptr = zone_c.as_ref().map_or(std::ptr::null(), |c| c.as_ptr());

        let status = unsafe {
            ffi::shim_mod_access_control(
                self.conn,
                path_c.as_ptr(),
                level_c.as_ptr(),
                user_c.as_ptr(),
                zone_ptr,
                if recursive { 1 } else { 0 },
            )
        };

        if status != 0 {
            return Err(BatonError::from_irods(status));
        }

        Ok(())
    }

    /// Open a data object for streaming I/O. Returns an iRODS L1
    /// descriptor — a non-negative int — that subsequent reads/writes
    /// refer to. Pass the handle to [`Self::close_data_object`] when
    /// done.
    ///
    /// Wraps `shim_data_obj_open`, which builds the `dataObjInp_t`
    /// internally and calls `rcDataObjOpen`. Rust never sees the iRODS
    /// struct.
    pub fn open_data_object(
        &mut self,
        path: &str,
        mode: OpenMode,
    ) -> Result<i32, BatonError> {
        let path_c = CString::new(path).map_err(|_| BatonError {
            code: -1,
            message: "path contains interior NUL".to_string(),
        })?;
        let mode_v = match mode {
            OpenMode::Read => ffi::SHIM_OPEN_READ,
            OpenMode::Write => ffi::SHIM_OPEN_WRITE,
        };
        let handle = unsafe { ffi::shim_data_obj_open(self.conn, path_c.as_ptr(), mode_v) };
        if handle < 0 {
            return Err(BatonError::from_irods(handle));
        }
        Ok(handle)
    }

    /// Read up to `buf.len()` bytes from `handle` into `buf`. Returns
    /// the number of bytes read; `Ok(0)` indicates end-of-file.
    pub fn read_data_object(
        &mut self,
        handle: i32,
        buf: &mut [u8],
    ) -> Result<usize, BatonError> {
        if buf.is_empty() {
            return Ok(0);
        }
        // c_int is the wire type of `len` on rcDataObjRead. Treating an
        // overlong slice as a buffer-size error keeps the C side from
        // ever being handed a negative or wrapped length.
        let len: c_int = buf.len().try_into().map_err(|_| BatonError {
            code: -1,
            message: "read buffer too large for c_int len".to_string(),
        })?;
        let n = unsafe {
            ffi::shim_data_obj_read(self.conn, handle, buf.as_mut_ptr() as *mut c_void, len)
        };
        if n < 0 {
            return Err(BatonError::from_irods(n));
        }
        Ok(n as usize)
    }

    /// Write `buf` in full to `handle`. Returns the number of bytes
    /// accepted by iRODS — typically `buf.len()`. iRODS does not
    /// short-write the way POSIX `write(2)` can, but callers that
    /// stream large payloads should still treat a non-error short
    /// return as a partial write and re-issue the remainder.
    pub fn write_data_object(
        &mut self,
        handle: i32,
        buf: &[u8],
    ) -> Result<usize, BatonError> {
        if buf.is_empty() {
            return Ok(0);
        }
        // Same len-fits-in-c_int guard as read_data_object.
        let len: c_int = buf.len().try_into().map_err(|_| BatonError {
            code: -1,
            message: "write buffer too large for c_int len".to_string(),
        })?;
        let n = unsafe {
            ffi::shim_data_obj_write(self.conn, handle, buf.as_ptr() as *const c_void, len)
        };
        if n < 0 {
            return Err(BatonError::from_irods(n));
        }
        Ok(n as usize)
    }

    /// Close `handle`. The shim's `shim_data_obj_close` no-ops on a
    /// negative handle so callers can use this unconditionally in their
    /// cleanup paths without prior validity checks.
    pub fn close_data_object(&mut self, handle: i32) -> Result<(), BatonError> {
        let status = unsafe { ffi::shim_data_obj_close(self.conn, handle) };
        if status < 0 {
            return Err(BatonError::from_irods(status));
        }
        Ok(())
    }

    /// Compute or retrieve the iRODS-side checksum for `path` and
    /// return it as an owned `String`. Wraps `shim_data_obj_checksum`,
    /// which itself wraps `rcDataObjChksum`.
    ///
    /// The format depends on the server's hash scheme. With the MD5
    /// client default pinned for issue #25, the result is 32 hex
    /// characters. SHA2 servers return a `sha2:` prefix followed by
    /// base64 — `baton-put` strips the prefix before comparing
    /// against its client-side hex digest.
    pub fn checksum_data_object(&mut self, path: &str) -> Result<String, BatonError> {
        let path_c = CString::new(path).map_err(|_| BatonError {
            code: -1,
            message: "path contains interior NUL".to_string(),
        })?;
        let mut buf: [c_char; ffi::SHIM_CHECKSUM_LEN] = [0; ffi::SHIM_CHECKSUM_LEN];
        let status = unsafe {
            ffi::shim_data_obj_checksum(
                self.conn,
                path_c.as_ptr(),
                buf.as_mut_ptr(),
                buf.len() as c_int,
            )
        };
        if status < 0 {
            return Err(BatonError::from_irods(status));
        }
        Ok(unsafe { CStr::from_ptr(buf.as_ptr()) }
            .to_string_lossy()
            .into_owned())
    }

    /// Tear down the current connection and build a fresh one in its
    /// place, re-authenticating via [`Self::login_from_auth_file`].
    ///
    /// Driven from each binary's NDJSON loop via
    /// [`ReconnectingSession`] when the `--connect-time` threshold
    /// elapses; also callable directly for tests or after a
    /// transient network failure.
    ///
    /// On failure the connection pointer is left null (from the
    /// disconnect step), so it's always safe to drop the
    /// [`RodsConnection`] after a failed reconnect.
    pub fn reconnect(&mut self) -> Result<(), BatonError> {
        // Close the current connection. shim_close's return is a status
        // we have nothing useful to do with on the teardown path.
        if !self.conn.is_null() {
            unsafe {
                ffi::shim_close(self.conn);
            }
            self.conn = std::ptr::null_mut();
        }

        // Open a new raw connection. Leaves self.conn null on failure,
        // matching the "always safe to drop" contract above.
        self.conn = Self::open_raw()?;

        // Re-authenticate. The server drops session state on disconnect,
        // so a fresh login is mandatory — the caller doesn't have to
        // remember to call login_from_auth_file again.
        self.login_from_auth_file()
    }

    /// Authenticate the connection using the auth token produced by `iinit`
    /// at `$HOME/.irods/.irodsA`.
    ///
    /// Deliberately avoids `clientLogin`. On iRODS 4.3.x, `clientLogin`
    /// probes the server's auth API table by sending
    /// `AUTHENTICATE_CLIENT_AN` (API 110000) before selecting a scheme,
    /// and not every 4.3.5 server image has that API registered — so
    /// `clientLogin` fails even in environments where `ils` and the other
    /// icommands authenticate fine.
    ///
    /// The flow here instead matches what `iinit`/`ils` do under the
    /// hood, via the C shim:
    ///
    /// 1. `shim_get_password` (`obfGetPw`) reads and deobfuscates the
    ///    `.irodsA` file into a plaintext password buffer.
    /// 2. `shim_login_password` (`clientLoginWithPassword`) runs the
    ///    legacy native auth handshake (`rcAuthRequest` →
    ///    MD5(challenge + password) → `rcAuthResponse`) without
    ///    touching API 110000.
    ///
    /// Only native auth is supported. PAM/GSI/Kerberos and
    /// interactive-password flows are out of scope and would land as
    /// separate methods in whichever session first needs them.
    pub fn login_from_auth_file(&mut self) -> Result<(), BatonError> {
        // MAX_PASSWORD_LEN is 50 in iRODS; sized generously here. The
        // shim sanity-checks buf_len ≥ 64 before delegating to obfGetPw.
        let mut password: [std::os::raw::c_char; 128] = [0; 128];

        // Stack arrays aren't auto-zeroed at function exit, so leaving
        // the plaintext sitting on the stack after we're done with it
        // would extend the window of exposure to anything inspecting
        // process memory (panic unwinders, core dumps, attached
        // debuggers). `write_volatile` keeps the compiler from
        // optimising the writes away. The closure runs unconditionally
        // before each return so an early failure (e.g. a partial
        // obfGetPw write) doesn't leave bytes behind.
        let zero_password = |buf: &mut [std::os::raw::c_char; 128]| {
            for byte in buf.iter_mut() {
                unsafe { std::ptr::write_volatile(byte, 0) };
            }
        };

        let status = unsafe {
            ffi::shim_get_password(password.as_mut_ptr(), password.len() as std::os::raw::c_int)
        };
        if status != 0 {
            zero_password(&mut password);
            return Err(BatonError::from_irods_with_context(
                status,
                "shim_get_password failed (is .irodsA present?)",
            ));
        }

        let status = unsafe { ffi::shim_login_password(self.conn, password.as_ptr()) };
        zero_password(&mut password);

        if status != 0 {
            return Err(BatonError::from_irods(status));
        }

        Ok(())
    }
}

impl Drop for RodsConnection {
    fn drop(&mut self) {
        if !self.conn.is_null() {
            // shim_close returns a status code, but there's nothing
            // useful to do with it here — we're on the destruction path.
            unsafe {
                ffi::shim_close(self.conn);
            }
            self.conn = std::ptr::null_mut();
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn should_reconnect_returns_true_when_threshold_is_zero() {
        // Zero threshold: every check yields a reconnect. Used in
        // integration tests to force-exercise the reconnect path
        // without sleeping.
        let now = Instant::now();
        assert!(should_reconnect(now, Duration::from_secs(0)));
    }

    #[test]
    fn should_reconnect_returns_false_within_threshold() {
        // Just-now reconnect with a typical 600s default — the check
        // should report "no reconnect needed". The baton-rs binaries
        // call this on every NDJSON record, so a false positive here
        // would cause excessive reconnect overhead.
        let now = Instant::now();
        assert!(!should_reconnect(now, Duration::from_secs(600)));
    }

    #[test]
    fn should_reconnect_returns_true_past_threshold() {
        // Simulate a reconnect 700 seconds in the past against a
        // 600s threshold. `Instant::sub` is well-defined for
        // sufficiently small offsets on the platforms we ship to
        // (Linux); panics on overflow, which the tiny offset rules
        // out.
        let earlier = Instant::now() - Duration::from_secs(700);
        assert!(should_reconnect(earlier, Duration::from_secs(600)));
    }

    #[test]
    fn min_connect_time_secs_matches_upstream() {
        // Pin the constant to baton's enforced minimum so a future
        // refactor can't silently drop below it. Upstream rejects
        // anything < 10s in `operations.c:77-83`.
        assert_eq!(MIN_CONNECT_TIME_SECS, 10);
    }

    #[test]
    fn default_connect_time_secs_matches_upstream() {
        // Same pinning rationale for the default — baton's
        // `DEFAULT_MAX_CONNECT_TIME` is 600 (`baton.h:34`).
        assert_eq!(DEFAULT_CONNECT_TIME_SECS, 600);
    }
}
