// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-24

//! Safe wrapper around an iRODS client connection.
//!
//! This module exposes `RodsConnection`, a RAII handle over `rcComm_t *`.
//! Constructing one calls `rcConnect`; dropping one calls `rcDisconnect`. The
//! raw connection pointer is never exposed outside this module — everything
//! a caller can do with a connection goes through safe methods that land in
//! later commits (authentication, reconnect, per-operation calls).
//!
//! Connections are single-threaded by default: the underlying `rcComm_t *` is
//! not safe to share across threads, and the raw-pointer field makes
//! `RodsConnection` `!Send` and `!Sync` automatically.

use std::ffi::CStr;
use std::mem::MaybeUninit;

use crate::error::BatonError;
use crate::ffi;

/// A live connection to an iRODS server.
pub struct RodsConnection {
    conn: *mut ffi::rcComm_t,
}

impl RodsConnection {
    /// Open a connection using the iRODS environment file at
    /// `$HOME/.irods/irods_environment.json`.
    ///
    /// Performs the TCP handshake and iRODS version negotiation only.
    /// Authentication (`clientLogin`) is a separate step handled by a later
    /// commit in this session; calling iRODS APIs that require auth before
    /// then will fail at the server.
    pub fn connect_from_env() -> Result<Self, BatonError> {
        // Load the iRODS environment file.
        let mut env = MaybeUninit::<ffi::rodsEnv>::zeroed();
        let env_status = unsafe { ffi::getRodsEnv(env.as_mut_ptr()) };
        if env_status != 0 {
            return Err(BatonError::from_irods(env_status));
        }
        let env = unsafe { env.assume_init() };

        // Open the connection. reconnFlag=0 here; the explicit reconnect
        // helper arrives in a later commit.
        let mut err_msg = MaybeUninit::<ffi::rErrMsg_t>::zeroed();
        let conn = unsafe {
            ffi::rcConnect(
                env.rodsHost.as_ptr(),
                env.rodsPort,
                env.rodsUserName.as_ptr(),
                env.rodsZone.as_ptr(),
                0,
                err_msg.as_mut_ptr(),
            )
        };

        if conn.is_null() {
            let err_msg = unsafe { err_msg.assume_init() };
            let msg = unsafe { CStr::from_ptr(err_msg.msg.as_ptr()) }
                .to_string_lossy()
                .into_owned();
            return Err(BatonError::from_irods_with_context(err_msg.status, &msg));
        }

        Ok(Self { conn })
    }

    /// Authenticate the connection using the auth token produced by `iinit`
    /// at `$HOME/.irods/.irodsA`.
    ///
    /// Deliberately avoids `clientLogin`. On iRODS 4.3.x, `clientLogin`
    /// probes the server's auth API table by sending
    /// `AUTHENTICATE_CLIENT_AN` (API 110000) before selecting a scheme,
    /// and not every 4.3.5 server image has that API registered — so
    /// `clientLogin` fails even in environments where `ils` and the other
    /// icommands authenticate fine.
    ///
    /// The flow here instead matches what `iinit`/`ils` do under the
    /// hood:
    ///
    /// 1. `obfGetPw` reads and deobfuscates the `.irodsA` file into a
    ///    plaintext password buffer.
    /// 2. `clientLoginWithPassword` runs the legacy native auth handshake
    ///    (`rcAuthRequest` → MD5(challenge + password) → `rcAuthResponse`)
    ///    without touching API 110000.
    ///
    /// Only native auth is supported in Session 2. PAM/GSI/Kerberos and
    /// interactive-password flows are out of scope and would land as
    /// separate methods in whichever session first needs them.
    pub fn login_from_auth_file(&mut self) -> Result<(), BatonError> {
        // MAX_PASSWORD_LEN is 50 in iRODS; sized generously here.
        let mut password: [std::os::raw::c_char; 128] = [0; 128];

        let status = unsafe { ffi::obfGetPw(password.as_mut_ptr()) };
        if status != 0 {
            return Err(BatonError::from_irods_with_context(
                status,
                "obfGetPw failed (is .irodsA present?)",
            ));
        }

        let status = unsafe {
            ffi::clientLoginWithPassword(self.conn, password.as_mut_ptr())
        };
        if status != 0 {
            return Err(BatonError::from_irods(status));
        }

        Ok(())
    }
}

impl Drop for RodsConnection {
    fn drop(&mut self) {
        if !self.conn.is_null() {
            // rcDisconnect returns a status code, but there's nothing useful
            // to do with it here — we're on the destruction path.
            unsafe {
                ffi::rcDisconnect(self.conn);
            }
            self.conn = std::ptr::null_mut();
        }
    }
}
