// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! Error types for baton-rs.
//!
//! `BatonError` matches the JSON shape baton produces inside an `"error"`
//! field when an operation fails for a particular input item, e.g.
//! ```json
//! {"collection": "/foo", "data_object": "bar.txt",
//!  "error": {"code": -813000, "message": "CAT_NO_ROWS_FOUND"}}
//! ```

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// A baton-style error carrying an iRODS numeric code and a message.
///
/// iRODS error codes are conventionally negative integers. The JSON shape
/// matches baton exactly so in-band error annotation on result items works
/// without any custom conversion.
#[derive(Debug, Clone, PartialEq, Eq, Error, Serialize, Deserialize)]
#[error("iRODS error {code}: {message}")]
pub struct BatonError {
    pub code: i32,
    pub message: String,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn baton_error_round_trip() {
        let json = r#"{"code":-813000,"message":"CAT_NO_ROWS_FOUND"}"#;
        let e: BatonError = serde_json::from_str(json).unwrap();
        assert_eq!(e.code, -813000);
        assert_eq!(e.message, "CAT_NO_ROWS_FOUND");
        assert_eq!(serde_json::to_string(&e).unwrap(), json);
    }

    #[test]
    fn baton_error_display() {
        let e = BatonError { code: -813000, message: "CAT_NO_ROWS_FOUND".to_string() };
        assert_eq!(e.to_string(), "iRODS error -813000: CAT_NO_ROWS_FOUND");
    }
}
