// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-24

//! Error types for baton-rs.
//!
//! `BatonError` matches the JSON shape baton produces inside an `"error"`
//! field when an operation fails for a particular input item, e.g.
//! ```json
//! {"collection": "/foo", "data_object": "bar.txt",
//!  "error": {"code": -813000, "message": "CAT_NO_ROWS_FOUND"}}
//! ```

use std::ffi::CStr;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::ffi;

/// A baton-style error carrying an iRODS numeric code and a message.
///
/// iRODS error codes are conventionally negative integers. The JSON shape
/// matches baton exactly so in-band error annotation on result items works
/// without any custom conversion.
#[derive(Debug, Clone, PartialEq, Eq, Error, Serialize, Deserialize)]
#[error("iRODS error {code}: {message}")]
pub struct BatonError {
    pub code: i32,
    pub message: String,
}

impl BatonError {
    /// Build a `BatonError` from an iRODS status code, resolving the
    /// symbolic error name via iRODS's own `rodsErrorName`.
    ///
    /// For example, `BatonError::from_irods(-305111)` yields a message of
    /// `"USER_SOCK_CONNECT_ERR"`. Unknown codes return the literal
    /// `"UNKNOWN_ERROR"` — iRODS returns that string itself rather than a
    /// null pointer in that case, so this maps cleanly 1:1.
    pub fn from_irods(code: i32) -> Self {
        Self {
            code,
            message: irods_error_name(code),
        }
    }

    /// Build a `BatonError` enriched with a server-supplied description —
    /// typically the `msg` field of an `rErrMsg_t` or the text iRODS wrote
    /// to stderr for this status. Empty or whitespace-only `context` falls
    /// back to the plain error name.
    pub fn from_irods_with_context(code: i32, context: &str) -> Self {
        let name = irods_error_name(code);
        let ctx = context.trim();
        let message = if ctx.is_empty() {
            name
        } else {
            format!("{}: {}", name, ctx)
        };
        Self { code, message }
    }
}

/// Look up the symbolic name for an iRODS status code using the iRODS
/// runtime's `rodsErrorName` helper.
fn irods_error_name(code: i32) -> String {
    // rodsErrorName returns a pointer to a static string owned by iRODS.
    // The second arg (sub-error name) is optional; pass null and ignore.
    let name_ptr = unsafe { ffi::rodsErrorName(code, std::ptr::null_mut()) };
    if name_ptr.is_null() {
        return format!("UNKNOWN_ERROR({})", code);
    }
    unsafe { CStr::from_ptr(name_ptr) }
        .to_string_lossy()
        .into_owned()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn baton_error_round_trip() {
        let json = r#"{"code":-813000,"message":"CAT_NO_ROWS_FOUND"}"#;
        let e: BatonError = serde_json::from_str(json).unwrap();
        assert_eq!(e.code, -813000);
        assert_eq!(e.message, "CAT_NO_ROWS_FOUND");
        assert_eq!(serde_json::to_string(&e).unwrap(), json);
    }

    #[test]
    fn baton_error_display() {
        let e = BatonError { code: -813000, message: "CAT_NO_ROWS_FOUND".to_string() };
        assert_eq!(e.to_string(), "iRODS error -813000: CAT_NO_ROWS_FOUND");
    }

    #[test]
    fn from_irods_resolves_known_names() {
        // A handful of stable iRODS codes that we've already hit in
        // connection-layer testing. If iRODS renames any of these we'd
        // want to know — hence pinning them explicitly.
        for (code, expected) in [
            (-305111, "USER_SOCK_CONNECT_ERR"),
            (-827000, "CAT_INVALID_USER"),
            (-813000, "CAT_NO_ROWS_FOUND"),
        ] {
            let e = BatonError::from_irods(code);
            assert_eq!(e.code, code, "code preserved");
            assert_eq!(e.message, expected, "name resolved for code {}", code);
        }
    }

    #[test]
    fn from_irods_with_context_formats_name_and_context() {
        let e = BatonError::from_irods_with_context(-305111, "connection refused");
        assert_eq!(e.code, -305111);
        assert_eq!(e.message, "USER_SOCK_CONNECT_ERR: connection refused");
    }

    #[test]
    fn from_irods_with_context_ignores_empty_context() {
        let e = BatonError::from_irods_with_context(-305111, "   ");
        assert_eq!(e.message, "USER_SOCK_CONNECT_ERR");
    }
}
