// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-09

//! Error types for baton-rs.
//!
//! `BatonError` matches the JSON shape baton produces inside an `"error"`
//! field when an operation fails for a particular input item, e.g.
//! ```json
//! {"collection": "/foo", "data_object": "bar.txt",
//!  "error": {"code": -813000, "message": "CAT_NO_ROWS_FOUND"}}
//! ```

use std::ffi::CStr;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::ffi;

/// A baton-style error carrying an iRODS numeric code and a message.
///
/// iRODS error codes are conventionally negative integers. The JSON shape
/// matches baton exactly so in-band error annotation on result items works
/// without any custom conversion.
#[derive(Debug, Clone, PartialEq, Eq, Error, Serialize, Deserialize)]
#[error("iRODS error {code}: {message}")]
pub struct BatonError {
    pub code: i32,
    pub message: String,
}

impl BatonError {
    /// Build a `BatonError` from an iRODS status code, resolving the
    /// symbolic error name via iRODS's own `rodsErrorName` and
    /// (where available) a human-readable phrase describing the
    /// failure.
    ///
    /// For example, `BatonError::from_irods(-310000)` yields the
    /// message `"USER_FILE_DOES_NOT_EXIST: path does not exist or
    /// user lacks access permission"`. The trailing phrase is what
    /// downstream consumers like partisan match against when they
    /// expect a particular failure shape (`pytest.raises(RodsError,
    /// match="does not exist")` —
    /// `partisan/src/partisan/irods.py`). Codes without a known
    /// phrase fall back to the bare symbolic name. See #57
    /// (Cluster A) for the partisan-side regex set this lookup
    /// satisfies.
    pub fn from_irods(code: i32) -> Self {
        Self {
            code,
            message: irods_error_message(code),
        }
    }

    /// Build a `BatonError` enriched with a server-supplied description —
    /// typically the `msg` field of an `rErrMsg_t` or the text iRODS wrote
    /// to stderr for this status. Empty or whitespace-only `context` falls
    /// back to the plain error name + descriptive phrase.
    pub fn from_irods_with_context(code: i32, context: &str) -> Self {
        let base = irods_error_message(code);
        let ctx = context.trim();
        let message = if ctx.is_empty() {
            base
        } else {
            format!("{}: {}", base, ctx)
        };
        Self { code, message }
    }
}

/// Look up the symbolic name for an iRODS status code via the C shim.
///
/// `shim_error_name` wraps iRODS's `rodsErrorName` and hands back a
/// pointer to a process-lifetime static string (no caller free
/// required). Returns a synthetic placeholder for codes iRODS doesn't
/// recognise.
fn irods_error_name(code: i32) -> String {
    let name_ptr = unsafe { ffi::shim_error_name(code) };
    if name_ptr.is_null() {
        return format!("UNKNOWN_ERROR({})", code);
    }
    unsafe { CStr::from_ptr(name_ptr) }
        .to_string_lossy()
        .into_owned()
}

/// Build the message string for an iRODS code: the symbolic name
/// (always) followed by a human-readable phrase (when known).
///
/// Wraps [`irods_error_name`] with the lookup in
/// [`descriptive_phrase`]. Used by [`BatonError::from_irods`] and
/// [`BatonError::from_irods_with_context`].
fn irods_error_message(code: i32) -> String {
    let name = irods_error_name(code);
    match descriptive_phrase(code) {
        Some(phrase) => format!("{}: {}", name, phrase),
        None => name,
    }
}

/// Map well-known iRODS error codes to short human-readable
/// phrases. Conservative — only entries we have a concrete reason
/// to add (i.e. a downstream consumer's regex demands them, or
/// an operator-facing log line is unhelpful without prose).
///
/// Phrasing follows upstream iRODS / baton conventions where they
/// exist; otherwise it's a plain English summary of the iRODS
/// header description for the code.
fn descriptive_phrase(code: i32) -> Option<&'static str> {
    match code {
        // -310000 USER_FILE_DOES_NOT_EXIST — partisan
        // `pytest.raises(RodsError, match="does not exist")`.
        -310000 => Some("path does not exist or user lacks access permission"),
        // -407000 CHECK_VERIFICATION_RESULTS — partisan
        // `pytest.raises(RodsError, match="checksum")` on
        // `verify_checksum_bad`.
        -407000 => Some("checksum verification failed"),
        // -809000 CATALOG_ALREADY_HAS_ITEM_BY_THAT_NAME — used by
        // mkdir's "create collection" failure path. The mkdir
        // module also wraps the error with operation context;
        // this phrase makes the bare-code form recognisable too.
        -809000 => Some("catalog already has item by that name"),
        // -814000 CAT_UNKNOWN_COLLECTION — surfaces in mkdir
        // (parent missing) and elsewhere. mkdir module wraps
        // with operation context; this phrase keeps the
        // bare-code form recognisable.
        -814000 => Some("unknown collection"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn baton_error_round_trip() {
        let json = r#"{"code":-813000,"message":"CAT_NO_ROWS_FOUND"}"#;
        let e: BatonError = serde_json::from_str(json).unwrap();
        assert_eq!(e.code, -813000);
        assert_eq!(e.message, "CAT_NO_ROWS_FOUND");
        assert_eq!(serde_json::to_string(&e).unwrap(), json);
    }

    #[test]
    fn baton_error_display() {
        let e = BatonError { code: -813000, message: "CAT_NO_ROWS_FOUND".to_string() };
        assert_eq!(e.to_string(), "iRODS error -813000: CAT_NO_ROWS_FOUND");
    }

    #[test]
    fn from_irods_resolves_observed_code() {
        // -305111 = USER_SOCK_CONNECT_ERR. Verified end-to-end during
        // connection-layer debugging (a real server-refused TCP connect
        // returned this code via rErrMsg_t).
        let e = BatonError::from_irods(-305111);
        assert_eq!(e.code, -305111, "code preserved");
        assert_eq!(e.message, "USER_SOCK_CONNECT_ERR", "name resolved");
    }

    #[test]
    fn from_irods_returns_non_empty_for_unknown_code() {
        // 42 is not an iRODS error code. rodsErrorName returns a placeholder
        // string ("UNKNOWN_ERROR" or similar depending on version); we only
        // assert the message is populated and the code is preserved.
        let e = BatonError::from_irods(42);
        assert_eq!(e.code, 42);
        assert!(!e.message.is_empty(), "message should not be empty");
    }

    #[test]
    fn from_irods_with_context_formats_name_and_context() {
        let e = BatonError::from_irods_with_context(-305111, "connection refused");
        assert_eq!(e.code, -305111);
        assert_eq!(e.message, "USER_SOCK_CONNECT_ERR: connection refused");
    }

    #[test]
    fn from_irods_with_context_ignores_empty_context() {
        let e = BatonError::from_irods_with_context(-305111, "   ");
        assert_eq!(e.message, "USER_SOCK_CONNECT_ERR");
    }

    #[test]
    fn from_irods_appends_phrase_for_known_code_does_not_exist() {
        // -310000 USER_FILE_DOES_NOT_EXIST. Phrase contains "does
        // not exist" so partisan's `match="does not exist"`
        // (`tests/test_irods.py::test_list_collection`,
        // `test_list_data_object`) holds.
        let e = BatonError::from_irods(-310000);
        assert_eq!(e.code, -310000);
        assert!(
            e.message.contains("USER_FILE_DOES_NOT_EXIST"),
            "should keep symbolic name: {}",
            e.message
        );
        assert!(
            e.message.contains("does not exist"),
            "should include phrase for partisan regex: {}",
            e.message
        );
    }

    #[test]
    fn from_irods_appends_phrase_for_known_code_checksum() {
        // -407000 CHECK_VERIFICATION_RESULTS. Phrase contains
        // "checksum" so partisan's `match="checksum"`
        // (`test_verify_checksum_bad`) holds.
        let e = BatonError::from_irods(-407000);
        assert_eq!(e.code, -407000);
        assert!(
            e.message.contains("checksum"),
            "should include phrase for partisan regex: {}",
            e.message
        );
    }

    #[test]
    fn from_irods_falls_back_to_name_only_for_unknown_codes() {
        // No phrase mapped for -305111 USER_SOCK_CONNECT_ERR;
        // message stays as the bare symbolic name. Pins that we
        // don't accidentally append phrases for codes outside the
        // explicit lookup.
        let e = BatonError::from_irods(-305111);
        assert_eq!(e.message, "USER_SOCK_CONNECT_ERR");
    }

    #[test]
    fn from_irods_with_context_combines_phrase_and_context() {
        // Both phrase (from code lookup) and operation context
        // (from caller) appear in the message — operation modules
        // can layer their own prefix on top of the code phrase.
        let e = BatonError::from_irods_with_context(-310000, "list /foo");
        assert!(
            e.message.contains("USER_FILE_DOES_NOT_EXIST"),
            "name present: {}",
            e.message
        );
        assert!(
            e.message.contains("does not exist"),
            "phrase present: {}",
            e.message
        );
        assert!(
            e.message.contains("list /foo"),
            "context present: {}",
            e.message
        );
    }
}
