// Generated by:    Claude Opus 4.7 (1M context)
// Generation date: 2026-04-24

//! baton-rs — a Rust reimplementation of the baton iRODS client.
//!
//! See `PLAN.md` at the repository root for the multi-session implementation plan.

pub mod types;

pub use types::*;
