// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-04-24

//! JSON data types for the baton-rs API.
//!
//! All types round-trip against the baton 6.0.0 JSON schema
//! (<https://wtsi-npg.github.io/baton/>).

use serde::{Deserialize, Serialize};

/// An iRODS path — serialised as a plain JSON string.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct IrodsPath(pub String);

impl IrodsPath {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for IrodsPath {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl From<String> for IrodsPath {
    fn from(s: String) -> Self {
        Self(s)
    }
}

/// A single attribute-value-unit metadata triple.
///
/// Accepts baton's short form (`a` / `v` / `u`) on deserialisation; always
/// serialises the long form (`attribute` / `value` / `units`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Avu {
    #[serde(alias = "a")]
    pub attribute: String,

    #[serde(alias = "v")]
    pub value: String,

    #[serde(alias = "u", skip_serializing_if = "Option::is_none", default)]
    pub units: Option<String>,
}

/// iRODS access level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AclLevel {
    Null,
    Read,
    Write,
    Own,
}

/// A single access control entry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Acl {
    pub owner: String,
    pub level: AclLevel,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub zone: Option<String>,
}

/// A single replica of a data object.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Replicate {
    pub checksum: String,
    pub location: String,
    pub resource: String,
    pub number: u32,
    pub valid: bool,
}

/// A timestamp for a data object or replicate.
///
/// Each entry carries either `created` or `modified` (not both in practice,
/// though the schema permits it). `replicate` identifies the replica when the
/// timestamp is replica-specific.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Timestamp {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub created: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub modified: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub replicate: Option<u32>,
}

/// Comparison operator used in baton metadata queries.
///
/// The `n`-prefixed variants are the numeric-comparison counterparts; baton
/// uses these to force numeric comparison for values that are strings in the
/// iRODS catalogue but should compare numerically.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "=")]
    Equals,
    #[serde(rename = "like")]
    Like,
    #[serde(rename = "not like")]
    NotLike,
    #[serde(rename = "in")]
    In,
    #[serde(rename = ">")]
    GreaterThan,
    #[serde(rename = "n>")]
    NumericGreaterThan,
    #[serde(rename = "<")]
    LessThan,
    #[serde(rename = "n<")]
    NumericLessThan,
    #[serde(rename = ">=")]
    GreaterThanOrEqual,
    #[serde(rename = "n>=")]
    NumericGreaterThanOrEqual,
    #[serde(rename = "<=")]
    LessThanOrEqual,
    #[serde(rename = "n<=")]
    NumericLessThanOrEqual,
}

/// A data object in iRODS (a file).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DataObject {
    pub collection: String,
    pub data_object: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub size: Option<u64>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub checksum: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub avus: Option<Vec<Avu>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub access: Option<Vec<Acl>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub replicates: Option<Vec<Replicate>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub timestamps: Option<Vec<Timestamp>>,
}

/// A collection in iRODS (a directory).
///
/// `contents` (the directory listing populated by `--contents`) arrives in a
/// later commit alongside the mixed-item enum it needs.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Collection {
    pub collection: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub avus: Option<Vec<Avu>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub access: Option<Vec<Acl>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub timestamps: Option<Vec<Timestamp>>,
}

/// A `baton-list` target — either a data object or a collection, distinguished
/// on the wire by whether `data_object` is present.
///
/// Untagged serde: `{"collection":"/x","data_object":"y"}` matches
/// `DataObject` (requires `data_object`); `{"collection":"/x"}` falls through
/// to `Collection`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Target {
    DataObject(DataObject),
    Collection(Collection),
}

impl Target {
    /// The iRODS absolute path — what `rcObjStat` wants as input.
    pub fn path(&self) -> String {
        match self {
            Target::Collection(c) => c.collection.clone(),
            Target::DataObject(d) => {
                if d.collection.ends_with('/') {
                    format!("{}{}", d.collection, d.data_object)
                } else {
                    format!("{}/{}", d.collection, d.data_object)
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn irods_path_round_trip() {
        let json = r#""/testZone/home/irods/foo.txt""#;
        let p: IrodsPath = serde_json::from_str(json).unwrap();
        assert_eq!(p.as_str(), "/testZone/home/irods/foo.txt");
        assert_eq!(serde_json::to_string(&p).unwrap(), json);
    }

    #[test]
    fn irods_path_constructors() {
        assert_eq!(IrodsPath::new("/a/b").as_str(), "/a/b");
        assert_eq!(IrodsPath::from("/a/b").as_str(), "/a/b");
        assert_eq!(IrodsPath::from(String::from("/a/b")).as_str(), "/a/b");
    }

    #[test]
    fn data_object_minimal_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt"}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.collection, "/testZone/home/irods");
        assert_eq!(d.data_object, "foo.txt");
        assert_eq!(d.size, None);
        assert_eq!(d.checksum, None);
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn data_object_with_size_and_checksum_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt","size":1024,"checksum":"d41d8cd98f00b204e9800998ecf8427e"}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.size, Some(1024));
        assert_eq!(d.checksum.as_deref(), Some("d41d8cd98f00b204e9800998ecf8427e"));
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn collection_minimal_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods"}"#;
        let c: Collection = serde_json::from_str(json).unwrap();
        assert_eq!(c.collection, "/testZone/home/irods");
        assert_eq!(serde_json::to_string(&c).unwrap(), json);
    }

    // --- Avu ---

    #[test]
    fn avu_long_form_round_trip() {
        let json = r#"{"attribute":"sample","value":"12345","units":"id"}"#;
        let a: Avu = serde_json::from_str(json).unwrap();
        assert_eq!(a.attribute, "sample");
        assert_eq!(a.value, "12345");
        assert_eq!(a.units.as_deref(), Some("id"));
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    #[test]
    fn avu_short_form_deserialises_and_emits_long_form() {
        let short = r#"{"a":"sample","v":"12345","u":"id"}"#;
        let long = r#"{"attribute":"sample","value":"12345","units":"id"}"#;
        let a: Avu = serde_json::from_str(short).unwrap();
        assert_eq!(a.attribute, "sample");
        assert_eq!(a.value, "12345");
        assert_eq!(a.units.as_deref(), Some("id"));
        assert_eq!(serde_json::to_string(&a).unwrap(), long);
    }

    #[test]
    fn avu_without_units() {
        let json = r#"{"attribute":"sample","value":"12345"}"#;
        let a: Avu = serde_json::from_str(json).unwrap();
        assert_eq!(a.units, None);
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    // --- Acl ---

    #[test]
    fn acl_with_zone_round_trip() {
        let json = r#"{"owner":"irods","level":"own","zone":"testZone"}"#;
        let a: Acl = serde_json::from_str(json).unwrap();
        assert_eq!(a.owner, "irods");
        assert_eq!(a.level, AclLevel::Own);
        assert_eq!(a.zone.as_deref(), Some("testZone"));
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    #[test]
    fn acl_without_zone_round_trip() {
        let json = r#"{"owner":"irods","level":"read"}"#;
        let a: Acl = serde_json::from_str(json).unwrap();
        assert_eq!(a.level, AclLevel::Read);
        assert_eq!(a.zone, None);
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    #[test]
    fn acl_all_levels_round_trip() {
        for (literal, level) in [
            (r#""null""#, AclLevel::Null),
            (r#""read""#, AclLevel::Read),
            (r#""write""#, AclLevel::Write),
            (r#""own""#, AclLevel::Own),
        ] {
            let parsed: AclLevel = serde_json::from_str(literal).unwrap();
            assert_eq!(parsed, level);
            assert_eq!(serde_json::to_string(&parsed).unwrap(), literal);
        }
    }

    // --- Replicate ---

    #[test]
    fn replicate_round_trip() {
        let json = r#"{"checksum":"d41d8cd98f00b204e9800998ecf8427e","location":"host","resource":"demoResc","number":0,"valid":true}"#;
        let r: Replicate = serde_json::from_str(json).unwrap();
        assert_eq!(r.checksum, "d41d8cd98f00b204e9800998ecf8427e");
        assert_eq!(r.location, "host");
        assert_eq!(r.resource, "demoResc");
        assert_eq!(r.number, 0);
        assert!(r.valid);
        assert_eq!(serde_json::to_string(&r).unwrap(), json);
    }

    // --- Timestamp ---

    #[test]
    fn timestamp_created_round_trip() {
        let json = r#"{"created":"2024-01-01T00:00:00"}"#;
        let t: Timestamp = serde_json::from_str(json).unwrap();
        assert_eq!(t.created.as_deref(), Some("2024-01-01T00:00:00"));
        assert_eq!(t.modified, None);
        assert_eq!(t.replicate, None);
        assert_eq!(serde_json::to_string(&t).unwrap(), json);
    }

    #[test]
    fn timestamp_modified_round_trip() {
        let json = r#"{"modified":"2024-01-02T12:34:56"}"#;
        let t: Timestamp = serde_json::from_str(json).unwrap();
        assert_eq!(t.modified.as_deref(), Some("2024-01-02T12:34:56"));
        assert_eq!(serde_json::to_string(&t).unwrap(), json);
    }

    #[test]
    fn timestamp_with_replicate_round_trip() {
        let json = r#"{"created":"2024-01-01T00:00:00","replicate":0}"#;
        let t: Timestamp = serde_json::from_str(json).unwrap();
        assert_eq!(t.replicate, Some(0));
        assert_eq!(serde_json::to_string(&t).unwrap(), json);
    }

    // --- Extended DataObject / Collection ---

    #[test]
    fn data_object_with_avus_and_access_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt","avus":[{"attribute":"sample","value":"12345"}],"access":[{"owner":"irods","level":"own","zone":"testZone"}]}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.avus.as_ref().map(Vec::len), Some(1));
        assert_eq!(d.access.as_ref().map(Vec::len), Some(1));
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn collection_with_avus_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","avus":[{"attribute":"project","value":"baton-rs"}]}"#;
        let c: Collection = serde_json::from_str(json).unwrap();
        assert_eq!(c.avus.as_ref().map(Vec::len), Some(1));
        assert_eq!(serde_json::to_string(&c).unwrap(), json);
    }

    // --- Target ---

    #[test]
    fn target_deserialises_as_data_object_when_data_object_present() {
        let json = r#"{"collection":"/z/home/u","data_object":"foo.txt"}"#;
        let t: Target = serde_json::from_str(json).unwrap();
        match t {
            Target::DataObject(d) => {
                assert_eq!(d.collection, "/z/home/u");
                assert_eq!(d.data_object, "foo.txt");
            }
            _ => panic!("expected DataObject"),
        }
    }

    #[test]
    fn target_deserialises_as_collection_without_data_object() {
        let json = r#"{"collection":"/z/home/u"}"#;
        let t: Target = serde_json::from_str(json).unwrap();
        match t {
            Target::Collection(c) => assert_eq!(c.collection, "/z/home/u"),
            _ => panic!("expected Collection"),
        }
    }

    #[test]
    fn target_path_joins_collection_and_data_object() {
        let d = DataObject {
            collection: "/z/home/u".to_string(),
            data_object: "foo.txt".to_string(),
            size: None,
            checksum: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
        };
        assert_eq!(Target::DataObject(d).path(), "/z/home/u/foo.txt");
    }

    #[test]
    fn target_path_handles_trailing_slash_on_collection() {
        let d = DataObject {
            collection: "/z/home/u/".to_string(),
            data_object: "foo.txt".to_string(),
            size: None,
            checksum: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
        };
        assert_eq!(Target::DataObject(d).path(), "/z/home/u/foo.txt");
    }

    #[test]
    fn target_path_for_collection_is_collection() {
        let c = Collection {
            collection: "/z/home/u".to_string(),
            avus: None,
            access: None,
            timestamps: None,
        };
        assert_eq!(Target::Collection(c).path(), "/z/home/u");
    }

    // --- Operator ---

    #[test]
    fn operator_round_trip_all_variants() {
        for (literal, op) in [
            (r#""=""#, Operator::Equals),
            (r#""like""#, Operator::Like),
            (r#""not like""#, Operator::NotLike),
            (r#""in""#, Operator::In),
            (r#"">""#, Operator::GreaterThan),
            (r#""n>""#, Operator::NumericGreaterThan),
            (r#""<""#, Operator::LessThan),
            (r#""n<""#, Operator::NumericLessThan),
            (r#"">=""#, Operator::GreaterThanOrEqual),
            (r#""n>=""#, Operator::NumericGreaterThanOrEqual),
            (r#""<=""#, Operator::LessThanOrEqual),
            (r#""n<=""#, Operator::NumericLessThanOrEqual),
        ] {
            let parsed: Operator = serde_json::from_str(literal).unwrap();
            assert_eq!(parsed, op);
            assert_eq!(serde_json::to_string(&parsed).unwrap(), literal);
        }
    }
}
