// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-04-24
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-06

//! JSON data types for the baton-rs API.
//!
//! All types round-trip against the baton 6.0.0 JSON schema
//! (<https://wtsi-npg.github.io/baton/>).

use serde::de::{self, MapAccess, Visitor};
use serde::{Deserialize, Deserializer, Serialize};
use std::fmt;

use crate::error::BatonError;

/// An iRODS path — serialised as a plain JSON string.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct IrodsPath(pub String);

impl IrodsPath {
    pub fn new(s: impl Into<String>) -> Self {
        Self(s.into())
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<&str> for IrodsPath {
    fn from(s: &str) -> Self {
        Self(s.to_string())
    }
}

impl From<String> for IrodsPath {
    fn from(s: String) -> Self {
        Self(s)
    }
}

/// A single attribute-value-unit metadata triple.
///
/// Accepts baton's short form (`a` / `v` / `u`) on deserialisation; always
/// serialises the long form (`attribute` / `value` / `units`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Avu {
    #[serde(alias = "a")]
    pub attribute: String,

    #[serde(alias = "v")]
    pub value: String,

    #[serde(alias = "u", skip_serializing_if = "Option::is_none", default)]
    pub units: Option<String>,
}

/// iRODS access level.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum AclLevel {
    Null,
    Read,
    Write,
    Own,
}

impl AclLevel {
    /// The bare lowercase string iRODS accepts as
    /// `modAccessControlInp_t.accessLevel`. Identical set to upstream
    /// baton (`baton/src/query.h:52-55`); anything outside these four
    /// surfaces as `CAT_INVALID_ARGUMENT` from the server.
    ///
    /// Distinct from the serde representation: although they happen
    /// to share the same four lowercase forms, going through
    /// `serde_json::to_string` would JSON-quote the result. This
    /// method returns the bare string the iRODS C API wants.
    pub fn as_irods_str(&self) -> &'static str {
        match self {
            AclLevel::Null => "null",
            AclLevel::Read => "read",
            AclLevel::Write => "write",
            AclLevel::Own => "own",
        }
    }
}

/// A single access control entry.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Acl {
    pub owner: String,
    pub level: AclLevel,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub zone: Option<String>,
}

/// A single replica of a data object.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Replicate {
    pub checksum: String,
    pub location: String,
    pub resource: String,
    pub number: u32,
    pub valid: bool,
}

/// A timestamp for a data object or replicate.
///
/// Each entry carries either `created` or `modified` (not both in practice,
/// though the schema permits it). `replicate` identifies the replica when the
/// timestamp is replica-specific.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Timestamp {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub created: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub modified: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub replicate: Option<u32>,
}

/// Comparison operator used in baton metadata queries.
///
/// The `n`-prefixed variants are the numeric-comparison counterparts; baton
/// uses these to force numeric comparison for values that are strings in the
/// iRODS catalogue but should compare numerically.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub enum Operator {
    #[default]
    #[serde(rename = "=")]
    Equals,
    #[serde(rename = "like")]
    Like,
    #[serde(rename = "not like")]
    NotLike,
    #[serde(rename = "in")]
    In,
    #[serde(rename = ">")]
    GreaterThan,
    #[serde(rename = "n>")]
    NumericGreaterThan,
    #[serde(rename = "<")]
    LessThan,
    #[serde(rename = "n<")]
    NumericLessThan,
    #[serde(rename = ">=")]
    GreaterThanOrEqual,
    #[serde(rename = "n>=")]
    NumericGreaterThanOrEqual,
    #[serde(rename = "<=")]
    LessThanOrEqual,
    #[serde(rename = "n<=")]
    NumericLessThanOrEqual,
}

/// A data object in iRODS (a file).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DataObject {
    pub collection: String,
    pub data_object: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub size: Option<u64>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub checksum: Option<String>,

    /// Inline data-object content, base64-encoded. Populated by
    /// `baton-get` in inline mode (no `--save`). JSON is text-only, so
    /// arbitrary bytes need an encoding; base64 matches upstream baton.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub data: Option<String>,

    /// Local destination directory for `baton-get --save`. Bytes go to
    /// `<directory>/<data_object>` on disk rather than into the JSON
    /// output's `data` field. Echoed on output records when present on
    /// input — matches baton's per-record save-destination convention.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub directory: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub avus: Option<Vec<Avu>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub access: Option<Vec<Acl>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub replicates: Option<Vec<Replicate>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub timestamps: Option<Vec<Timestamp>>,

    /// Populated by in-band error annotation when an operation fails for
    /// this specific input item.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub error: Option<BatonError>,
}

/// A collection in iRODS (a directory).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Collection {
    pub collection: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub avus: Option<Vec<Avu>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub access: Option<Vec<Acl>>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub timestamps: Option<Vec<Timestamp>>,

    /// Direct children of this collection — populated by `--contents`.
    /// Mixed list of data objects and sub-collections; each item carries
    /// its own typed identity via the `Target` enum.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub contents: Option<Vec<Item>>,

    /// Populated by in-band error annotation when an operation fails for
    /// this specific input item.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub error: Option<BatonError>,
}

/// A `baton-list` target — either a data object or a collection, distinguished
/// on the wire by whether `data_object` is present.
///
/// Untagged serde: `{"collection":"/x","data_object":"y"}` matches
/// `DataObject` (requires `data_object`); `{"collection":"/x"}` falls through
/// to `Collection`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Target {
    DataObject(DataObject),
    Collection(Collection),
}

/// One element of a collection's `contents` list.
///
/// Same on-the-wire shape as [`Target`] (data object vs sub-collection
/// distinguished by presence of `data_object` on the JSON object), so we
/// alias rather than duplicate the enum. `Vec<Item>` and `Vec<Target>`
/// interoperate freely.
pub type Item = Target;

impl Target {
    /// The iRODS absolute path — what `rcObjStat` wants as input.
    pub fn path(&self) -> String {
        match self {
            Target::Collection(c) => c.collection.clone(),
            Target::DataObject(d) => {
                if d.collection.ends_with('/') {
                    format!("{}{}", d.collection, d.data_object)
                } else {
                    format!("{}/{}", d.collection, d.data_object)
                }
            }
        }
    }

    /// Annotate this target with an error. Used by the in-band error flow
    /// to emit `{"collection": "…", "data_object": "…", "error": {…}}` on
    /// a per-input failure instead of aborting the stream.
    pub fn set_error(&mut self, err: BatonError) {
        match self {
            Target::DataObject(d) => d.error = Some(err),
            Target::Collection(c) => c.error = Some(err),
        }
    }
}

/// One operation `baton-metamod` can perform per input line.
///
/// Carried inline on each [`MetamodInput`] so a single NDJSON stream
/// can mix adds and removes — matches upstream baton's behaviour.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum MetamodOperation {
    Add,
    Rm,
}

/// One input record for `baton-metamod`.
///
/// JSON shape:
/// ```text
/// {
///   "collection": "/zone/coll",
///   "data_object": "foo.txt",        // optional; collections omit it
///   "operation":   "add",            // or "rm"
///   "avus":        [{"attribute": "a", "value": "v", "units": "u"}],
///   "error":       {...}             // populated by in-band failure
/// }
/// ```
///
/// Sibling of [`Target`] rather than a wrapping enum: `operation` and
/// `avus` need to live at the top level next to `collection` /
/// `data_object`, and flattening `Target` (which is itself an untagged
/// enum) into a struct fights serde's resolution rules. A focused
/// struct with a [`Self::target`] accessor is cheaper.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MetamodInput {
    pub collection: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub data_object: Option<String>,

    pub operation: MetamodOperation,

    /// AVUs to add or remove. baton accepts an empty list (no-op for
    /// the input); we mirror that — a record with an empty `avus`
    /// array succeeds without making any catalog calls.
    #[serde(default)]
    pub avus: Vec<Avu>,

    /// Populated by in-band error annotation when the operation fails
    /// for this specific input. Same pattern as `DataObject.error` /
    /// `Collection.error`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub error: Option<BatonError>,
}

impl MetamodInput {
    /// Project this input into the [`Target`] form the connection layer
    /// understands. The resulting `DataObject` / `Collection` carries
    /// only path identity — none of the metadata fields are populated.
    pub fn target(&self) -> Target {
        match &self.data_object {
            Some(name) => Target::DataObject(DataObject {
                collection: self.collection.clone(),
                data_object: name.clone(),
                size: None,
                checksum: None,
                data: None,
                directory: None,
                avus: None,
                access: None,
                replicates: None,
                timestamps: None,
                error: None,
            }),
            None => Target::Collection(Collection {
                collection: self.collection.clone(),
                avus: None,
                access: None,
                timestamps: None,
                contents: None,
                error: None,
            }),
        }
    }
}

/// One AVU criterion for a `baton-metaquery` search.
///
/// `operator` defaults to [`Operator::Equals`] when omitted from the
/// JSON input — matches baton's behaviour and keeps simple inputs
/// concise. Pair this with the catalog's `META_*_ATTR_VALUE` column.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AvuQuery {
    pub attribute: String,
    pub value: String,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub units: Option<String>,

    #[serde(default)]
    pub operator: Operator,
}

/// One timestamp criterion for a `baton-metaquery` search.
///
/// Either `created` or `modified` is provided (mirroring [`Timestamp`]'s
/// emission shape) — both fields being `None` is meaningless and
/// callers shouldn't construct that, but we don't hard-fail on it
/// either; the query layer will simply not add a WHERE condition.
/// Operator is typically a comparison (`>`, `>=`, `<`, `<=`) for range
/// queries; defaults to `=` for an exact-match.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TimestampQuery {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub created: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub modified: Option<String>,

    #[serde(default)]
    pub operator: Operator,
}

/// One ACL criterion for a `baton-metaquery` search — find objects
/// where `owner` (with optional `zone`) has the given access `level`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AccessQuery {
    pub owner: String,
    pub level: AclLevel,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub zone: Option<String>,
}

/// Top-level input record for `baton-metaquery`.
///
/// Each field is independently optional. Multiple `AvuQuery` entries
/// are treated as AND (the query layer runs per-AVU subqueries and
/// intersects results — `rcGenQuery` doesn't naturally express
/// metadata self-joins). Multiple timestamps are also AND. Multiple
/// access entries are AND.
///
/// `collection` and `zone` are scoping fields restricting the search
/// to a particular subtree / zone respectively.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct MetaqueryInput {
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub avus: Vec<AvuQuery>,

    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub timestamps: Vec<TimestampQuery>,

    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    pub access: Vec<AccessQuery>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub collection: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub zone: Option<String>,
}

// --- baton-do multiplexer types ---------------------------------------------
//
// `baton-do` accepts a JSON envelope per NDJSON line, dispatches to the
// matching per-op function, and emits the input echoed with a `result`
// or `error` field added. Wire shape matches upstream baton-do exactly
// (see issue #36's gap-analysis comment for the source citations).

/// Operations the `baton-do` multiplexer dispatches to.
///
/// Eleven variants covering the existing six operations (`list` / `get` /
/// `put` / `chmod` / `metamod` / `metaquery`) plus the five
/// `baton-do`-only ones added in Session 7a (`checksum` / `move` /
/// `remove` / `mkdir` / `rmdir`). The wire form is bare lowercase.
///
/// Anything else on input → serde fails to deserialise; the binary
/// surfaces it as a parse error per the upstream-mirroring drop
/// (deviation tracked in #37).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Operation {
    List,
    Get,
    Put,
    Chmod,
    Metamod,
    Metaquery,
    Checksum,
    Move,
    Remove,
    Mkdir,
    Rmdir,
}

/// Per-call argument bag in the `baton-do` envelope.
///
/// Flat namespace of all per-operation flags. Each field is optional
/// on the wire (`#[serde(default)]`); `None` / `false` means the flag
/// wasn't requested. Fields enumerate the predicates upstream baton's
/// dispatcher checks (`baton/src/json.h:118-136`,
/// `baton/src/json.c:584-658`):
///
/// - `acl` / `avu` / `replicate` / `timestamp` / `size` / `checksum` /
///   `contents`: output-decoration flags shared with `baton-list` and
///   `baton-metaquery`.
/// - `verify`: `baton-put`'s client-side hashing flag.
/// - `save`: `baton-get` save-to-disk mode.
/// - `raw`: accepted-but-no-op (upstream's raw-bytes get mode;
///   baton-rs always returns the inline base64 representation).
/// - `recurse` / `force`: shared by `chmod` / `mkdir` / `rmdir`.
/// - `collection` / `object`: `baton-metaquery` scope flags.
/// - `single_server`: passed through accepted-but-no-op (baton-rs's put
///   path is sequential by construction; documented divergence).
/// - `redirect`: server-side redirect flag, accepted-but-no-op.
/// - `path`: destination path for `move` (where upstream's
///   `arguments.path` lives).
/// - `operation`: metamod's required `"add"` / `"rem"` discriminator
///   (the only argument any operation *requires*).
///
/// Empty arguments serialise as the absent field on the envelope —
/// `is_empty` returns true when every field is at its default.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct Arguments {
    #[serde(default, skip_serializing_if = "is_false")]
    pub acl: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub avu: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub checksum: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub verify: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub contents: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub replicate: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub redirect: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub size: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub timestamp: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub raw: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub save: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub recurse: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub force: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub collection: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub object: bool,
    #[serde(default, skip_serializing_if = "is_false")]
    pub single_server: bool,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,

    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
}

impl Arguments {
    /// True iff every field is at its default — used by
    /// `BatonDoEnvelope` to skip-serialise an absent arguments
    /// block. Matches upstream's "arguments key may be omitted
    /// entirely when no flag is set" behaviour.
    pub fn is_empty(&self) -> bool {
        !self.acl
            && !self.avu
            && !self.checksum
            && !self.verify
            && !self.contents
            && !self.replicate
            && !self.redirect
            && !self.size
            && !self.timestamp
            && !self.raw
            && !self.save
            && !self.recurse
            && !self.force
            && !self.collection
            && !self.object
            && !self.single_server
            && self.path.is_none()
            && self.operation.is_none()
    }
}

/// Helper for `#[serde(skip_serializing_if = "is_false")]` on bool
/// fields — keeps the serialised form free of `"flag":false` noise.
fn is_false(b: &bool) -> bool {
    !*b
}

/// The target field of a [`BatonDoEnvelope`]. Most operations
/// carry a [`Target`]; `metaquery` carries a richer
/// [`MetaqueryInput`] (with `AvuQuery` / `TimestampQuery` /
/// `AccessQuery` operator fields and a top-level `zone`).
///
/// On deserialise, [`BatonDoEnvelope`]'s custom `Deserialize`
/// reads the operation field first and picks the right variant;
/// callers don't construct `EnvelopeTarget` by hand. On
/// serialise, the variants are untagged — the wire shape is
/// just the inner type's JSON, no extra wrapper key.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
#[serde(untagged)]
pub enum EnvelopeTarget {
    Standard(Target),
    Query(MetaqueryInput),
}

impl EnvelopeTarget {
    /// Borrow as `Target`. Returns `None` for the `Query`
    /// variant — callers handling the metaquery operation use
    /// [`Self::as_metaquery_input`] instead.
    pub fn as_target(&self) -> Option<&Target> {
        match self {
            EnvelopeTarget::Standard(t) => Some(t),
            EnvelopeTarget::Query(_) => None,
        }
    }

    /// Borrow as `MetaqueryInput`. Returns `None` for the
    /// `Standard` variant.
    pub fn as_metaquery_input(&self) -> Option<&MetaqueryInput> {
        match self {
            EnvelopeTarget::Standard(_) => None,
            EnvelopeTarget::Query(q) => Some(q),
        }
    }
}

/// Input envelope to `baton-do`. One per NDJSON input line.
///
/// Wire shape: `{"operation": "<op>", "target": {...}, "arguments": {...}?}`.
/// Short aliases `op` / `args` accepted on deserialise (matches
/// upstream's `baton/src/json.h:96-116`); long forms emitted on
/// serialise. Arguments are optional everywhere except `metamod`,
/// which requires `arguments.operation`. The dispatcher enforces
/// that requirement at the call site rather than in serde so the
/// error has a clear per-operation message.
///
/// `target` is an [`EnvelopeTarget`] enum because metaquery's
/// wire-format target shape differs from the rest (it carries
/// query-time operators and a `zone` scope that the standard
/// [`Target`] type doesn't model). The custom `Deserialize`
/// impl reads `operation` first and picks the right variant;
/// for serialisation the variants are untagged so the wire shape
/// stays exactly upstream's.
///
/// Use [`Self::new_standard`] / [`Self::new_metaquery`] to
/// construct envelopes in code without having to spell out the
/// inner enum variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct BatonDoEnvelope {
    pub operation: Operation,

    pub target: EnvelopeTarget,

    #[serde(default, skip_serializing_if = "Arguments::is_empty")]
    pub arguments: Arguments,
}

impl BatonDoEnvelope {
    /// Construct an envelope with a standard [`Target`]. Used by
    /// every operation except `metaquery`.
    pub fn new_standard(
        operation: Operation,
        target: Target,
        arguments: Arguments,
    ) -> Self {
        Self {
            operation,
            target: EnvelopeTarget::Standard(target),
            arguments,
        }
    }

    /// Construct a metaquery envelope. The operation is
    /// implicitly [`Operation::Metaquery`] — the target shape
    /// would be ambiguous otherwise.
    pub fn new_metaquery(input: MetaqueryInput, arguments: Arguments) -> Self {
        Self {
            operation: Operation::Metaquery,
            target: EnvelopeTarget::Query(input),
            arguments,
        }
    }
}

// Custom Deserialize on BatonDoEnvelope: serde can't peek at one
// field's value to drive another field's deserialisation through
// derive macros alone, and we need exactly that — `target`'s
// shape depends on `operation`. Hand-rolled visitor reads the
// JSON map, identifies the operation (accepting the `op` alias),
// then deserialises `target` into the right `EnvelopeTarget`
// variant. `arguments` reads the `args` alias too.
impl<'de> Deserialize<'de> for BatonDoEnvelope {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct EnvelopeVisitor;

        impl<'de> Visitor<'de> for EnvelopeVisitor {
            type Value = BatonDoEnvelope;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("a baton-do envelope object")
            }

            fn visit_map<M>(self, mut map: M) -> Result<Self::Value, M::Error>
            where
                M: MapAccess<'de>,
            {
                // Buffer fields by raw JSON value first; resolve
                // target shape once we know the operation. serde
                // doesn't guarantee key order, so we have to
                // accept any ordering of operation / target /
                // arguments and reconstruct at the end.
                let mut operation: Option<Operation> = None;
                let mut target_value: Option<serde_json::Value> = None;
                let mut arguments_value: Option<serde_json::Value> = None;

                while let Some(key) = map.next_key::<String>()? {
                    match key.as_str() {
                        "operation" | "op" => {
                            if operation.is_some() {
                                return Err(de::Error::duplicate_field("operation"));
                            }
                            operation = Some(map.next_value()?);
                        }
                        "target" => {
                            if target_value.is_some() {
                                return Err(de::Error::duplicate_field("target"));
                            }
                            target_value = Some(map.next_value()?);
                        }
                        "arguments" | "args" => {
                            if arguments_value.is_some() {
                                return Err(de::Error::duplicate_field("arguments"));
                            }
                            arguments_value = Some(map.next_value()?);
                        }
                        _ => {
                            // Skip unknown keys — matches
                            // upstream's tolerance for
                            // forward-compat fields.
                            let _: serde::de::IgnoredAny = map.next_value()?;
                        }
                    }
                }

                let operation = operation
                    .ok_or_else(|| de::Error::missing_field("operation"))?;
                let target_value = target_value
                    .ok_or_else(|| de::Error::missing_field("target"))?;

                let target = match operation {
                    Operation::Metaquery => {
                        let input: MetaqueryInput =
                            serde_json::from_value(target_value).map_err(de::Error::custom)?;
                        EnvelopeTarget::Query(input)
                    }
                    _ => {
                        let t: Target =
                            serde_json::from_value(target_value).map_err(de::Error::custom)?;
                        EnvelopeTarget::Standard(t)
                    }
                };

                let arguments = match arguments_value {
                    Some(v) => serde_json::from_value(v).map_err(de::Error::custom)?,
                    None => Arguments::default(),
                };

                Ok(BatonDoEnvelope {
                    operation,
                    target,
                    arguments,
                })
            }
        }

        deserializer.deserialize_map(EnvelopeVisitor)
    }
}

/// Result payload baton-do attaches to the output envelope on
/// success. Externally-tagged enum: `Single` becomes
/// `{"single": {...}}` on the wire, `Multiple` becomes
/// `{"multiple": [...]}`. Mirrors `add_result`'s behaviour at
/// `baton/src/json.c:1010-1042`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OperationResult {
    Single(Target),
    Multiple(Vec<Target>),
}

/// Output envelope from `baton-do`. Same wire shape as the input
/// envelope plus exactly one of `result` or `error`:
///
/// - `result` carries the per-operation output on success.
/// - `error` carries an in-band annotation on per-input failure.
///
/// Both fields are skip-serialised when `None`; the on-the-wire
/// invariant is "exactly one is present" and the dispatcher
/// enforces this by construction.
///
/// Mirrors the input shape rather than wrapping it via
/// `#[serde(flatten)]` because [`BatonDoEnvelope`]'s custom
/// `Deserialize` doesn't compose with flatten — serde's flatten
/// machinery requires the inner type's deserialise to operate on
/// a content map rather than a freshly-driven map. Inlining the
/// fields here keeps the wire-format identical to upstream
/// (operation / target / arguments at the top level alongside
/// result / error) and keeps the deserialiser explicit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct BatonDoOutput {
    pub operation: Operation,

    pub target: EnvelopeTarget,

    #[serde(default, skip_serializing_if = "Arguments::is_empty")]
    pub arguments: Arguments,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub result: Option<OperationResult>,

    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub error: Option<BatonError>,
}

impl BatonDoOutput {
    /// Build an output from an input envelope plus one of the
    /// outcome fields. The dispatcher uses this to compose the
    /// output line — exactly one of `result` / `error` should be
    /// `Some`, the other `None`.
    pub fn new(
        envelope: BatonDoEnvelope,
        result: Option<OperationResult>,
        error: Option<BatonError>,
    ) -> Self {
        Self {
            operation: envelope.operation,
            target: envelope.target,
            arguments: envelope.arguments,
            result,
            error,
        }
    }
}

// Custom Deserialize on BatonDoOutput, parallel to
// BatonDoEnvelope's. Same operation-driven target dispatch, plus
// the result / error fields that only appear on output.
impl<'de> Deserialize<'de> for BatonDoOutput {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        struct OutputVisitor;

        impl<'de> Visitor<'de> for OutputVisitor {
            type Value = BatonDoOutput;

            fn expecting(&self, f: &mut fmt::Formatter) -> fmt::Result {
                f.write_str("a baton-do output object")
            }

            fn visit_map<M>(self, mut map: M) -> Result<Self::Value, M::Error>
            where
                M: MapAccess<'de>,
            {
                let mut operation: Option<Operation> = None;
                let mut target_value: Option<serde_json::Value> = None;
                let mut arguments_value: Option<serde_json::Value> = None;
                let mut result: Option<OperationResult> = None;
                let mut error: Option<BatonError> = None;

                while let Some(key) = map.next_key::<String>()? {
                    match key.as_str() {
                        "operation" | "op" => {
                            if operation.is_some() {
                                return Err(de::Error::duplicate_field("operation"));
                            }
                            operation = Some(map.next_value()?);
                        }
                        "target" => {
                            if target_value.is_some() {
                                return Err(de::Error::duplicate_field("target"));
                            }
                            target_value = Some(map.next_value()?);
                        }
                        "arguments" | "args" => {
                            if arguments_value.is_some() {
                                return Err(de::Error::duplicate_field("arguments"));
                            }
                            arguments_value = Some(map.next_value()?);
                        }
                        "result" => {
                            if result.is_some() {
                                return Err(de::Error::duplicate_field("result"));
                            }
                            result = Some(map.next_value()?);
                        }
                        "error" => {
                            if error.is_some() {
                                return Err(de::Error::duplicate_field("error"));
                            }
                            error = Some(map.next_value()?);
                        }
                        _ => {
                            let _: serde::de::IgnoredAny = map.next_value()?;
                        }
                    }
                }

                let operation = operation
                    .ok_or_else(|| de::Error::missing_field("operation"))?;
                let target_value = target_value
                    .ok_or_else(|| de::Error::missing_field("target"))?;

                let target = match operation {
                    Operation::Metaquery => {
                        let input: MetaqueryInput =
                            serde_json::from_value(target_value).map_err(de::Error::custom)?;
                        EnvelopeTarget::Query(input)
                    }
                    _ => {
                        let t: Target =
                            serde_json::from_value(target_value).map_err(de::Error::custom)?;
                        EnvelopeTarget::Standard(t)
                    }
                };

                let arguments = match arguments_value {
                    Some(v) => serde_json::from_value(v).map_err(de::Error::custom)?,
                    None => Arguments::default(),
                };

                Ok(BatonDoOutput {
                    operation,
                    target,
                    arguments,
                    result,
                    error,
                })
            }
        }

        deserializer.deserialize_map(OutputVisitor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn irods_path_round_trip() {
        let json = r#""/testZone/home/irods/foo.txt""#;
        let p: IrodsPath = serde_json::from_str(json).unwrap();
        assert_eq!(p.as_str(), "/testZone/home/irods/foo.txt");
        assert_eq!(serde_json::to_string(&p).unwrap(), json);
    }

    #[test]
    fn irods_path_constructors() {
        assert_eq!(IrodsPath::new("/a/b").as_str(), "/a/b");
        assert_eq!(IrodsPath::from("/a/b").as_str(), "/a/b");
        assert_eq!(IrodsPath::from(String::from("/a/b")).as_str(), "/a/b");
    }

    #[test]
    fn data_object_minimal_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt"}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.collection, "/testZone/home/irods");
        assert_eq!(d.data_object, "foo.txt");
        assert_eq!(d.size, None);
        assert_eq!(d.checksum, None);
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn data_object_with_size_and_checksum_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt","size":1024,"checksum":"d41d8cd98f00b204e9800998ecf8427e"}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.size, Some(1024));
        assert_eq!(d.checksum.as_deref(), Some("d41d8cd98f00b204e9800998ecf8427e"));
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn data_object_with_inline_data_round_trip() {
        // baton-get inline mode emits the bytes as base64 in the `data`
        // field. "aGVsbG8=" is the base64 of b"hello".
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt","data":"aGVsbG8="}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.data.as_deref(), Some("aGVsbG8="));
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn data_object_with_save_directory_round_trip() {
        // baton-get --save reads the per-record `directory` field;
        // the field is echoed back on the output unchanged so the
        // caller can correlate input/output records by content.
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt","directory":"/tmp/baton_rs_save"}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.directory.as_deref(), Some("/tmp/baton_rs_save"));
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn collection_minimal_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods"}"#;
        let c: Collection = serde_json::from_str(json).unwrap();
        assert_eq!(c.collection, "/testZone/home/irods");
        assert_eq!(serde_json::to_string(&c).unwrap(), json);
    }

    // --- Avu ---

    #[test]
    fn avu_long_form_round_trip() {
        let json = r#"{"attribute":"sample","value":"12345","units":"id"}"#;
        let a: Avu = serde_json::from_str(json).unwrap();
        assert_eq!(a.attribute, "sample");
        assert_eq!(a.value, "12345");
        assert_eq!(a.units.as_deref(), Some("id"));
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    #[test]
    fn avu_short_form_deserialises_and_emits_long_form() {
        let short = r#"{"a":"sample","v":"12345","u":"id"}"#;
        let long = r#"{"attribute":"sample","value":"12345","units":"id"}"#;
        let a: Avu = serde_json::from_str(short).unwrap();
        assert_eq!(a.attribute, "sample");
        assert_eq!(a.value, "12345");
        assert_eq!(a.units.as_deref(), Some("id"));
        assert_eq!(serde_json::to_string(&a).unwrap(), long);
    }

    #[test]
    fn avu_without_units() {
        let json = r#"{"attribute":"sample","value":"12345"}"#;
        let a: Avu = serde_json::from_str(json).unwrap();
        assert_eq!(a.units, None);
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    // --- Acl ---

    #[test]
    fn acl_with_zone_round_trip() {
        let json = r#"{"owner":"irods","level":"own","zone":"testZone"}"#;
        let a: Acl = serde_json::from_str(json).unwrap();
        assert_eq!(a.owner, "irods");
        assert_eq!(a.level, AclLevel::Own);
        assert_eq!(a.zone.as_deref(), Some("testZone"));
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    #[test]
    fn acl_without_zone_round_trip() {
        let json = r#"{"owner":"irods","level":"read"}"#;
        let a: Acl = serde_json::from_str(json).unwrap();
        assert_eq!(a.level, AclLevel::Read);
        assert_eq!(a.zone, None);
        assert_eq!(serde_json::to_string(&a).unwrap(), json);
    }

    #[test]
    fn acl_all_levels_round_trip() {
        for (literal, level) in [
            (r#""null""#, AclLevel::Null),
            (r#""read""#, AclLevel::Read),
            (r#""write""#, AclLevel::Write),
            (r#""own""#, AclLevel::Own),
        ] {
            let parsed: AclLevel = serde_json::from_str(literal).unwrap();
            assert_eq!(parsed, level);
            assert_eq!(serde_json::to_string(&parsed).unwrap(), literal);
        }
    }

    #[test]
    fn acl_level_as_irods_str_is_bare_lowercase() {
        // Pin the exact strings iRODS's modAccessControlInp_t accepts.
        // Upstream baton hardcodes the same four (baton/src/query.h:52-55);
        // anything else triggers CAT_INVALID_ARGUMENT server-side.
        // Distinct from serde's JSON representation, which would
        // quote the values.
        assert_eq!(AclLevel::Null.as_irods_str(), "null");
        assert_eq!(AclLevel::Read.as_irods_str(), "read");
        assert_eq!(AclLevel::Write.as_irods_str(), "write");
        assert_eq!(AclLevel::Own.as_irods_str(), "own");
    }

    // --- Replicate ---

    #[test]
    fn replicate_round_trip() {
        let json = r#"{"checksum":"d41d8cd98f00b204e9800998ecf8427e","location":"host","resource":"demoResc","number":0,"valid":true}"#;
        let r: Replicate = serde_json::from_str(json).unwrap();
        assert_eq!(r.checksum, "d41d8cd98f00b204e9800998ecf8427e");
        assert_eq!(r.location, "host");
        assert_eq!(r.resource, "demoResc");
        assert_eq!(r.number, 0);
        assert!(r.valid);
        assert_eq!(serde_json::to_string(&r).unwrap(), json);
    }

    // --- Timestamp ---

    #[test]
    fn timestamp_created_round_trip() {
        let json = r#"{"created":"2024-01-01T00:00:00"}"#;
        let t: Timestamp = serde_json::from_str(json).unwrap();
        assert_eq!(t.created.as_deref(), Some("2024-01-01T00:00:00"));
        assert_eq!(t.modified, None);
        assert_eq!(t.replicate, None);
        assert_eq!(serde_json::to_string(&t).unwrap(), json);
    }

    #[test]
    fn timestamp_modified_round_trip() {
        let json = r#"{"modified":"2024-01-02T12:34:56"}"#;
        let t: Timestamp = serde_json::from_str(json).unwrap();
        assert_eq!(t.modified.as_deref(), Some("2024-01-02T12:34:56"));
        assert_eq!(serde_json::to_string(&t).unwrap(), json);
    }

    #[test]
    fn timestamp_with_replicate_round_trip() {
        let json = r#"{"created":"2024-01-01T00:00:00","replicate":0}"#;
        let t: Timestamp = serde_json::from_str(json).unwrap();
        assert_eq!(t.replicate, Some(0));
        assert_eq!(serde_json::to_string(&t).unwrap(), json);
    }

    // --- Extended DataObject / Collection ---

    #[test]
    fn data_object_with_avus_and_access_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","data_object":"foo.txt","avus":[{"attribute":"sample","value":"12345"}],"access":[{"owner":"irods","level":"own","zone":"testZone"}]}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.avus.as_ref().map(Vec::len), Some(1));
        assert_eq!(d.access.as_ref().map(Vec::len), Some(1));
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    #[test]
    fn collection_with_avus_round_trip() {
        let json = r#"{"collection":"/testZone/home/irods","avus":[{"attribute":"project","value":"baton-rs"}]}"#;
        let c: Collection = serde_json::from_str(json).unwrap();
        assert_eq!(c.avus.as_ref().map(Vec::len), Some(1));
        assert_eq!(serde_json::to_string(&c).unwrap(), json);
    }

    // --- Target ---

    #[test]
    fn target_deserialises_as_data_object_when_data_object_present() {
        let json = r#"{"collection":"/z/home/u","data_object":"foo.txt"}"#;
        let t: Target = serde_json::from_str(json).unwrap();
        match t {
            Target::DataObject(d) => {
                assert_eq!(d.collection, "/z/home/u");
                assert_eq!(d.data_object, "foo.txt");
            }
            _ => panic!("expected DataObject"),
        }
    }

    #[test]
    fn target_deserialises_as_collection_without_data_object() {
        let json = r#"{"collection":"/z/home/u"}"#;
        let t: Target = serde_json::from_str(json).unwrap();
        match t {
            Target::Collection(c) => assert_eq!(c.collection, "/z/home/u"),
            _ => panic!("expected Collection"),
        }
    }

    #[test]
    fn target_path_joins_collection_and_data_object() {
        let d = DataObject {
            collection: "/z/home/u".to_string(),
            data_object: "foo.txt".to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        };
        assert_eq!(Target::DataObject(d).path(), "/z/home/u/foo.txt");
    }

    #[test]
    fn target_path_handles_trailing_slash_on_collection() {
        let d = DataObject {
            collection: "/z/home/u/".to_string(),
            data_object: "foo.txt".to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        };
        assert_eq!(Target::DataObject(d).path(), "/z/home/u/foo.txt");
    }

    #[test]
    fn target_path_for_collection_is_collection() {
        let c = Collection {
            collection: "/z/home/u".to_string(),
            avus: None,
            access: None,
            timestamps: None,
            contents: None,
            error: None,
        };
        assert_eq!(Target::Collection(c).path(), "/z/home/u");
    }

    #[test]
    fn collection_contents_round_trip_mixed_items() {
        // Mixed listing: a sub-collection and a data object as direct
        // children of the parent.
        let json = r#"{"collection":"/z/home/u","contents":[{"collection":"/z/home/u/sub"},{"collection":"/z/home/u","data_object":"foo.txt"}]}"#;
        let c: Collection = serde_json::from_str(json).unwrap();
        let items = c.contents.as_ref().expect("contents populated");
        assert_eq!(items.len(), 2);
        // First child is a sub-collection.
        match &items[0] {
            Target::Collection(sub) => assert_eq!(sub.collection, "/z/home/u/sub"),
            other => panic!("expected sub-collection, got {:?}", other),
        }
        // Second child is a data object.
        match &items[1] {
            Target::DataObject(d) => {
                assert_eq!(d.collection, "/z/home/u");
                assert_eq!(d.data_object, "foo.txt");
            }
            other => panic!("expected data object, got {:?}", other),
        }
        assert_eq!(serde_json::to_string(&c).unwrap(), json);
    }

    #[test]
    fn collection_without_contents_omits_field_on_serialise() {
        let c = Collection {
            collection: "/z/home/u".to_string(),
            avus: None,
            access: None,
            timestamps: None,
            contents: None,
            error: None,
        };
        // skip_serializing_if = "Option::is_none" keeps the field absent
        // when nothing populates it — matches every other optional field.
        assert_eq!(
            serde_json::to_string(&c).unwrap(),
            r#"{"collection":"/z/home/u"}"#
        );
    }

    #[test]
    fn target_set_error_annotates_data_object() {
        let mut t = Target::DataObject(DataObject {
            collection: "/x".to_string(),
            data_object: "y".to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        });
        t.set_error(BatonError::from_irods(-310000));
        match t {
            Target::DataObject(d) => {
                assert_eq!(d.error.as_ref().map(|e| e.code), Some(-310000));
            }
            _ => panic!("expected DataObject"),
        }
    }

    #[test]
    fn data_object_with_error_round_trip() {
        let json = r#"{"collection":"/z","data_object":"y","error":{"code":-310000,"message":"USER_FILE_DOES_NOT_EXIST"}}"#;
        let d: DataObject = serde_json::from_str(json).unwrap();
        assert_eq!(d.error.as_ref().map(|e| e.code), Some(-310000));
        assert_eq!(
            d.error.as_ref().map(|e| e.message.as_str()),
            Some("USER_FILE_DOES_NOT_EXIST")
        );
        assert_eq!(serde_json::to_string(&d).unwrap(), json);
    }

    // --- MetamodInput ---

    #[test]
    fn metamod_operation_round_trip_lowercase() {
        let add: MetamodOperation = serde_json::from_str(r#""add""#).unwrap();
        assert_eq!(add, MetamodOperation::Add);
        assert_eq!(serde_json::to_string(&add).unwrap(), r#""add""#);

        let rm: MetamodOperation = serde_json::from_str(r#""rm""#).unwrap();
        assert_eq!(rm, MetamodOperation::Rm);
        assert_eq!(serde_json::to_string(&rm).unwrap(), r#""rm""#);
    }

    #[test]
    fn metamod_input_data_object_round_trip() {
        let json = r#"{"collection":"/z/home/u","data_object":"foo.txt","operation":"add","avus":[{"attribute":"a","value":"v","units":"u"}]}"#;
        let input: MetamodInput = serde_json::from_str(json).unwrap();
        assert_eq!(input.collection, "/z/home/u");
        assert_eq!(input.data_object.as_deref(), Some("foo.txt"));
        assert_eq!(input.operation, MetamodOperation::Add);
        assert_eq!(input.avus.len(), 1);
        assert_eq!(input.avus[0].attribute, "a");
        assert_eq!(input.error, None);
        assert_eq!(serde_json::to_string(&input).unwrap(), json);
    }

    #[test]
    fn metamod_input_collection_round_trip() {
        // No data_object key for a collection target.
        let json = r#"{"collection":"/z/home/u","operation":"rm","avus":[]}"#;
        let input: MetamodInput = serde_json::from_str(json).unwrap();
        assert_eq!(input.data_object, None);
        assert_eq!(input.operation, MetamodOperation::Rm);
        assert!(input.avus.is_empty());
        assert_eq!(serde_json::to_string(&input).unwrap(), json);
    }

    #[test]
    fn metamod_input_target_data_object() {
        let input = MetamodInput {
            collection: "/z/home/u".to_string(),
            data_object: Some("foo.txt".to_string()),
            operation: MetamodOperation::Add,
            avus: vec![],
            error: None,
        };
        match input.target() {
            Target::DataObject(d) => {
                assert_eq!(d.collection, "/z/home/u");
                assert_eq!(d.data_object, "foo.txt");
                // None of the metadata fields are seeded by .target().
                assert!(d.avus.is_none());
                assert!(d.access.is_none());
            }
            other => panic!("expected DataObject, got {:?}", other),
        }
    }

    #[test]
    fn metamod_input_target_collection() {
        let input = MetamodInput {
            collection: "/z/home/u".to_string(),
            data_object: None,
            operation: MetamodOperation::Rm,
            avus: vec![],
            error: None,
        };
        match input.target() {
            Target::Collection(c) => assert_eq!(c.collection, "/z/home/u"),
            other => panic!("expected Collection, got {:?}", other),
        }
    }

    #[test]
    fn metamod_input_with_error_annotation_round_trip() {
        let json = r#"{"collection":"/z/home/u","data_object":"foo.txt","operation":"add","avus":[],"error":{"code":-310000,"message":"USER_FILE_DOES_NOT_EXIST"}}"#;
        let input: MetamodInput = serde_json::from_str(json).unwrap();
        assert_eq!(input.error.as_ref().map(|e| e.code), Some(-310000));
        assert_eq!(serde_json::to_string(&input).unwrap(), json);
    }

    // --- Operator ---

    #[test]
    fn operator_round_trip_all_variants() {
        for (literal, op) in [
            (r#""=""#, Operator::Equals),
            (r#""like""#, Operator::Like),
            (r#""not like""#, Operator::NotLike),
            (r#""in""#, Operator::In),
            (r#"">""#, Operator::GreaterThan),
            (r#""n>""#, Operator::NumericGreaterThan),
            (r#""<""#, Operator::LessThan),
            (r#""n<""#, Operator::NumericLessThan),
            (r#"">=""#, Operator::GreaterThanOrEqual),
            (r#""n>=""#, Operator::NumericGreaterThanOrEqual),
            (r#""<=""#, Operator::LessThanOrEqual),
            (r#""n<=""#, Operator::NumericLessThanOrEqual),
        ] {
            let parsed: Operator = serde_json::from_str(literal).unwrap();
            assert_eq!(parsed, op);
            assert_eq!(serde_json::to_string(&parsed).unwrap(), literal);
        }
    }

    #[test]
    fn operator_default_is_equals() {
        assert_eq!(Operator::default(), Operator::Equals);
    }

    // --- AvuQuery / MetaqueryInput / TimestampQuery / AccessQuery ---

    #[test]
    fn avu_query_with_explicit_operator_round_trip() {
        let json = r#"{"attribute":"sample","value":"12*","operator":"like"}"#;
        let q: AvuQuery = serde_json::from_str(json).unwrap();
        assert_eq!(q.attribute, "sample");
        assert_eq!(q.operator, Operator::Like);
        assert_eq!(serde_json::to_string(&q).unwrap(), json);
    }

    #[test]
    fn avu_query_default_operator_is_equals() {
        // Operator omitted from input → defaults to Equals.
        let q: AvuQuery = serde_json::from_str(
            r#"{"attribute":"sample","value":"12345"}"#,
        )
        .unwrap();
        assert_eq!(q.operator, Operator::Equals);
        // Round-trip emits the operator explicitly (no skip on default).
        assert_eq!(
            serde_json::to_string(&q).unwrap(),
            r#"{"attribute":"sample","value":"12345","operator":"="}"#
        );
    }

    #[test]
    fn timestamp_query_round_trip() {
        let json = r#"{"created":"2024-01-01T00:00:00","operator":">="}"#;
        let q: TimestampQuery = serde_json::from_str(json).unwrap();
        assert_eq!(q.created.as_deref(), Some("2024-01-01T00:00:00"));
        assert_eq!(q.modified, None);
        assert_eq!(q.operator, Operator::GreaterThanOrEqual);
        assert_eq!(serde_json::to_string(&q).unwrap(), json);
    }

    #[test]
    fn access_query_with_zone_round_trip() {
        let json = r#"{"owner":"irods","level":"read","zone":"testZone"}"#;
        let q: AccessQuery = serde_json::from_str(json).unwrap();
        assert_eq!(q.owner, "irods");
        assert_eq!(q.level, AclLevel::Read);
        assert_eq!(q.zone.as_deref(), Some("testZone"));
        assert_eq!(serde_json::to_string(&q).unwrap(), json);
    }

    #[test]
    fn metaquery_input_full_round_trip() {
        let json = r#"{"avus":[{"attribute":"sample","value":"12345","operator":"="}],"timestamps":[{"created":"2024-01-01T00:00:00","operator":">="}],"access":[{"owner":"irods","level":"own"}],"collection":"/testZone/home/irods","zone":"testZone"}"#;
        let q: MetaqueryInput = serde_json::from_str(json).unwrap();
        assert_eq!(q.avus.len(), 1);
        assert_eq!(q.timestamps.len(), 1);
        assert_eq!(q.access.len(), 1);
        assert_eq!(q.collection.as_deref(), Some("/testZone/home/irods"));
        assert_eq!(serde_json::to_string(&q).unwrap(), json);
    }

    #[test]
    fn metaquery_input_empty_round_trip() {
        // Empty Vec fields and None scoping fields all serde-skip, so
        // the canonical empty input is just `{}` — and serializes back
        // to the same.
        let q: MetaqueryInput = serde_json::from_str("{}").unwrap();
        assert!(q.avus.is_empty());
        assert!(q.timestamps.is_empty());
        assert!(q.access.is_empty());
        assert_eq!(q.collection, None);
        assert_eq!(q.zone, None);
        assert_eq!(serde_json::to_string(&q).unwrap(), "{}");
    }

    // --- baton-do envelope and result types ---------------------------------

    #[test]
    fn operation_round_trip_all_eleven_variants() {
        // Pin every operation name to the bare lowercase wire
        // form. The set is closed — matches upstream baton-do's
        // dispatcher (baton/src/operations.c) exactly.
        for (literal, op) in [
            (r#""list""#, Operation::List),
            (r#""get""#, Operation::Get),
            (r#""put""#, Operation::Put),
            (r#""chmod""#, Operation::Chmod),
            (r#""metamod""#, Operation::Metamod),
            (r#""metaquery""#, Operation::Metaquery),
            (r#""checksum""#, Operation::Checksum),
            (r#""move""#, Operation::Move),
            (r#""remove""#, Operation::Remove),
            (r#""mkdir""#, Operation::Mkdir),
            (r#""rmdir""#, Operation::Rmdir),
        ] {
            let parsed: Operation = serde_json::from_str(literal).unwrap();
            assert_eq!(parsed, op, "deserialise {literal:?}");
            assert_eq!(serde_json::to_string(&parsed).unwrap(), literal);
        }
    }

    #[test]
    fn arguments_default_is_empty_and_serialises_as_empty_object() {
        let args = Arguments::default();
        assert!(args.is_empty());
        assert_eq!(serde_json::to_string(&args).unwrap(), "{}");
    }

    #[test]
    fn arguments_round_trip_drops_default_fields_on_serialise() {
        // Only the populated fields appear on the wire; defaults
        // are skip-serialised. Deserialise re-fills the absent
        // fields with defaults.
        let mut args = Arguments::default();
        args.recurse = true;
        args.path = Some("/zone/home/u/dst".to_string());
        let json = serde_json::to_string(&args).unwrap();
        assert_eq!(json, r#"{"recurse":true,"path":"/zone/home/u/dst"}"#);
        let parsed: Arguments = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, args);
    }

    #[test]
    fn arguments_metamod_operation_field_round_trips() {
        // metamod's required arguments.operation field is a
        // string ("add" / "rem"). The dispatcher validates the
        // value; serde just round-trips the string.
        let args: Arguments =
            serde_json::from_str(r#"{"operation":"add"}"#).unwrap();
        assert_eq!(args.operation.as_deref(), Some("add"));
        assert_eq!(
            serde_json::to_string(&args).unwrap(),
            r#"{"operation":"add"}"#
        );
    }

    #[test]
    fn baton_do_envelope_minimal_round_trip() {
        // Smallest legal envelope: operation + target. No
        // arguments — skip-serialised because Arguments::is_empty
        // is true.
        let json = r#"{"operation":"list","target":{"collection":"/zone/home/u","data_object":"foo.txt"}}"#;
        let env: BatonDoEnvelope = serde_json::from_str(json).unwrap();
        assert_eq!(env.operation, Operation::List);
        assert!(env.arguments.is_empty());
        assert_eq!(serde_json::to_string(&env).unwrap(), json);
    }

    #[test]
    fn baton_do_envelope_with_arguments_round_trips() {
        let json = r#"{"operation":"chmod","target":{"collection":"/zone/home/u"},"arguments":{"recurse":true}}"#;
        let env: BatonDoEnvelope = serde_json::from_str(json).unwrap();
        assert_eq!(env.operation, Operation::Chmod);
        assert!(env.arguments.recurse);
        assert_eq!(serde_json::to_string(&env).unwrap(), json);
    }

    #[test]
    fn baton_do_envelope_short_form_aliases_deserialise() {
        // baton/src/json.h:96-116 documents `op` / `args` short
        // aliases; we accept both on input but emit the long
        // forms on output.
        let json = r#"{"op":"checksum","target":{"collection":"/zone/home/u","data_object":"foo.txt"},"args":{"force":true}}"#;
        let env: BatonDoEnvelope = serde_json::from_str(json).unwrap();
        assert_eq!(env.operation, Operation::Checksum);
        assert!(env.arguments.force);
        // Round-trip emits the long form even though the input
        // used short aliases.
        let long = r#"{"operation":"checksum","target":{"collection":"/zone/home/u","data_object":"foo.txt"},"arguments":{"force":true}}"#;
        assert_eq!(serde_json::to_string(&env).unwrap(), long);
    }

    #[test]
    fn operation_result_single_and_multiple_round_trip() {
        // Externally-tagged enum: variant name becomes the key.
        // Mirrors `add_result`'s wire shape at
        // baton/src/json.c:1010-1042.
        let single_json = r#"{"single":{"collection":"/x","data_object":"y"}}"#;
        let single: OperationResult = serde_json::from_str(single_json).unwrap();
        assert!(matches!(single, OperationResult::Single(_)));
        assert_eq!(serde_json::to_string(&single).unwrap(), single_json);

        let multiple_json = r#"{"multiple":[{"collection":"/x","data_object":"y"},{"collection":"/x","data_object":"z"}]}"#;
        let multiple: OperationResult =
            serde_json::from_str(multiple_json).unwrap();
        match &multiple {
            OperationResult::Multiple(items) => assert_eq!(items.len(), 2),
            other => panic!("expected Multiple, got {:?}", other),
        }
        assert_eq!(serde_json::to_string(&multiple).unwrap(), multiple_json);
    }

    #[test]
    fn baton_do_output_with_result_round_trips() {
        // Success output: input echoed plus a `result` field.
        // BatonDoOutput inlines the envelope fields directly
        // rather than flattening (custom Deserialize doesn't
        // compose with serde flatten); wire shape stays
        // identical to upstream's add_result mutation of the
        // input item.
        let json = r#"{"operation":"list","target":{"collection":"/x","data_object":"y"},"result":{"single":{"collection":"/x","data_object":"y","size":1024}}}"#;
        let out: BatonDoOutput = serde_json::from_str(json).unwrap();
        assert_eq!(out.operation, Operation::List);
        assert!(out.result.is_some());
        assert!(out.error.is_none());
        assert_eq!(serde_json::to_string(&out).unwrap(), json);
    }

    #[test]
    fn baton_do_output_with_error_round_trips() {
        // Failure output: input echoed plus an `error` field, no
        // `result`. Mirrors upstream's `add_error_value` path
        // (`baton/src/operations.c:129-136`).
        let json = r#"{"operation":"get","target":{"collection":"/x","data_object":"missing"},"error":{"code":-310000,"message":"USER_FILE_DOES_NOT_EXIST"}}"#;
        let out: BatonDoOutput = serde_json::from_str(json).unwrap();
        assert_eq!(out.operation, Operation::Get);
        assert!(out.result.is_none());
        assert_eq!(out.error.as_ref().map(|e| e.code), Some(-310000));
        assert_eq!(serde_json::to_string(&out).unwrap(), json);
    }

    #[test]
    fn baton_do_envelope_metaquery_target_is_metaquery_input() {
        // The metaquery operation gets a richer target shape:
        // AvuQuery (with operator) instead of Avu, and a
        // top-level zone scope. The custom Deserialize on the
        // envelope reads the operation field first and picks the
        // right EnvelopeTarget variant.
        let json = r#"{"operation":"metaquery","target":{"avus":[{"attribute":"sample","value":"12*","operator":"like"}],"zone":"testZone"}}"#;
        let env: BatonDoEnvelope = serde_json::from_str(json).unwrap();
        assert_eq!(env.operation, Operation::Metaquery);
        let q = env.target.as_metaquery_input().expect("metaquery variant");
        assert_eq!(q.avus.len(), 1);
        assert_eq!(q.avus[0].operator, Operator::Like);
        assert_eq!(q.zone.as_deref(), Some("testZone"));
        // The raw target shape round-trips because the
        // EnvelopeTarget enum is untagged on serialise (no
        // wrapper key around the inner JSON).
        assert_eq!(serde_json::to_string(&env).unwrap(), json);
    }

    #[test]
    fn baton_do_envelope_non_metaquery_target_is_standard_target() {
        // Non-metaquery operations carry a plain Target. JSON
        // shapes that overlap (like a bare {"collection": "/x"})
        // still get routed correctly because the custom
        // Deserialize switches on operation before parsing
        // target.
        let json = r#"{"operation":"chmod","target":{"collection":"/x"}}"#;
        let env: BatonDoEnvelope = serde_json::from_str(json).unwrap();
        assert_eq!(env.operation, Operation::Chmod);
        match env.target.as_target() {
            Some(Target::Collection(c)) => assert_eq!(c.collection, "/x"),
            other => panic!("expected Collection target, got {:?}", other),
        }
    }

    #[test]
    fn baton_do_envelope_constructor_helpers_round_trip() {
        // Code-side construction goes through new_standard /
        // new_metaquery — callers don't have to spell out the
        // EnvelopeTarget variant by hand.
        let target = Target::DataObject(DataObject {
            collection: "/x".to_string(),
            data_object: "y".to_string(),
            size: None,
            checksum: None,
            data: None,
            directory: None,
            avus: None,
            access: None,
            replicates: None,
            timestamps: None,
            error: None,
        });
        let env = BatonDoEnvelope::new_standard(
            Operation::List,
            target,
            Arguments::default(),
        );
        assert!(matches!(env.target, EnvelopeTarget::Standard(_)));

        let mut q = MetaqueryInput::default();
        q.zone = Some("testZone".to_string());
        let env_q = BatonDoEnvelope::new_metaquery(q, Arguments::default());
        assert_eq!(env_q.operation, Operation::Metaquery);
        assert!(matches!(env_q.target, EnvelopeTarget::Query(_)));
    }
}
