// Generated by:     Claude Opus 4.7 (1M context)
// Generation date:  2026-05-08
// Last modified by: Claude Opus 4.7 (1M context)
// Last modified:    2026-05-08

//! Version-string reporting for the `--version` flag on every
//! baton-rs binary.
//!
//! Two modes:
//!
//! - **Default** (env var unset): report the real baton-rs crate
//!   version from `CARGO_PKG_VERSION`. Honest reporting; logs and
//!   debug surfaces never lie about what's running.
//! - **`STRICT_BATON_COMPAT` env var set to any non-empty value**:
//!   report [`BATON_COMPAT_VERSION`], the upstream baton release
//!   we target wire-compat with. Lets downstream consumers
//!   (partisan, extendo, …) probe `baton-do --version` and parse
//!   it as if it were upstream baton — needed because partisan's
//!   `client_version()` (`partisan/src/partisan/irods.py:1589`)
//!   compares the result against expected baton X.Y.Z values.
//!
//! Any-non-empty semantics matches `RUST_LOG` / `RUST_BACKTRACE` /
//! standard Unix convention. Set `STRICT_BATON_COMPAT=1` (or any
//! non-empty value) to enable.
//!
//! Future compat divergences (parse-error wire shape #37,
//! partisan's `calculate`/`recalculate` checksum aliases, …) gate
//! on the same env var so callers don't have to learn a new flag
//! per feature. See issue #58 for the design discussion and
//! release-checklist.

/// Upstream baton version baton-rs targets wire-compat with.
///
/// Bumped in lockstep with the `Target baton version` decision
/// recorded in `SESSIONS.md` whenever we re-pin against a newer
/// upstream baton. The release checklist in #58 calls out this
/// audit step explicitly.
pub const BATON_COMPAT_VERSION: &str = "6.0.0";

/// Env var that toggles compat-mode version reporting. See module
/// doc-comment for the rationale and #58 for the design.
pub const STRICT_BATON_COMPAT_ENV: &str = "STRICT_BATON_COMPAT";

/// The version string each binary's `--version` flag should print.
///
/// Returns [`BATON_COMPAT_VERSION`] when `STRICT_BATON_COMPAT` is
/// set to any non-empty value, otherwise the running crate's
/// `CARGO_PKG_VERSION`. Output is intended to be printed bare
/// (`println!("{}", report_version())`) and parsed by downstream
/// tools as `<X>.<Y>.<Z>` — same shape upstream baton-do's
/// `--version` emits.
pub fn report_version() -> &'static str {
    match std::env::var_os(STRICT_BATON_COMPAT_ENV) {
        Some(val) if !val.is_empty() => BATON_COMPAT_VERSION,
        _ => env!("CARGO_PKG_VERSION"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Lock used to serialise the env-mutating tests. `cargo test`
    /// runs tests in parallel by default; without a lock, two tests
    /// flipping `STRICT_BATON_COMPAT` would race and one would see
    /// the other's value.
    fn env_lock() -> std::sync::MutexGuard<'static, ()> {
        use std::sync::{Mutex, OnceLock};
        static LOCK: OnceLock<Mutex<()>> = OnceLock::new();
        // Recover from a poisoned lock — a panicking test still
        // released the env var via the RAII guard below, so the
        // remaining state is consistent.
        LOCK.get_or_init(|| Mutex::new(()))
            .lock()
            .unwrap_or_else(|p| p.into_inner())
    }

    /// RAII guard: records the env var's previous value at
    /// construction, restores it on drop. Keeps tests honest in
    /// the face of CI runners that pre-set `STRICT_BATON_COMPAT`.
    struct EnvGuard {
        prior: Option<std::ffi::OsString>,
    }
    impl EnvGuard {
        fn capture() -> Self {
            Self {
                prior: std::env::var_os(STRICT_BATON_COMPAT_ENV),
            }
        }
    }
    impl Drop for EnvGuard {
        fn drop(&mut self) {
            // SAFETY: env mutations are unsafe in Rust 2024; this
            // helper is test-only and serialised via env_lock.
            unsafe {
                match &self.prior {
                    Some(v) => std::env::set_var(STRICT_BATON_COMPAT_ENV, v),
                    None => std::env::remove_var(STRICT_BATON_COMPAT_ENV),
                }
            }
        }
    }

    #[test]
    fn report_version_unset_returns_crate_version() {
        let _lock = env_lock();
        let _guard = EnvGuard::capture();
        unsafe {
            std::env::remove_var(STRICT_BATON_COMPAT_ENV);
        }
        assert_eq!(report_version(), env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn report_version_empty_string_returns_crate_version() {
        // Empty value treated as unset — matches RUST_LOG and
        // most Unix tooling.
        let _lock = env_lock();
        let _guard = EnvGuard::capture();
        unsafe {
            std::env::set_var(STRICT_BATON_COMPAT_ENV, "");
        }
        assert_eq!(report_version(), env!("CARGO_PKG_VERSION"));
    }

    #[test]
    fn report_version_set_returns_compat_version() {
        let _lock = env_lock();
        let _guard = EnvGuard::capture();
        unsafe {
            std::env::set_var(STRICT_BATON_COMPAT_ENV, "1");
        }
        assert_eq!(report_version(), BATON_COMPAT_VERSION);
    }

    #[test]
    fn report_version_arbitrary_truthy_value_returns_compat_version() {
        // Any-non-empty semantics: "true", "yes", "0", "anything"
        // all flip the toggle. No string-value parsing.
        let _lock = env_lock();
        let _guard = EnvGuard::capture();
        unsafe {
            std::env::set_var(STRICT_BATON_COMPAT_ENV, "anything-nonempty");
        }
        assert_eq!(report_version(), BATON_COMPAT_VERSION);
    }

    #[test]
    fn baton_compat_version_is_xyz_shape() {
        // Belt-and-braces: BATON_COMPAT_VERSION must parse as
        // <X>.<Y>.<Z> with all-digit components, since downstream
        // consumers (partisan) parse it via int().
        let parts: Vec<&str> = BATON_COMPAT_VERSION.split('.').collect();
        assert_eq!(parts.len(), 3, "BATON_COMPAT_VERSION must be X.Y.Z");
        for p in &parts {
            assert!(
                !p.is_empty() && p.bytes().all(|b| b.is_ascii_digit()),
                "BATON_COMPAT_VERSION component {:?} must be non-empty digits",
                p
            );
        }
    }
}
